### ISSUE TITLE
Icons overlap

### ISSUE THREAD

**Issue by natcl** [dceejay/RedMap#1]
I assume this is not normal ?
![capture d ecran 2016-05-14 a 14 22 36](https://cloud.githubusercontent.com/assets/77556/15270020/6bb2f90c-19df-11e6-9be8-957224f3474e.png)

**Comment by dceejay** [comment]
guess that isn't chrome... ;-(

**Comment by natcl** [comment]
Yeah Safari on OS X 10.11
