### ISSUE TITLE
Heat map layer

### ISSUE THREAD

**Issue by nakiabrewer** [dceejay/RedMap#10]
Hi,

Have you given thought to opening up how one could control the heat map layer ?

Right now it appears to just increase the intensity  based on the count of positions in the area but is there a way to assign a value to set the intensity (heat level).

Example:
I am plotting my drive to an from work each day and would like to plot the fuel usage as a heat map on each of the positions I record along the way.

Maybe a new parameter like msg.payload {heatmap_intensity: 1 - 5}

Happy to make he modifications to the node if you could give me a little starter assistance ??

**Comment by dceejay** [comment]
Hi

I could add a command option .heatmap    which could contain an options object from the underlying library - https://github.com/Leaflet/Leaflet.heat

so radius and gradient probably most useful...

though I think the way the heatmap works is that the colours are more intense the more points are plotted... so not sure how you translate fuel consumption into more points...

**Comment by dceejay** [comment]
eg   send      msg.payload.control.heatmap = {gradient:{0.4: 'blue', 0.65: 'lime', 1: 'red'}};

**Comment by nakiabrewer** [comment]
Wow, that was fast to get that done!

After looking at that link you provided in the Readme it looks like intensity is an optional 3rd argument in the LatLng parameter of L.heatLayer(latlngs, options). Is there a way to expose that in the Node Red Module? Maybe a new optional property for msg.payload like **{add-to-heat: Boolean, intensity:0.0-1.0,}**

From leaflet github readme below:
"Optional third argument in each LatLng point (altitude) represents point intensity. Unless max option is specified, intensity should range between 0.0 and 1.0."

Appreciate your thoughts....

**Comment by nakiabrewer** [comment]
I had a look at this today and it appears that as soon as any point (name,lat,lon) is plotted onto a visible layer it is automatically added to the heat map. As I need my visible layer to continually show the updated  location of my vehicle (as I drive around) this then means I get no control over what points contribute to the heat map. I think having the ability to set a boolean flag (as per suggestion above) in msg.payload for adding that point to the heatmap (or not) with the intensity parameter as well will allow a much greater amount of flexibility with the heatmap functionality.

I've had a look through your source and think `new L.LatLng` (lines 698-700 of index.html) is responsible for adding the points to the layer but cant for the life of me figure out how that is then adding that point to the heatmap. Thought it might be the  `if (heatAll || map.hasLayer(layers[lay])) { heat.addLatLng(ll); }` on line 815 but commenting that line out again any points plotted to a visible layer are contributing to the heatmap? 

Again, appreciate your thoughts

**Comment by dceejay** [comment]
Not sure why you want to do all this via the heatmap layer... why not just add multiple points to the map in the colour of your choice ? it's is the name property that is used to be unique - so just set the name to be (say) the timestamp and plot away...

currently no, the only control you get is either ALL point (visible or not) or visible only to contribute to heatmap.

I'm not considering adding a third parameter to the point as I'd rather keep that for real altitude if needed.

**Comment by nakiabrewer** [comment]
My thoughts around wanting to use the heat map layer are because when it draws the points it will  take care of the joining and intersections of the multiple points. I.e they won't just appear as individual dots on the map (I am plotting once a second so it's common for the points to touch each other and heat map does a good job of joining them).

Understand your preference to leave as is.

If you would be kind enough to let me know how leaflet-heat is currently getting its points to plot (noting that in my testing commenting out heat.addLatLng the visible layer still adds points to heatmap) I think I can figure out how to modify my local copy to suit my needs.

Appreciate your thoughts

Best Regards,

Nakia Brewer
WesTrac Technology and Solutions Manager | Tomago NSW | 0249645051

On 6 Mar 2017, at 2:45 am, Dave Conway-Jones <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure why you want to do all this via the heatmap layer... why not just add multiple points to the map in the colour of your choice ? it's is the name property that is used to be unique - so just set the name to be (say) the timestamp and plot away...

currently no, the only control you get is either ALL point (visible or not) or visible only to contribute to heatmap.

I'm not considering adding a third parameter to the point as I'd rather keep that for real altitude if needed.

**Comment by dceejay** [comment]
HI,

yes it's the heat.addLatLng(ll); that adds it to the heat layer. Thta line is checking if the layer is one of the active ones or all can contribute...  
Interested to see what you come up with.

**Comment by nakiabrewer** [comment]
Intersting, as I thought.

I did try commenting out line 893 in index.html `if (heatAll || map.hasLayer(layers[lay])) { heat.addLatLng(ll); }` but found points were still contributing to the heatmap.
Any idea why that might be the case? browser cache thing? With that line commented out nothing should ever contribute to the heatmap right?

I was simply going to add something like below to have a settable flag for adding to heatmap or not:
`
if (data.hasOwnProperty("add-to-heatmap")){
    if (heatAll || map.hasLayer(layers[lay])) { 
        heat.addLatLng(ll); 
    } 
} `

I would also add a new function to contruct the (ll) object with an intensity value.

Again, appreciate your thoughts.

**Comment by dceejay** [comment]
Ah yes - you need to edit the cache manifest file - any change will do.

**Comment by nakiabrewer** [comment]
Okay, After a lot of mucking around I figured out taking out the index.html file from the cache manifest seemed to work. Are you saying that in place of that I could just re save the manifest file and that will also work?

**Comment by dceejay** [comment]
yes - it just needs to change... but commenting out whichever file you are editing would have the same effect... if you are doing a lot of changes.

**Comment by nakiabrewer** [comment]
Hi,

So I have been able to get the settable flag working for controlling what points contribute to the heatmap layer. I've done this in a non breaking way so that the current behavior remains the same and you have to explicitly set `addtoheatmap:"false"` to STOP a plotted position contributing to the heatmap. if `msg.payload.addtoheatmap` doesn't exist it still contributes to the heatmap just as it does today (no change).

In relation to the intensity value I have almost completed the required changes for `msg.payload.intensity`. If this property is found it will create another Leaftlet LatLng object (lli) and this will be used for `heat.addLatLng()` in place of ll. lli is ONLY used in `heat.addLatLng()`!. If `msg.payload.intensity` is not found it will use ll for `heat.addLatLng()` as it does now.

This way it leaves the altitude property free as you requested and ll is still the primary LatLng object.

One thing to note on this is there seems to be a bug in leaflet-heat in relation to intensity not working correctly in the currently version. There is pull request in with the required changes to fix it but its not been actioned from what I can tell....

[https://github.com/Leaflet/Leaflet.heat/issues/74](url)

**Comment by nakiabrewer** [comment]
Hi,

So I finished off the changes as per my last comment.

To summarize.

1. added `msg.payload.addtoheatmap`. This defaults to true so you need to explicitly set it to false if you dont want that point to contribute to the heatmap. Done to make this change non breaking for other users.
2. added `msg.payload.int` or `msg.payload.intensity` (read notes below for when to use which one). This sets the intensity of the point you contribute to the heatmap. If you leave the heatmap max parameter at the default of 1 it will work with values of 0.1 - 1. if this parameter doesn't exist the current behavior as it stands today is applied.

Notes
- there is a bug in leaflet-heat at the moment that if you change max parameter the intensity value doesn't work correctly (screws up when you zoom in and out). suggest leaving at default of 1 and scaling int/intensity between 0.1 - 1.
- Looking through your code you have a few different formats that a position can be added with. can be lat & lon OR latitude & longtitude etc. So inline with that if the position input is lat & lon the intensity parameter is set by `msg.payload.int`. If the position input is latitude & longitude the intensity parameter is set by `msg.payload.intensity`.

I will submit a pull request now and if you see fit feel free to merge.
