### ISSUE TITLE
layercontrol.removeFrom is not a function

### ISSUE THREAD

**Issue by fencer** [dceejay/RedMap#100]
`Uncaught TypeError: layercontrol.removeFrom is not a function`
worldmap.js line 1504 

Happens on version 2.0.12  when setting "Layer Menu" to "Hide"
![image](https://user-images.githubusercontent.com/620966/59212848-ba267480-8bb3-11e9-939a-bfa3c27550ba.png)

**Comment by dceejay** [comment]
Fixed by a98ff9d087f1b1fd68561f4088b1acbcad93ae1a
