### ISSUE TITLE
Worldmap not working on Internet Explorer!!

### ISSUE THREAD

**Issue by kaushalkumarjoshi** [dceejay/RedMap#101]
Dear @dceejay , The worldmap is not working on Internet Explorer.
Can you suggest any solution for the same??

Best Regards,

**Comment by dceejay** [comment]
Use Edge ? or Chrome ? or Firefox ?

**Comment by kaushalkumarjoshi** [comment]
Dear @dceejay,
Please find the screenshots from Edge as Well as IE11
![image](https://user-images.githubusercontent.com/11587185/59604110-cfa61c00-9128-11e9-871f-2d8ac521c651.png)
![image](https://user-images.githubusercontent.com/11587185/59604156-f9f7d980-9128-11e9-8e73-75d484567b4f.png)
![image](https://user-images.githubusercontent.com/11587185/59604201-13008a80-9129-11e9-9518-a4a0fd70928f.png)

Best Regards

**Comment by kaushalkumarjoshi** [comment]
It works great on Chrome.
I am using an Web Browser Activex which is based on IE.
If this solution works on IE, life will be a lot easier!!

Thanks for your support.

PS: Node-Red v0.20 is great!! Thank you guys for making it happen.

Best Regards

**Comment by dceejay** [comment]
Can you double check you are on latest ? (yes I bumped it to 2.0.15 :-)

**Comment by kaushalkumarjoshi** [comment]
Dear @dceejay,

![image](https://user-images.githubusercontent.com/11587185/59627724-8ec7fa80-915c-11e9-8d6e-ae29319e9a29.png)

Thank you very much!!

Works like charm both on edge as well as IE.

Thank you for your valuable support.

Best Regards

PS -  I really appreciate your suggestion. We are using Activex in our current solution and only IE has it's activex. I am not aware of any other browser activex. I hope that by december we will have some solution for the same. Maybe a javascript extension or something. I hope for the best. Thank you once again.

Can you let me know how to make a offline backup of this version that I can locally install on node-red. Just in case if I lose this in newer version, I can still have this version to use.

Thanks

**Comment by dceejay** [comment]
You can always install a specific version eg

    cd ~/.node-red
    npm i node-red-contrib-web-worldmap@2.0.16

But yes - I'll try not to break it for a while :-)
