### ISSUE TITLE
Enhancement: Fullscreen using msg property and fullscreen lock

### ISSUE THREAD

**Issue by kaushalkumarjoshi** [dceejay/RedMap#102]
Dear @dceejay,

Can you provide an option to set the map to fullscreen mode using msg property?
Also, it will be great if there can be an option to lock the map in full screen mode (so that the full screen button has no effect to get the window back to normal).

Best Regards

**Comment by dceejay** [comment]
not the worst idea :-)  Will look at it when I get some time.

**Comment by dceejay** [comment]
Actually the underlying library and the basic browser code will not allow it, as it seen as annoying by most and potential for malicious code by others - eg see
https://stackoverflow.com/questions/32642865/failed-to-execute-requestfullscreen-on-element-api-can-only-be-initiated-by?rq=1

So you will have to configure your browser to run in kiosk mode instead.
