### ISSUE TITLE
Context menu set by map command is applied to new markers

### ISSUE THREAD

**Issue by oliv3** [dceejay/RedMap#103]
Hi, I have a map with a custom context menu set via a map command:

```javascript
if (msg.payload.action == "connected") {
    msg.payload = {
        command: {
            contextmenu: (some custom menu)
```
This works as expected. But when I inject a new marker on this map, with `contextmenu = ""` set in the marker's payload, and right-click on this marker, the context menu previously defined gets used.

**Comment by dceejay** [comment]
Yeah - currently when the contextmenu is removed the underlying map one propagates through.

**Comment by oliv3** [comment]
Did some quick tests, looks like the problem is solved ! Thanks @dceejay
