### ISSUE TITLE
photoUrl is broken when using custom popup

### ISSUE THREAD

**Issue by oliv3** [dceejay/RedMap#104]
Hi, the "`photoUrl`" feature seems to work only when using default popups.

https://github.com/dceejay/RedMap/blob/master/worldmap/worldmap.js#L1368

When using custom popups, wouldn't it be nice to have a `$photoUrl`, as there is e.g. `$name` for replacements in the contextmenu ?

**Comment by dceejay** [comment]
If it's being passed a fully custom popup you can add whatever images/links you want, and set the size appropriately, whereas $photourl is/was a leftover from when that capability didn't exist and is/was a way to just add an image to the popup. If anything it should be deprecated I think.

**Comment by oliv3** [comment]
I see, thanks !
