### ISSUE TITLE
No way to differentiate between layer creation and layer toggling.

### ISSUE THREAD

**Issue by deyanimay** [dceejay/RedMap#108]
I'm trying to set up a map in such a way that all the layers I want are initialized, but the code that generates the points on the map is only run when the layer is toggled on. The only way I could find to create an empty layer is to create a geojson as "" with the layer name I want and then use the hidelayer command.  Unfortunately this triggers an "addlayer" action which then triggers my code to create the points. Is it possible to have different actions for a layer being created and just being turned on, or better yet add a command for adding blank layers with a toggle for its default state (on or off) that doesnt count as an "addlayer" action?

**Comment by dceejay** [comment]
err so you want to add a blank layer that doesn't trigger an addLayer ?  Either it's a layer that is being added or it isn't. If you know you just added it can't you filter on your side and not create the points ?

**Comment by deyanimay** [comment]
The problem is there's no way to differentiate between creating a layer and just toggling on an already created layer. How would you filter it since they both trigger the same action?

**Comment by dceejay** [comment]
could you try for me... in latest worldmap/worldmap.js file line 1719 to be

         if (cmd.map.hasOwnProperty("visible") && (cmd.map.visible != false)) {
            map.addLayer(overlays[cmd.map.overlay]);
        }


IE add the if around it - then add a parameter to your geojson cmd to add visible:false - this should add the layer but not add it to the map... hopefully.
