### ISSUE TITLE
Map not loading in FF (68.0.2 64-bit) on Win 7 

### ISSUE THREAD

**Issue by spydmobile** [dceejay/RedMap#111]
very similar to #98,  I get 
ReferenceError: L is not defined worldmap.js:126:1
I see the icon and Node Red - Map all the things but no map.

I am loading the map inside the dashboard with a variation on the example included with the map. my version in the template says:

```
<iframe src="../virsPolyMap"  scrolling="no" frameborder="0"
    style="position: relative; height: 400px; width: 100%;" >    
</iframe>
```

I think this is actually a symptom, not the root cause, I think the root cause is:
Source map error: request failed with status 404
Resource URL: http://localhost:1880/ui/js/app.min.js
which loads if you click it in the error link but 404s if you dont.

Does not happen on chrome.

IE 11 does a similar thing, no map just black screen with logo and slogan
but gives me:
SCRIPT1014: Invalid character
File: worldmap.js, Line: 177, Column: 16

this is using:
node-red 0.20.5
dashboard 2.14.0 and redmap 2.0.12
IE 11, FF 68.0.2 64-bit, Windows 7 pro

**Comment by dceejay** [comment]
Which version of worldmap ?
line 126 doesn't have L.

**Comment by spydmobile** [comment]
you bet, Ill be back in the office on monday and try it. Have no idea why I did not try upgrading first, sorry.
