### ISSUE TITLE
Icon not showing

### ISSUE THREAD

**Issue by fencer** [dceejay/RedMap#115]
When bearing is supplied, the icon will not show & bearing will only show once.
![image](https://user-images.githubusercontent.com/620966/64945689-65a92a00-d871-11e9-851e-56dae45066cb.png)

I've attached a sample I have extracted from the websocket [sample.txt](https://github.com/dceejay/RedMap/files/3615403/sample.txt)

This was working in previous versions.

**Comment by dceejay** [comment]
Sorry - how was that sample created ? Doesn't seem to be a format I recognise.

**Comment by fencer** [comment]
Sorry forgot to mention the sample file contains 4 'streams' I extracted from the web socket output (in chrome developers tool on `/worldmap`). 
Within node-red I am passing the 'worldmap node' and 'tracks node' a payload in this format:

`msg.payload = {
		name: 'CE',
		lat: 35.9041603,
		lon: 14.512736,
		speed: 8.38875,
		bearing: 245,
		icon: "ship",
		iconColor: "red"
	}`

**Comment by dceejay** [comment]
got it - thanks. 
Pushed version 2.1.1 with fix (I think)
please let me know. Thanks

**Comment by fencer** [comment]
I took the source files from git and replaced the files in the node_modules but the issue still somewhat there. The only thing different this time is that the bearing line is never displayed (and the icon still not visible)

**Comment by dceejay** [comment]
I can see this wi th the original sample you supplied (once edited)

![image](https://user-images.githubusercontent.com/5375409/65157754-245b7a80-da29-11e9-9170-55c8863cab23.png)

can you try v2.1.1 (now that it is on npm) - make sure you flush local cache etc.

**Comment by fencer** [comment]
I can confirm that it now works!
