### ISSUE TITLE
with latest version (2.1.2) link on info tab takes you to first tab in flows

### ISSUE THREAD

**Issue by juggledad** [dceejay/RedMap#117]
in v2.1.2 the `The map can be found here.` link in the description no longer takes you to` http:..your-ip:1880/worldmap` instead it takes you to the first tab in the editor.

The same link in the new ui_worldmap does take you to `http:..your-ip:1880/worldmap`

**Comment by dceejay** [comment]
errrr - they both use exactly the same code... 
what is your settings.js  httpNodeRoot  set to ?

**Comment by juggledad** [comment]
the default
    //httpNodeRoot: '/red-nodes',

**Comment by juggledad** [comment]
Interestingly if I have tab 1 with the worldmap node and tab 2 with the ui_worldmap and hit the link on tab2 (the ui version) it tales me to the worldmap running in tab 1. I know this because the tab2 ui map is using the color changes function talked about in the thread

**Comment by juggledad** [comment]
Running the same flow on a Mac vrs a Pi - both on the same versions of NR, dashboard and world map - the ui_worldmap works fine at the ui page on the Mac, but does not show on the ui page on the Pi. The map on the pi does show at /worldmap and any buttons on the ui page show up and effect the map at /worldmap.

**Comment by juggledad** [comment]
on the mac,
26 Sep 09:49:17 - [info] Node-RED version: v1.0.0-beta.4
26 Sep 09:49:17 - [info] Node.js version: v10.15.3
26 Sep 09:49:17 - [info] Darwin 17.7.0 x64 LE
26 Sep 09:49:17 - [info] Loading palette nodes
26 Sep 09:49:19 - [info] Worldmap version 2.1.2
26 Sep 09:49:19 - [info] Dashboard version 2.16.3 started at /ui 

on the pi, 
26 Sep 07:43:26 - [info] Node-RED version: v1.0.0-beta.4
26 Sep 07:43:26 - [info] Node.js version: v10.16.3
26 Sep 07:43:26 - [info] Linux 4.19.66-v7+ arm LE
26 Sep 07:43:27 - [info] Loading palette nodes
26 Sep 07:43:34 - [info] Worldmap version 2.1.2
26 Sep 07:43:34 - [info] Dashboard version 2.16.3 started at /ui

**Comment by dceejay** [comment]
closed by 8f51fa21ae5b8473e7d10a7faeba5a943c2d97ee
