### ISSUE TITLE
making separate layer form overlapping layers 

### ISSUE THREAD

**Issue by aqieez** [dceejay/RedMap#119]
I have two layers, layer 1 have a polygon drawing shape and layer 2 has some points. Both these two layers are overlapping at some points. now I want to create a different layer which only contains overlapping points. how can I achieve that? I really can't see any filtering mechanism. Please help

**Comment by dceejay** [comment]
You would need to do the maths at the backend in your application.  The map is just a rendering engine to help visualise the points. 

For general discussions it may be better to ask on either the Node-RED discourse forum or maybe a specialist mapping forum.

**Comment by aqieez** [comment]
@dceejay  thanks for your reply. Issues has been resolved. I did some math at backend then from results i made a new layer.
