### ISSUE TITLE
Showing legend in the world map

### ISSUE THREAD

**Issue by aqieez** [dceejay/RedMap#120]
I am working with the world map and plotting some points on it and giving them different colors. But I also want a legend to show on the world map. But I can't figure it out how can I do it? Is it possible to show legend ? or not? Thanks

**Comment by dceejay** [comment]
Not easily.... 
so I have added a legend command in version 2.1.6 that will accept html

#### To add and remove a legend

     msg.payload.command = { "legend": "<b>Title</b></br><i style=\"background: #477AC2\"></i> Water<br><i style=\"background: #448D40\"></i> Forest<br>" };

**Comment by aqieez** [comment]
@dceejay I didn't see that coming, but this new update has solved my problem. Thanks a lot

**Comment by dceejay** [comment]
No Worries - it wasn't coming until you suggested it :-)
