### ISSUE TITLE
Enhancement: Have all icons oriented on a supplied bearing

### ISSUE THREAD

**Issue by Aterfax** [dceejay/RedMap#125]
I have some custom icons I'd like to use supplied as images (linked in) but they will stay oriented upright irrespective of their object's given bearing.

Is there a way for me to toggle the orientation of an image icon - or FA-icon to follow the bearing? (By assuming directly up the icon as displayed in browser is 0 degrees)

I can't see in the documentation whether I can get this working like the built in icons or whether this needs some new code?

Example image below, built in icons orient on their bearing but not other icon types:

![image](https://user-images.githubusercontent.com/8648058/78789632-502e5580-79a5-11ea-8b6f-b276c4fce0f9.png)

**Comment by Aterfax** [comment]
Looks like an edit can be made here?

https://github.com/dceejay/RedMap/blob/7908311561ee115bd0e47c63259b1d37f3a9a58b/worldmap/worldmap.js#L1356

**Comment by dceejay** [comment]
happy to look at a  pull request if you get one working.
Obviously it's not really applicable to many icon types like normal markers etc (or SIDC codes) - but in principle yes.

**Comment by Aterfax** [comment]
Not greatly familiar with javascript - I might have a go - but yeah it's why I figured it should be toggleable if added.

**Comment by dceejay** [comment]
well I'm happy for it to be "on" all the time for those of type http etc as that sort of makes sense.
just not fa icons etc.

**Comment by Aterfax** [comment]
Oh yeah - the FA-icons by and large wouldn't make sense.

**Comment by dceejay** [comment]
I have found a helper to rotate icons - just need to test.

**Comment by Aterfax** [comment]
Tested and working! Many thanks for the help.

**Comment by dceejay** [comment]
feel free to post a pic of the result :-)

**Comment by Aterfax** [comment]
Here's an example - still plenty of work for me to do to get some specific icons for all types of platform :)

![image](https://user-images.githubusercontent.com/8648058/78934005-155e1780-7aa2-11ea-9750-910819427fbf.png)
