### ISSUE TITLE
On click action response does not contain all object attributes / properties.

### ISSUE THREAD

**Issue by Aterfax** [dceejay/RedMap#126]
Would it be possible for the on click action response to contain the full attributes for the clicked object at present I only seem to get the following:

![image](https://user-images.githubusercontent.com/8648058/78846176-d0cf6f00-7a02-11ea-8303-30f000062353.png)

![image](https://user-images.githubusercontent.com/8648058/78846193-e2187b80-7a02-11ea-985e-0e0aae9085d3.png)

Cheers!

**Comment by dceejay** [comment]
the name is unique - so you can use that as a lookup into wherever you are sending it from.

**Comment by Aterfax** [comment]
That's how I'm handling it at the moment :)
