### ISSUE TITLE
Enhancement: show ruler button on iframed worldmap

### ISSUE THREAD

**Issue by Aterfax** [dceejay/RedMap#127]
When looking at the Worldmap the ruler button appears under the zoom buttons:

![image](https://user-images.githubusercontent.com/8648058/78998008-a20ae300-7b3f-11ea-90bc-6c4c49cd2fba.png)

When inside an iframe within the dashboard UI, this button vanishes:

![image](https://user-images.githubusercontent.com/8648058/78997957-84d61480-7b3f-11ea-8183-bda11e189a82.png)

I can't see any documentation on how to get this to appear?

I'm guessing this disappearing is part of getting rid of the top bar when in the iframe? Might be an idea to have an option to toggle whether it should be there or not?

Edit: Happy Easter!

**Comment by dceejay** [comment]
it might be an idea. The thinking was when in dashboard mode there is not much space to be doing things like measurements etc - so why clutter the screen with extra controls.

**Comment by Aterfax** [comment]
Is there a way I can feed a command to the map to make the button appear?

**Comment by dceejay** [comment]
not yet

**Comment by dceejay** [comment]
Ok - if 
![image](https://user-images.githubusercontent.com/5375409/79226717-bc520300-7e56-11ea-82bc-19fcbbfc113f.png)
set visible then the ruler button will also appear.
pushed as version 2.3.6  (also include a better fix for the tracks of array of points)
