### ISSUE TITLE
Icon is now shown on map

### ISSUE THREAD

**Issue by drmabuzo** [dceejay/RedMap#128]
Dear,

I just update new version of node @2.3.6 and i cannot see any icons anymore on map?
I tried with https://fontawesome.com/v4.7.0/icons/ and with https://github.com/dceejay/RedMap/blob/master/emojilist.md icons and have the same issue.

I'm using worldmap node in node-red v1.0.3
Here is my json:

{"name":"Test",
"lat":44.8046,
"lon":20.4286,
"icon":"fa-arrows-alt",
"iconColor":'#00CF00',
"color":'#FFFF00',
"fillColor":'#FFFF00',
"radius":3000}

[https://imgur.com/IODgSwe](url)

Can you check and see where is the problem?

Thanks in advanced,
Regards,
Milos

**Comment by dceejay** [comment]
The thinking was that if you are drawing a circle it shouldn't also have an icon. Either the object is a marker - or a shape...  but.. what is your use case ? It may make sense, and we can look at it.

**Comment by dceejay** [comment]
gone for the halfway approach - if icon is specified it it drawn even if it is a circle... - if not specified it doesn't get drawn.
