### ISSUE TITLE
leaflet.markercluster.js.map missing

### ISSUE THREAD

**Issue by ewrayjohnson** [dceejay/RedMap#129]
Upgraded from: "node-red-contrib-web-worldmap": "^2.2.1",  "node-red": "^1.0.3",
Upgraded to: "node-red-contrib-web-worldmap": "^2.3.6", "node-red": "^1.0.5"
Getting the following error not seen before upgrading:
Unhandled error for request GET /redapi/worldmap/leaflet/leaflet.markercluster.js.map: Error: Cannot GET /redapi/worldmap/leaflet/leaflet.markercluster.js.map

Note: usage embedded in iframe

**Comment by dceejay** [comment]
Are you sure you have flushed the local browser cache properly before reloading the page ?

**Comment by ewrayjohnson** [comment]
Yes I did.  The file is just not part of the distribution package.

**Comment by dceejay** [comment]
It should even be asking for it. If you have console tools open it may try to load it as it is a debugging aid for one of the libraries - but we don't ship it and it isn't required.
