### ISSUE TITLE
.ui-worldmap

### ISSUE THREAD

**Issue by ewrayjohnson** [dceejay/RedMap#130]
Upgraded from: "node-red-contrib-web-worldmap": "^2.2.1",  "node-red": "^1.0.3",  "node-red-dashboard": "^2.19.3"
Upgraded to: "node-red-contrib-web-worldmap": "^2.3.6", "node-red": "^1.0.5","node-red-dashboard": "^2.20.0"
Getting the following error not seen before upgrading:
Unhandled error for request GET /.ui-worldmap: Error: Cannot GET /.ui-worldmap

Note: usage embedded in iframe

**Comment by dceejay** [comment]
Are you sure you have flushed the local browser cache properly before reloading the page ?

**Comment by ewrayjohnson** [comment]
Yes I have.  The node just does not get registered properly even though I have other dashboard nodes.   In debugging I determined that an exception does NOT get thrown when the registration call is made.

**Comment by ewrayjohnson** [comment]
![ui_worldmap_missing](https://user-images.githubusercontent.com/5104066/79695039-5ee8f800-8242-11ea-8697-113d19539a28.png)

**Comment by ewrayjohnson** [comment]
![ui_worldmap_missing2](https://user-images.githubusercontent.com/5104066/79695106-c69f4300-8242-11ea-9865-3b92890da8ab.png)

**Comment by dceejay** [comment]
What do you mean by usage in iframe ? the worldmap is already in an iframe to put it in the dashboard. (as ui_worldmap)... Are you then putting the whole dashboard in another iframe ?

**Comment by ewrayjohnson** [comment]
I am using the worldmap in a node-red-contrib-uibuilder web page not a Dashboard.  I can't use it on a dashboard anyway because the ui_worldmap is not successfully registered as a node.

**Comment by dceejay** [comment]
you can embed the normal worldmap out node in an iframe. The url is just the same. Was the way we used to do it all the time before we had the dashboard specific one.

**Comment by ewrayjohnson** [comment]
That is what I am doing.  It still works.  The only problem is that the automatic height (e.g. 100%) adjustment on window resize does not work.

**Comment by dceejay** [comment]
do you have a small flow you can share that demonstrates this ?

**Comment by ewrayjohnson** [comment]
Yes.  I will post in a few days.

**Comment by Ferrancf5** [comment]
Yes, i have same problem. ui_worldmap doesn't appear in dashboard nodes. I can see map if I go to url/worlmap.

In another computer I have installed version 2.3.4 and appear it, but in version 2.3.8 don't.
