### ISSUE TITLE
Point resides inside a polygon?

### ISSUE THREAD

**Issue by victorUTF** [dceejay/RedMap#132]
Hi, I'm trying to check whether a point is inside a GeoJson polygon or not.

I found the function wich solve my problems, which is **d3.geoContains()** here:
https://github.com/d3/d3-geo#geoContains

So i modified the example **Add Geoson Building** 

```
var geo = { "type": "FeatureCollection",
"features": [
  {
    "type": "Feature",
    "properties": {
      "color": "rgb(0,0,255)",
      "roofColor": "rgb(128,128,255)",
      "height": 20,
      "minHeight": 0
    },
    "geometry": {
      "type": "Polygon",
      "coordinates": [
          // long, lat
        [
        [-50.408083, -24.517496],
        [-50.407976, -24.516664],
        [-50.406089,-24.516202],
        [-50.402566,-24.517136,],
        [-50.405989,-24.520584],
        [-50.408083,-24.517496,]
        ]
      ]
    }
  }
]
}
var pos = [-50.413438, -24.527021];
var inside =  d3.geoContains(geo, pos);
var m = {overlay:"Golf Clubhouse", geojson:geo, fit:true};

msg.payload = {command:{map:m, lat:-24.527021, lon:-50.413438}};
return msg;  
```

Which returns an error massage:
![image](https://user-images.githubusercontent.com/35344574/81891887-0cb89f80-9580-11ea-9ff8-f25798a7c4d4.png)

`[{"id":"c97b18e3.b89c28","type":"worldmap","z":"6cc3da71.4cb554","name":"","lat":"","lon":"","zoom":"","layer":"","cluster":"","maxage":"","usermenu":"show","layers":"show","panit":"true","hiderightclick":"false","coords":"none","path":"/worldmap1","x":770,"y":420,"wires":[]},{"id":"b0cc2326.043a4","type":"function","z":"6cc3da71.4cb554","name":"","func":"var geo = { \"type\": \"FeatureCollection\",\n\"features\": [\n  {\n    \"type\": \"Feature\",\n    \"properties\": {\n      \"color\": \"rgb(0,0,255)\",\n      \"roofColor\": \"rgb(128,128,255)\",\n      \"height\": 20,\n      \"minHeight\": 0\n    },\n    \"geometry\": {\n      \"type\": \"Polygon\",\n      \"coordinates\": [\n          // long, lat\n        [\n        [-50.408083, -24.517496],\n        [-50.407976, -24.516664],\n        [-50.406089,-24.516202],\n        [-50.402566,-24.517136,],\n        [-50.405989,-24.520584],\n        [-50.408083,-24.517496,]\n        ]\n      ]\n    }\n  }\n]\n}\nvar pos = [-50.413438, -24.527021];\nvar inside =  d3.geoContains(geo, pos);\nvar m = {overlay:\"Golf Clubhouse\", geojson:geo, fit:true};\n\nmsg.payload = {command:{map:m, lat:-24.527021, lon:-50.413438}};\nreturn msg;  \n\n\n","outputs":1,"noerr":0,"x":520,"y":420,"wires":[["c97b18e3.b89c28"]]},{"id":"a60a6180.1edfa","type":"inject","z":"6cc3da71.4cb554","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":320,"y":420,"wires":[["b0cc2326.043a4"]]}]`

Thanks.

**Comment by victorUTF** [comment]
Any news?

**Comment by dceejay** [comment]
why would you expect that to work ? the worldmap page does not use d3.

**Comment by victorUTF** [comment]
Thanks for the suggestion @dceejay ,  I'll try .
