### ISSUE TITLE
Add "drawing" layer

### ISSUE THREAD

**Issue by victorUTF** [dceejay/RedMap#133]
How add a layer?

With "drawing" select in layer menu, this action happens.

![image](https://user-images.githubusercontent.com/35344574/82859955-9bb5a800-9eee-11ea-8e04-83e720d2ff51.png)
 
On the map, you can see this panel:
![image](https://user-images.githubusercontent.com/35344574/82860408-d835d380-9eef-11ea-8217-e0f9a0848b1c.png)

How can I configure the map using a function, something like the image below:
![image](https://user-images.githubusercontent.com/35344574/82860047-dcadbc80-9eee-11ea-99b7-e813de5edf74.png)

Thanks

**Comment by victorUTF** [comment]
can you help me? @dceejay 

sorry for bothering you :( , i didn't found the solution yet

**Comment by dceejay** [comment]
Hi, I'm sorry - I'm not quite sure what you are asking for ? yes that is the drawing layer and yes you could dd an icon to it like that.
The README shows how to add or switch layers. using commands if that is what you want ?
or... ?

**Comment by victorUTF** [comment]
I found a way to resolve this. Thanks for your attention @dceejay
