### ISSUE TITLE
Enhancement: use tracks to autocalculate a speed

### ISSUE THREAD

**Issue by Aterfax** [dceejay/RedMap#134]
As said in the title, it might be useful for the tracks node to automatically calculate a speed, not sure what unit or variable would be appropriate?

Possibly trackspeed and ms^1 ?

Would be nicer than the hacky method I think I am using now!

**Comment by dceejay** [comment]
and do what with it ? polylines can't have a speed ?

**Comment by Aterfax** [comment]
Oh yeah I mean use the tracks data to compute the speed for the object contributing the location data which is making the track.

**Comment by dceejay** [comment]
All the tracks does is hold onto the series of last positions to create a line - and it just emits a line. You still need to pass the object itself to the map and It doesn't update the object. 
The other problem is that just given a position the only time difference we have is time of arrival at us - which may or may not be realistic given reading/network delays etc. 

But it's fairly simple to create that in a function like this (or something like it :-)

```
var things = context.things || {};
var last = context.last || {};
var _toRad = function(deg) { return deg * Math.PI / 180; }
var _toDeg = function(rad) { return rad * 180 / Math.PI; };

var bearing = function (lat1,lng1,lat2,lng2) {
    var dLon = _toRad(lng2-lng1);
    var y = Math.sin(dLon) * Math.cos(_toRad(lat2));
    var x = Math.cos(_toRad(lat1))*Math.sin(_toRad(lat2)) - Math.sin(_toRad(lat1))*Math.cos(_toRad(lat2))*Math.cos(dLon);
    var brng = _toDeg(Math.atan2(y, x));
    return Math.round(((brng + 360) % 360)*100)/100;
};

var distance = function(lat1, lon1, lat2, lon2) {
	if ((lat1 == lat2) && (lon1 == lon2)) { return 0; }
	else {
		var radlat1 = Math.PI * lat1/180;
		var radlat2 = Math.PI * lat2/180;
		var theta = lon1-lon2;
		var radtheta = Math.PI * theta/180;
		var dist = Math.sin(radlat1) * Math.sin(radlat2) + Math.cos(radlat1) * Math.cos(radlat2) * Math.cos(radtheta);
		if (dist > 1) { dist = 1; }
		dist = Math.acos(dist);
		dist = dist * 180/Math.PI * 60 * 1.1515 * 1609.344;
		dist = Math.round(dist*100)/100;
		return dist;
	}
}

if (msg.payload.lat === last.lat && msg.payload.lon === last.lon) { return; }

var foo = things[msg.topic];
if (foo) {
    msg.payload.speed = distance(foo.lat,foo.lon,msg.payload.lat,msg.payload.lon)/((Date.now() - msg.payload.ts)/1000);
    msg.payload.hdg = bearing(foo.lat,foo.lon,msg.payload.lat,msg.payload.lon);
}
msg.payload.ts = Date.now();

things[msg.topic] = msg.payload;
context.last = msg.payload;
context.things = things;
return msg;
```

**Comment by Aterfax** [comment]
The implementation I have on my end uses a LastSeen time value to do the calculation, but I could see an implementation for the tracks node simply using a timestamp when fed to the tracks node or a text input to select a message value (e.g. msg.lastseen) for the timing info.

Didn't realise the track was simply a drawn line not associated with the object generating it.

Might be worth linking a track to the object? (This would be nice in terms of being able to toggle tracks on and off per object within a layer.)

**Comment by dceejay** [comment]
The tracks can already be associated with different layers - and depending on which you choose varies how you toggle hem on or off. 
![image](https://user-images.githubusercontent.com/5375409/83902053-a294b400-a753-11ea-863f-33e39e01ba77.png)

**Comment by Aterfax** [comment]
Yeah I have been using this to separate tracks into aircraft, ground etc... but was looking for a way to declutter specific tracks on an individual object basis, decluttering tracks on click on an aircraft object landing around / on an aircraft carrier.

When aircraft are landed on the deck, they still generate a track as the carrier is moving which ends up cluttering the area directly behind the carrier which will obscure tracks and aircraft (objects) which are landing onto that carrier.

In terms of sorting this - I wanted to automatically de-track any aircraft object in proximity to the aircraft carrier at the same altitude as the carrier.

From what I can tell, at the moment I would need to either delete the object (which isn't really feasible from a live track) or add every aircraft to its own layer (which also isn't very feasible when I have 50 - 100 aircraft at any given time.)

**Comment by dceejay** [comment]
you could always have a switch before sending to track node to filter out any aircraft tracks below say 25m ? so once on deck they didn't create a track ?

**Comment by Aterfax** [comment]
I think I will have to approach it by grabbing the location of aircraft carriers and dropping tracks for aircraft within x nautical miles since I would like to retain tracks for taxiing aircraft at airfields.
