### ISSUE TITLE
Bug: Speed vectors are drawn permanently on map while object layer is hidden.  

### ISSUE THREAD

**Issue by Aterfax** [dceejay/RedMap#135]
If you supply a speed value a vector is added to the map in front of the object, however when the layer for these objects is hidden these velocity vector lines are drawn permanently (but currently hidden).

When you turn the layer back on, every speed vector drawn while the layer is hidden is now visible and permanently on the map (leading to a lot of clutter.)

I hope this is explained clearly enough to make sense!  See below:

Example 1: Layer turned on - vectors visible

![image](https://user-images.githubusercontent.com/8648058/83762553-8fa8b380-a66f-11ea-8144-2ad8e4a5fad8.png)

Example 2 with layer off:

![image](https://user-images.githubusercontent.com/8648058/83762732-c1ba1580-a66f-11ea-953a-745b2164f728.png)

Example 3 with layer now turned back on:

![image](https://user-images.githubusercontent.com/8648058/83762705-b961da80-a66f-11ea-96a8-745ea8a7f430.png)

**Comment by dceejay** [comment]
@Aterfax - sorry for the delay in fixing this. Hopefully all sorted in v2.8.1.

**Comment by Aterfax** [comment]
No worries, your efforts are much appreciated!
