### ISSUE TITLE
add button, click or event on popup?

### ISSUE THREAD

**Issue by halukmy** [dceejay/RedMap#136]
hello, can we any intereaction on popup text or button?

**Comment by dceejay** [comment]
yes - you can add any html you like into the popup.

**Comment by halukmy** [comment]
![image](https://user-images.githubusercontent.com/2916333/85673297-6c03e680-b6cc-11ea-9160-ce5aa5e3e029.png)

it has an id, so is there possible to get id of unit and send mqtt message with button on popup ?

can you share a code? sadly i couldnt find any example

**Comment by dceejay** [comment]
in the popup html you should be able to add an html button with an onclick action like 
```
onclick='feedback(this.name,"some data you want to send")'
```
the worldmap in node should then report that action which you can feed to mqtt.

**Comment by halukmy** [comment]
@dceejay i want thank you for share, but i still cant find where should i add onclick process,

![image](https://user-images.githubusercontent.com/2916333/85712263-d29afb80-b6f0-11ea-8dc7-1cd128f39338.png)

first of i clear map,
and after that, via mqtt i send payload messages on c# 

  //var payload = "{\"areynode\":\"" + cihazModeli + "\"" +
                        //              "," + "\"lightpower\":\"" + cihazEnerjisi + "\"" +
                        //              "," + "\"lightmodel\":\"" + lambaModeli + "\"" +
                        //              "," + "\"lightdriver\":\"" + cihazSurucusu + "\"" +
                        //              "," + "\"totalnode\":\"" + birimAdedi + "\"" +
                        //              "," + "\"nodeenergy\":\"" + cihazaUygulananEnerji + "\"" +
                        //              "," + "\"totalenergy\":\"" + totalEnergyUsage + "\"}";

                        //sendMQTT("AREYTECH/AREYLIGHT/IVEDIK1/INFO", payload);


and still searching how can i add button and add event onclick

**Comment by dceejay** [comment]
Here is a simple example to import
```
[{"id":"afb2fe0e.7558f","type":"inject","z":"5cce3836.d51838","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":120,"y":80,"wires":[["5857fe5d.4521c"]]},{"id":"d9ab8788.d72268","type":"worldmap","z":"5cce3836.d51838","name":"","lat":"","lon":"","zoom":"","layer":"","cluster":"","maxage":"","usermenu":"show","layers":"show","panit":"false","panlock":"false","zoomlock":"false","hiderightclick":"false","coords":"false","showgrid":"false","path":"/worldmap","x":480,"y":80,"wires":[]},{"id":"5857fe5d.4521c","type":"function","z":"5cce3836.d51838","name":"","func":"msg.payload = {\n    name:\"Dave\",\n    lat:51.05,\n    lon:-1.35,\n    popup:'<button type=\"button\" onclick=\\'feedback(\"Dave\",\"some data you want to send\")\\'>Click Me!</button>'\n}\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":300,"y":80,"wires":[["d9ab8788.d72268"]]},{"id":"73a153e5.47345c","type":"worldmap in","z":"5cce3836.d51838","name":"","path":"/worldmap","events":"all","x":120,"y":140,"wires":[["d42093ff.d836b"]]},{"id":"d42093ff.d836b","type":"debug","z":"5cce3836.d51838","name":"","active":true,"tosidebar":true,"console":true,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":500,"y":140,"wires":[]}]
```
