### ISSUE TITLE
Bigger custom icons?

### ISSUE THREAD

**Issue by realjax** [dceejay/RedMap#137]
Hi, 

Would dit be possible to use bigger images as icons instead of the downscaling to 32x32?  I would like to use this as a map showing where the members of the house are currently located and use their pic's as the icon. But a 32x32 image is kinda hard to see :)

cheers.

**Comment by dceejay** [comment]
now in v2.3.14 - if you set icon to http.... then you can also set iconSize=xx  where xx is a size in pixels (square) - default is 32.
