### ISSUE TITLE
Rounded coordinates

### ISSUE THREAD

**Issue by sro49-iot** [dceejay/RedMap#138]
Hello,

It seems that coordinates latitude and longitude are rounded and fixed to 6 decimal digits. In my case these rounded coordinates make me an placement error of approximatly 150 meters. Is there a way to use full lon and lat values?

For example lon sent to World Map node: -0,0778516 and what I get in my map marker: -0.077852

Thank you

**Comment by dceejay** [comment]
How so ? - 5 dp is about 1m ? 6dp about 10cm ?
Where are you seeing ? (what function are  you using ?)

**Comment by sro49-iot** [comment]
I made new test this morning and seems to be better but don't know why.
I use Google Maps to get coordinates of my marker ([link](https://www.google.fr/maps/place/49400+Saumur/@47.2535859,-0.0774323,47m/data=!3m1!1e3!4m5!3m4!1s0x4807f0cda39bbc09:0x40d37521e0d8900!8m2!3d47.260135!4d-0.080893)) and made a form in Node Red with dashboard to enter latitude, longitude and give a name to my marker. Yesterday I got 100 meters difference between Google Maps and Worlmap. This morning I have 10 meters.

Below my Node Red flow:

`[{"id":"630cac0d.e692f4","type":"worldmap","z":"d8b42fc1.9ef58","name":"","lat":"","lon":"","zoom":"","layer":"OSM grey","cluster":"","maxage":"","hiderightclick":"false","coords":"none","path":"worldmap","x":920,"y":200,"wires":[]},{"id":"b884230a.f7c3c","type":"function","z":"d8b42fc1.9ef58","name":"test","func":"msg.payload.layer = \"lora\";\n//msg.payload.name = \"gateway\";\nmsg.payload.icon = \"wifi\";\nmsg.payload.iconColor = \"blue\";\nmsg.payload.accuracy = 8;\n\nreturn msg;","outputs":1,"noerr":0,"x":690,"y":680,"wires":[["630cac0d.e692f4"]]},{"id":"a1cd1683.7e6ba8","type":"ui_form","z":"d8b42fc1.9ef58","name":"Gateway","label":"Add Gateway","group":"9c1177e6.bae358","order":0,"width":0,"height":0,"options":[{"label":"Latitude","value":"lat","type":"number","required":true,"rows":null},{"label":"Longitude","value":"lon","type":"number","required":true,"rows":null},{"label":"Gateway ID","value":"name","type":"text","required":true,"rows":null}],"formValue":{"lat":"","lon":"","name":""},"payload":"","submit":"submit","cancel":"cancel","topic":"","x":520,"y":680,"wires":[["b884230a.f7c3c"]]},{"id":"9c1177e6.bae358","type":"ui_group","z":"","name":"Default","tab":"a40b0d57.f769a","order":1,"disp":true,"width":"6","collapse":false},{"id":"a40b0d57.f769a","type":"ui_tab","z":"","name":"Home","icon":"dashboard","disabled":false,"hidden":false}]`

I will make new tests today to check accuracy. Thank you for your quick reply.

**Comment by dceejay** [comment]
Hi - I had a quick look at the code - I don't think I round or truncate any of the inputs per se. They do seem to get rounded for display in the popup - not sure why - as I'm just doing a getLatLng call which should just get them as-is (or so I thought). I do round the returns if you drag or add marker manually (which i think is probably fair given accuracy of mouse/pixels/resolution of map etc.
