### ISSUE TITLE
PNG icons

### ISSUE THREAD

**Issue by jibdata** [dceejay/RedMap#139]
Hi,

Worldmap v2.3.14, Node-Red v1.1.0
No longer able to use png-icons. Will not show on map.
I'm using the same icon as before I updated to 2.3.14, and that worked fine on the older version.

**Comment by dceejay** [comment]
please provide an example. thanks

**Comment by jibdata** [comment]
Created a plain and simple example:

[{"id":"18f4465c.f6cb2a","type":"inject","z":"914a9a06.8aa058","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"name\":\"Testing\",\"lat\":51.0641923,\"lon\":-1.3558968,\"icon\":\"https://img.icons8.com/color/48/000000/map-pin.png\"}","payloadType":"json","x":240,"y":620,"wires":[["2224324a.07cb6e"]]},{"id":"2224324a.07cb6e","type":"worldmap","z":"914a9a06.8aa058","name":"","lat":"","lon":"","zoom":"","layer":"","cluster":"","maxage":"","usermenu":"show","layers":"show","panit":"false","panlock":"false","zoomlock":"false","hiderightclick":"false","coords":"none","showgrid":"false","path":"/worldmap","x":450,"y":620,"wires":[]}]

**Comment by dceejay** [comment]
thanks - will investigate

**Comment by dceejay** [comment]
Yup - bad spelling - sorry - fixed pushed to master and npm.
