### ISSUE TITLE
FontAwesome icons version?

### ISSUE THREAD

**Issue by brylie** [dceejay/RedMap#14]
What version of the FontAwesome icons does this package include? I cannot tell from the documentation, as it simply points to the FontAwesome front page.

**Comment by dceejay** [comment]
4.7

**Comment by brylie** [comment]
OK, thanks. We cannot get the icons to work. We have tried the following:

- without any `fa` prefixing
- with `fa-icon-name`
- with `fa fa-icon-name`

In each case, the map renders the default icon. Would you mind giving a documentation example of how to use a FA icon on the map?

**Comment by dceejay** [comment]
A function with this
```
var thing = {
    name:"Jason Isaacs", 
    lat:51, 
    lon:-1.45,
    icon:"fa-male",
    iconColor:"darkred",
    extrainfo:"Hello to Jason Isaacs"
};
msg.payload = thing;
return msg;
```

should give you this
![image](https://cloud.githubusercontent.com/assets/5375409/25818979/571a61dc-3424-11e7-9a77-dd1e08c19822.png)

**Comment by brylie** [comment]
Ah, it places the FA icon on the marker. We were expecting to see the FA icon *instead of* the marker. Thank you for clarification. Would you consider adding that example to the README?

**Comment by dceejay** [comment]
several examples already installed under the menu - import - examples - worldmap.... when you install the node.
There are a few special icons...  plane, ship, car, satellite  .. that do replace the icon shape and also align with the direction bearing (actually satellite doesn't align but the other three do)
