### ISSUE TITLE
iconSize shows up in popup text box

### ISSUE THREAD

**Issue by jibdata** [dceejay/RedMap#140]
When spesifying iconSize, it shows up in the popup text box.
I guess this should behave similar as the other properties?

Kind Regards

**Comment by dceejay** [comment]
doh - yes will fix.

**Comment by jibdata** [comment]
Thumbs up :)
Also, discovered when combining with http image and radius, these properties will appear in the popup:
iconSize (already mentioned), clickable, fillColor
