### ISSUE TITLE
Ruler options for units missing?

### ISSUE THREAD

**Issue by Aterfax** [dceejay/RedMap#142]
I can't find a way to change the units utilized for the ruler from km and degrees - was hoping to use nautical miles, miles, mils etc...

Is there an option I've missed / would be nice as a feature request.

**Comment by dceejay** [comment]
the underlying library only allows setting that during the construction of the control so can't easily be changed dynamically. line 144 of worldmap/worldmap.js if you want to hack it.
see the library readme for usage - https://github.com/gokertanrisever/leaflet-ruler

**Comment by Aterfax** [comment]
Many thanks, I will go have a tinker, could be added to documentation?

**Comment by dceejay** [comment]
Good workaround.
