### ISSUE TITLE
Enhancement: Mini-maps / Split Maps

### ISSUE THREAD

**Issue by Aterfax** [dceejay/RedMap#143]
Any chance we could get support for a minimap style setup?

I'd love to be able to have a smaller bit of my map zoomed in a bit and to be following an object, with a larger map showing an overview of the area. 

I think this would likely need the sync and clonelayer plugins here: https://leafletjs.com/plugins.html#minimaps--synced-maps

**Comment by dceejay** [comment]
or how about this one ? https://github.com/Norkart/Leaflet-MiniMap

**Comment by Aterfax** [comment]
Looks great! My key feature is the ability to control the main map and minimap independently if desired with the option to sync :)

**Comment by dceejay** [comment]
OK - now in v 2.5

**Comment by Aterfax** [comment]
Awesome! Many thanks for the hard work!
