### ISSUE TITLE
Map click event

### ISSUE THREAD

**Issue by namgk** [dceejay/RedMap#146]
Hi there,

Is there away to listen to map click event (click anywhere on the map)? 

When I click on a marker it opens the popup and I'm wondering if there's a way to click anywhere on the map to close such popup or do something else?

Thanks

**Comment by dceejay** [comment]
each popup should have a x close button top right you can use to close the popup.

**Comment by namgk** [comment]
Yes the problem is when you click on many markers and the popups don't disappear automatically. I'm not sure if there's any option that I missed to dismiss these popups automatically.

If you can click on the map to close all of the popups that'd be great.

**Comment by dceejay** [comment]
set Esc key to close all open popups in v2.5.2
