### ISSUE TITLE
Connect event only on worldmap in node 

### ISSUE THREAD

**Issue by adminfriso** [dceejay/RedMap#147]
When setting the worldmap in node to "connection event only" it does not only trigger on the connection event. it accually triggers on all events

![Screenshot 2020-10-27 at 15 49 16](https://user-images.githubusercontent.com/23073031/97318276-fa9b9680-186b-11eb-98bf-8ef9ce3014a2.png)

**Comment by dceejay** [comment]
Refactored recently in 2.7.0
