### ISSUE TITLE
how can add button as json data?

### ISSUE THREAD

**Issue by halukmy** [dceejay/RedMap#148]
contextmenu: '<button name="Clicker" onclick=\'feedback(this.name)\'>Click me</button>'

can anyone help me to convert it to json?

"{"test":"valu123" " }" runs perfect but when i try to add button , it just doesnt work!

"{"test":"valu123" ,"contextmenu":"<button name="Clicker" onclick=\'feedback(this.name)\'>Click me</button>" }"

**Comment by dceejay** [comment]
you will need to escape the " inside the html with \   so \"Clicker\" etc.
please use the Node-RED discourse forum or slack channel for general how-to type questions so we can keep the issues for code bugs etc. Thanks

**Comment by halukmy** [comment]
you are true hero of nodered civilization dear @dceejay 

but i will be so happy to if there is a how to use samples of usage the subtopics i shared

i am a c# developer so new on nodered using payloads with mqtt and grpc it will be super good so i will share on forum next , thanks!

deleted : set to true to remove the named marker. (default false)
draggable : set to true to allow marker to be moved. (default false)
layer : specify a layer on the map to add marker to. (default "unknown")
speed : when combined with bearing, draws a vector.
bearing : when combined with speed, draws a vector.
accuracy : when combined with bearing, draws a polygon of possible direction.
color : CSS color name or #rrggbb value for bearing line or accuracy polygon
icon : font awesome icon name, weather-lite icon, :emoji name:, or https://
iconColor : Standard CSS colour name or #rrggbb hex value.
SIDC : NATO symbology code (can be used instead of icon). See below.
building : OSMbulding GeoJSON feature set to add 2.5D buildings to buildings layer. See below.
ttl : time to live, how long an individual marker stays on map in seconds (overrides general maxage setting, minimum 20 seconds)
photoUrl : adds an image pointed at by the url to the popup box.
videoUrl : adds an mp4 video pointed at by the url to the popup box. Ideally 320x240 in size.
weblink : adds a link to an external page for more information. Either set a url as a string, or an object like {"name":"BBC News", "url":"https://news.bbc.co.uk", "target":"_new"}
addtoheatmap : set to false to exclude point from contributing to the heatmap layer. (default true)
intensity : set to a value of 0.1 - 1.0 to set the intensity of the point on the heatmap layer. (default 1.0)
popped : set to true to automatically open the popup info box, set to false to close it.
popup : html to fill the popup if you don't want the automatic default of the properties list. Using this overrides photourl, videourl and weblink options.
label : displays the contents as a permanent label next to the marker, or
tooltip : displays the contents when you hover over the marker. (Mutually exclusive with label. Label has priority)
contextmenu : an html fragment to display on right click of marker - defaults to delete marker. You can specify $name to pass in the name of the marker. Set to "" to disable just this instance.

**Comment by halukmy** [comment]
"{"name":"1310","Uygulanan Enerji":"6","Bağlı Uygulama":"DownPole","Cihaz Özellikleri":"XEN Module","layer":"areylight","weblink ":"areylight,","lat":37.027859, "lon":27.987977,"popup":'<button type = "button" onclick ='feedback("Dave","some data you want to send")'>Click Me!</button> ',"icon":"https://image.flaticon.com/icons/png/512/2892/2892056.png"}"

@dceejay  whats wrong on this string? i get this error
"Unexpected token ' in JSON at position 184"


just try to simulate

msg.payload = {
    name:"Dave",
    lat:51.05,
    lon:-1.35,
    popup:'<button type="button" onclick=\'feedback("Dave","some data you want to send")\'>Click Me!</button>'
}
return msg;

but somethng wrong

**Comment by adminfriso** [comment]
@halukmy The issue is in your quotation. 
In JSON double quotes are used for defining the param name and the (string) value. in the value of popup you used single quotes and therefor it cannot parse it correct.

The way to solve this is to use double quotations for the String assignment in JSON, and then you can use single quotiations in the html.

`
{
    "name": "1310",
    "Uygulanan Enerji": "6",
    "Bağlı Uygulama": "DownPole",
    "Cihaz Özellikleri": "XEN Module",
    "layer": "areylight",
    "weblink ": "areylight,",
    "lat": 37.027859,
    "lon": 27.987977,
    "popup": "<button type = 'button' onclick ='feedback('Dave','some data you want to send')'>Click Me!</button>",
    "icon": "https: //image.flaticon.com/icons/png/512/2892/2892056.png"
}
`
For as far as i know HTML accepts single quotations, if it does not you can escape the double quotations. Therefor your popup value would look like this.

`
{
    "popup": "<button type = \"button\" onclick =\"feedback(\"Dave\",\"some data you want to send\")\">Click Me!</button>"
}

`
