### ISSUE TITLE
Some of the examples fail to load the map when using the 'The map can be found here.' link of the info tab

### ISSUE THREAD

**Issue by juggledad** [dceejay/RedMap#149]
node-red v1.2.5
node.js v12.13.0
node-red-contrib-web-worldmap v2.7.1

MacOS 10.14.6
Safari, FireFox, Chrome all experience the same issue

Example flows effected
Add Geojson Building
Basic Map
Earthquake

If you import any of those three sample flows, deploy, Click on the worldmap node, click the 'Info' tab in the right sidebar and then click on the 'The map can be found `here`.' link, an `Cannot GET /undefined` error will occur with the URL reported as: http://your_ip:1880/undefined 

Replacing the worldmap node with a fresh copy resolves the issue.

**Comment by juggledad** [comment]
Created a [PR](https://github.com/dceejay/RedMap/pull/150) to address these issues.

**Comment by dceejay** [comment]
Closed by d0205a66430b002706624f4f378e12ea081850e8
