### ISSUE TITLE
Possibility to add markers without lat, long

### ISSUE THREAD

**Issue by eriklindstein** [dceejay/RedMap#151]
I would like to be able to send a few draggable icons into the map but I can't find a way to send them to the map without knowing where the map is positioned. 

Basically I would like to send the new icon to "center" of the map without knowing lat, long.
Is this possible?

Something like this;
{
    "name": "c1",
    "draggable": true,
    "icon": "satellite",
    "label": "C1",
    "position": "center"
}

**Comment by dceejay** [comment]
Hi - no this is not possible. You can either set the map to a known position and zoom then add the markers or if the map is in move to marker mode you could add them and the map will move to where yo add them.
