### ISSUE TITLE
Baselayer Overlay Menu Icon

### ISSUE THREAD

**Issue by smallf00t** [dceejay/RedMap#152]
Hi, 
with worldmap.css and leaflet.css i can change color/font size of the box
But i would like to add icon menu instead of radio and a submenu and img to the overlay section
iconUrl for baselayer doesn t work
May il have to add a leaflet addon ? or modify worldmap.js ?

Thanks

**Comment by dceejay** [comment]
Hi,
I'm not quite understanding what you are trying to do ? If you want to replace the built in layer menu then yes you will need to edit the source code to add that in instead. I think I did include (but not use) one different one - see worldmap/worldmap.js Line 1067 - so maybe you can hack around here.
![image](https://user-images.githubusercontent.com/5375409/103345459-5d3a2a00-4a89-11eb-9bbd-78f0e6379dad.png)

**Comment by smallf00t** [comment]
Hi thanks for your answer 
i try to organize it like this leaflet [plugin ](https://github.com/stefanocudini/leaflet-panel-layers)
![image](https://user-images.githubusercontent.com/28515330/103349173-78fafb80-4a9c-11eb-8248-6146f9c6afea.png)

**Comment by dceejay** [comment]
yes - I have seen that plugin - and it's not something I'm looking to implement, so over to you :-) Good luck.
