### ISSUE TITLE
TYPE attrib error

### ISSUE THREAD

**Issue by raz0rsedge1975** [dceejay/RedMap#153]
I had some working nodes updated to 2.8.2 last night and realized that there are no icons shown anymore. After further investigation I found the attribute "type", which is provided by the API I am using, caused the icons to not show up.

Reproduce: create an icon with type and without type attrib. My Example payload comming from the API:
`msg.payload={
    "layer":"Drones",
    "name": msg.payload[0],
    //"type": msg.payload[1],
    "date": msg.payload[2],
    "age": msg.payload[3],
    "lat": msg.payload[4], 
    "lon": msg.payload[5],
    "height": msg.payload[6],
    "speed": msg.payload[9],
    "bearing": msg.payload[10],
    "vert-speed": msg.payload[11],
    "turn-rate": msg.payload[12],
    "relay": msg.payload[16],
    "tooltip": tooltip,
    "battery": msg.payload[18],
    "label": tooltip0[0]+"<br>"+msg.payload[6]+" m<br>"+zulu[1],
    "icon": icon0,
    "iconColor": icolor0,
    "lineColor":"#e69900",
    "popped": false
    // if type is defined here, icon disappears
};`

maybe its fixed after 2.8.2 but atm I am too afraid to test it :)

Thanks for your ongoing awesome work!

Raz0rsEdge

**Comment by dceejay** [comment]
simple/workaround fix is to rename that property to something other than type.
I will investigate.

**Comment by raz0rsedge1975** [comment]
Thanks for the fast response!
