### ISSUE TITLE
Readdir -> exif -> worldmap

### ISSUE THREAD

**Issue by mikakaraila** [dceejay/RedMap#154]
Any change to tune direction arc shown on map?

![image](https://user-images.githubusercontent.com/5184524/109976152-1de7be00-7d04-11eb-9238-d5b1894d97e4.png)

**Comment by mikakaraila** [comment]
Should I use smaller pan? I didn´t find documentation for this:

![image](https://user-images.githubusercontent.com/5184524/109976639-ab2b1280-7d04-11eb-8467-0ed6a379f625.png)

**Comment by dceejay** [comment]
It's just reporting what is in the exif - so not sure how it could be tuned - either you trust the camera or you don't - if not then yes you can apply whatever function you like before plotting.The range rings etc are documented in the readme - https://github.com/dceejay/RedMap#arcs-range-rings

**Comment by mikakaraila** [comment]
Thanks, ranges with zoom factor 18 with default values were too big.
Now it looks much better:
![image](https://user-images.githubusercontent.com/5184524/110232771-857e5300-7f28-11eb-8fb0-1deaf7e004b5.png)
