### ISSUE TITLE
ui_worldmap not appearing in side menu

### ISSUE THREAD

**Issue by matteos1** [dceejay/RedMap#158]
in my node red configuration  not appear ui_worldmap. any solution?

**Comment by dceejay** [comment]
I assume you have the node-red-dashboard installed ? Which versions of 
dashboard ?
Node-RED ?
node.js ?

**Comment by matteos1** [comment]
node red v.1.2.9

**Comment by matteos1** [comment]
> any errors or warnings in the browser javascript console ?
> The other worldmap nodes appear OK ? - as do the regular dashboard nodes ?

no error, nodered is an addon of home assistant.
![image](https://user-images.githubusercontent.com/16237822/110761243-c9869600-824f-11eb-9555-29daf73542e9.png)

**Comment by dceejay** [comment]
Sorry - and which version of worldmap - I think there was a fix that tried to address this in 2.8.7

**Comment by matteos1** [comment]
version of worldmap 2.9.0

**Comment by dceejay** [comment]
Ok - I'm at a bit of a loss - I don't use HA so no idea what extra constraints that is adding. All it does is only try to load if it can find the main dashboard - so obviously something is blocking that. (line 166 of worldmap.js)

**Comment by anhtu91** [comment]
I have same problem. Did you guys find solution?

**Comment by dceejay** [comment]
you could try upping the timeout on line 213 or worldmap.js from 250 to say 500. See if that improves the situation. It shouldn't be necessary unless the hardware is very slow but let's see.

**Comment by matteos1** [comment]
> you could try upping the timeout on line 213 or worldmap.js from 250 to say 500. See if that improves the situation. It shouldn't be necessary unless the hardware is very slow but let's see.

not work

**Comment by anhtu91** [comment]
> > you could try upping the timeout on line 213 or worldmap.js from 250 to say 500. See if that improves the situation. It shouldn't be necessary unless the hardware is very slow but let's see.
> 
> not work
Try out older version

**Comment by matteos1** [comment]
> > > you could try upping the timeout on line 213 or worldmap.js from 250 to say 500. See if that improves the situation. It shouldn't be necessary unless the hardware is very slow but let's see.
> > 
> > 
> > not work
> 
> Try out older version

myversion of worldmap is 2.9.0

**Comment by PierreLevres** [comment]
Having exact same issue here in Home Assistant, ui_worldmap is greyed out, all other nodes function well. 
Remove and re-install did not help. 
According to the info the node was installed. 
Versions:

node-red 1.3.3
dashboard 2.28.2
node-red-contrib-web-worldmap 2.13.3

**Comment by Urs-Eppenberger** [comment]
I'm fairly new to this. I do see the ui_worldmap node. It is not grey, it has another colour, because it is listed in the group where all other ui related nodes are.

**Comment by PierreLevres** [comment]
Let me clarify. 
I have a production rPI4 with 
System: Home Assistant OS 5.13  (aarch64 / raspberrypi4-64)
Home Assistant Core: 2021.5.1
Home Assistant Supervisor: 2021.04.3
Node-Red Add-on version: 9.0.1. 
The addon runs Node Red 1.3.3. 
In the palette manager the node ui_worldmap is unusable: it is greyed out, and in the “dashboard” - group it is not present.

My development rPi3B+ runs Buster, Node-Red 1.3.2 
There the node is NOT greyed out AND visible in the “dashboard” - group. 




Binary comparison of the two machines, list identical files in the two directories…
Both machines are running dashboard 2.29.0.

**Comment by andreypopov** [comment]
ane news here? the same issue

**Comment by andreypopov** [comment]
I don't know how, but missing node appeared)

**Comment by PierreLevres** [comment]
Updated node-red-dashboard to 0.20.0 —> no improvement
Updated node-red-contrib-worldmap from 2.13.4 to 2.15.5 —> no improvement

So for me ui_worldmap node is still nog available… all other nodes are...

**Comment by otavioon** [comment]
Hello,

I am with the same problem. ui_worldmap do not appear in side bar. Any workarround?

**Comment by dceejay** [comment]
If anyone has a way to recreate this without requiring HA please let me know.

**Comment by mcdonaldajr** [comment]
I have the same issue, running node red embedded into signal K server. Given that is two examples of the issue when running embedded node red, I think we can assume it is something different about embedded rather than stand alone node red that is causing the problem. Interestingly, it works OK accessed directly i.e. not through the dashboard, e.g. http://192.168.1.140:3000/plugins/signalk-node-red/redApi/worldmap/

![Image 24-09-2021 at 12 08](https://user-images.githubusercontent.com/4070175/134665289-aae3fa91-fa27-46ae-b93c-f85a6f2e7095.jpeg)

**Comment by dceejay** [comment]
I've recently pushed an update to v2.15.8 that adjusts the timing of the check for the dashboard. Can you try that. It should also add to the console log if it doesn't load so can you check that also please. Thanks

**Comment by mcdonaldajr** [comment]
Still got problem. Here's the lo
[log.txt](https://github.com/dceejay/RedMap/files/7225999/log.txt)
g

**Comment by mcdonaldajr** [comment]
This may be the offending line.
`------------------------------------------------------ 
Sep 24 13:29:19 24 Sep 13:29:19 - [warn] [node-red-contrib-web-worldmap/worldmap] SyntaxError: Unexpected token ? (line:34) 
Sep 24 13:29:19 24 Sep 13:29:19 - [warn] `

**Comment by dceejay** [comment]
Hmm sorry about that - please try latest 2.16.1 that reverts that change

**Comment by mcdonaldajr** [comment]
Thanks, back where we were. Unfortunately, I am at the mercy of the Signal K team as regards the version of nodejs. I will see if I can persuade them to upgrade. Do you think that will fix the problem?

**Comment by dceejay** [comment]
Hi - probably not - but they should do anyway for security going forwards..

**Comment by dceejay** [comment]
Ok - we've found the callback test use a path .ui-worldmap ...  and many webservers (not unreasonably) block calls to paths starting . (to prevent .htaccess etc etc.. now fixed in version 2.21.2
