### ISSUE TITLE
Custom icon markers https only

### ISSUE THREAD

**Issue by rogerjames99** [dceejay/RedMap#159]
The need to specify custom icon markers as https makes it difficult to access icons stored on the local system, for example anything stored in httpStatic. I am probably missing something here, but having to turn on httpStaticAuth and use https://localhost:1880/icon.png causes lots problems with other icons not being available (lots of missing token errors at startup). 

Roger

**Comment by dceejay** [comment]
I don't think it has to be https - did you try it without ?

**Comment by rogerjames99** [comment]
Sorry . I thought I had replied on this. Definitely ok to close. I hope this post does not reopen it!
