### ISSUE TITLE
Possibility to change line width for arc

### ISSUE THREAD

**Issue by eriklindstein** [dceejay/RedMap#161]
Im trying to change the width for the lines in a arc but i'm not able to do so.
Is there any property I can set to do this?

(also it would be very nice to be able to use fillColor it like for circles)

Here is my payload;

            msg.payload = { 
                "name": "123", 
                "layer":"Sector",
                "lat":49.528498370936, 
                "lon":28.105769597706843,
                "icon":"uav",
                "iconColor": "#ffce44",
                "ttl": 1,
                "bearing": 123,
                "length": 800,
                "color": "#ffce44",
                arc: {
                    "ranges": [800],
                    "pan": 123,
                    "fov": 10,
                    "color": "#ffce44"
                }
        }

**Comment by dceejay** [comment]
Fixed in 2.11.2 :-)
add    property   `weight` to the arc as thickness in pixels
