### ISSUE TITLE
[Feature Request] parameters in the url

### ISSUE THREAD

**Issue by meeki007** [dceejay/RedMap#162]
Wish I could send parameters in the url like I do in dashboard.
http:/my-ip-here:1880/worldmap/?testing=true

**Comment by dceejay** [comment]
to accomplish what ? This is a Node-RED nodes so we pass things in via messages :-)

**Comment by meeki007** [comment]
This is not a priority but happy your curious about what the heck I'd use it for.

Right now I I use the map for the companies camera system. I am not part of the IT dept so access is controlled via a (insert company secret here )  server. Problem is I've been told I can get users credentials (I identifying information, not pass words ) sent along by the reverse proxy in a header or parameters.

In this information I get info if its from accounting / warehouse / department foo here,
I would like to only give access to that sections cameras so they quit clicking on 30 cameras outside there section and over loading the mjpeg streams just because they want to watch their car out in the secure lots.

Request comes in with parameter ?dept="warehouse"&user="FredFredricson" and then I can only show the cameras in their section(s) tied to the _sessionid. I then can create a log to track what video a user reviewed or what live streams they had running. Right now I have a login form they use on the map tied to the _sessionid and every time they refresh the map page they have to log back in. Be nice to only have to use the company's login and not have a second map login. 

Not a big deal at the moment just an idea.

**Comment by meeki007** [comment]
![ihttps://ibb.co/gZCB09N](https://ibb.co/gZCB09N)

**Comment by dceejay** [comment]
not really sure how that would work nicely - as I'm currently serving the page statically - the parameters would end up at the web page in the browser - which then has to send them back to the worldmap in node for you to handle to then send back some icons/widgets via the websocket etc... all seems a bit convoluted.

**Comment by meeki007** [comment]
No prob.. It was just a wish. Thanks for getting back to me.

**Comment by dceejay** [comment]
Well it's easy enough to feed them back but...

as a test you can change line 85 of worldmap/worldmap.js to be
```
ws.send(JSON.stringify({action:"connected",parameters:Object.fromEntries((new URL(location)).searchParams)}));
```
and see if that helps.

**Comment by meeki007** [comment]
@dceejay "Well it's easy enough to feed them back but..."
I get that I then have to send all the widgets and stuff after I filter the user. I already do this. heck I even took the time banging my head against the wall making a auto centre for the map based on where I place the cameras on the map.

```JS

// reformat lat: key's value in object to an Array
var lat_to_array = msg.payload.map(obj => obj.lat);

// reformat lon: key's value in object to an Array
var lon_to_array = msg.payload.map(obj => obj.lon);

// get the average of all the values in lat array
let sum_lat = lat_to_array.reduce((previous, current) => current += previous);
let avg_lat = sum_lat / lat_to_array.length;

// get the average of all the values in lon array
let sum_lon = lon_to_array.reduce((previous, current) => current += previous);
let avg_lon = sum_lon / lon_to_array.length;

//find the greatest distance of sepreration between two cameras on the map
// used to set zoom distance on map
//get highest and lowest values in both arrays
var lat_max = Math.max(...lat_to_array);
var lat_min = Math.min(...lat_to_array);
var lon_max = Math.max(...lon_to_array);
var lon_min = Math.min(...lon_to_array);
var lat_lon_seperation_max_array = [(lat_max) - (lat_min),(lon_max) - (lon_min)];
var lat_lon_seperation_max = Math.max(...lat_lon_seperation_max_array);

//set the map zoom level
var map_zoom_level = 2;
if (lat_lon_seperation_max < (1/512)) { map_zoom_level = 18; }
else if (lat_lon_seperation_max < (2/512)) { map_zoom_level = 17; }
else if (lat_lon_seperation_max < (4/512)) { map_zoom_level = 16; }
else if (lat_lon_seperation_max < (8/512)) { map_zoom_level = 15; }
else if (lat_lon_seperation_max < (16/512)) { map_zoom_level = 14; }
else if (lat_lon_seperation_max < (32/512)) { map_zoom_level = 13; }
else if (lat_lon_seperation_max < (64/512)) { map_zoom_level = 12; }
else if (lat_lon_seperation_max < (128/512)) { map_zoom_level = 11; }
else if (lat_lon_seperation_max < (256/512)) { map_zoom_level = 10; }
else if (lat_lon_seperation_max < (512/512)) { map_zoom_level = 9; }
else if (lat_lon_seperation_max < (1024/512)) { map_zoom_level = 8; }
else if (lat_lon_seperation_max < (2048/512)) { map_zoom_level = 7; }
else if (lat_lon_seperation_max < (4096/512)) { map_zoom_level = 6; }
else if (lat_lon_seperation_max < (8192/512)) { map_zoom_level = 5; }
else if (lat_lon_seperation_max < (16384/512)) { map_zoom_level = 4; }


msg.payload = { command:{layer:"",lat:avg_lat,lon:avg_lon,zoom:map_zoom_level} };



//msg.map_zoom_level = map_zoom_level;
msg.avg_lat = avg_lat;
msg.avg_lon = avg_lon;
//msg.lat_lon_seperation_max = lat_lon_seperation_max;


return msg;
```

**Comment by meeki007** [comment]
By 90% work done was time taken to get up to speed with the worldmap.js code.  here is a 0.01% contribution weighed against all the work you have done before me :P 

Pull request for _sessionip - I don't know if you want it but im going to keep using it for my needs.
https://github.com/dceejay/RedMap/pull/163

![https://i.ibb.co/GM3yFxv/sessionip.jpg](https://i.ibb.co/GM3yFxv/sessionip.jpg)

**Comment by dceejay** [comment]
Hi - yeah I don't mind adding _sessionid. Do we really need ip ? (don't mind adding but do we need both ?)
(also need to check they are same variables names as dashboard...) but yes PR .
