### ISSUE TITLE
map is not stable. 

### ISSUE THREAD

**Issue by mofisher** [dceejay/RedMap#164]
I am new to Node-Red & use  worldmap.
When first time deploy, it's usually fine. But I try to close explorer to reconnect,it often failed to show map.  
For now, when I find failed,I redeploy. It's so bad idea.
Please help me to  solve it. Thanks a lot.

node version : V12.21.0
node-red  version: V1.2.9
node-red-contrib-web-worldmap   version : 2.12.1 

error message is as attach file.

![2021-04-01 122510](https://user-images.githubusercontent.com/74110796/113243335-67b4cb80-92e5-11eb-9a67-ac30b2424e13.png)

**Comment by mofisher** [comment]
I use the sample of  embed Map in Dashboard.
When embed Map failed, I try Ctrl+Shift+M  it works fine. 
![2021-04-01 134820](https://user-images.githubusercontent.com/74110796/113249278-0692f500-92f1-11eb-8989-3cc51cfcb632.png)

![2021-04-01 134540](https://user-images.githubusercontent.com/74110796/113249023-9b492300-92f0-11eb-962d-97c0490540ec.png)

**Comment by dceejay** [comment]
None of those errors relate to the map - and are not significant.
You need to inject the info to the template AFTER the map has connected. The easy way to do that is to either use a worldmap in node set to output connect events only - to trigger the sending of the data. Or to use a dashboard worldmap node 
![image](https://user-images.githubusercontent.com/5375409/113269668-97a5a400-92d0-11eb-8fac-c38f52e29d3e.png)

In general it is much easier to get help via either slack or the discourse forum, leaving the issues for actual code issues. thanks
