### ISSUE TITLE
msg.payload.name and umlauts

### ISSUE THREAD

**Issue by Urs-Eppenberger** [dceejay/RedMap#165]
I played around with the world map node yesterday, connecting my Tesla car location data to the worldmap. Very simple.
Initially I did not get it to work, and there were no errors in the sidebar from the node. I copied the name of the car from the Tesla data to msg.payload.name.
The car name is "öise Tesla".

Only after I changed this to "Tesla", it worked.

I did not dig into this further, but maybe the msg.payload.name can't handle umlauts?

Urs Eppenberger
Switzerland

**Comment by dceejay** [comment]
Works when tested locally, closing unless a failing use case can be provided.
