### ISSUE TITLE
map list : Open Topo Map

### ISSUE THREAD

**Issue by Urs-Eppenberger** [dceejay/RedMap#166]
In the map list on the web gui, there is the option to select the "Open Top Map". I personally like it for my use case.
It is not selectable in the settings of the node itself.
Is this an oversight on my side (quite often the case), a bug or a feature?
If it is one of the latter two cases, is there a way around this?

Kind regards,

Urs Eppenberger
Switzerland

**Comment by dceejay** [comment]
ah - two lists out of sync - will fix

**Comment by Urs-Eppenberger** [comment]
thanks. No need to hurry.
