### ISSUE TITLE
[Feature request] Supply lat and lon from existing marker if they are not in the incoming data.

### ISSUE THREAD

**Issue by rogerjames99** [dceejay/RedMap#167]
Hi dceejay,
Thanks for the quick fix to the layer stuff.

Having to supply the correct lat and lon when you just want to update a custom property in a marker is a pain. The name field has to be unique across the whole map. So would it be possible to use that to look up the current lat lon of the marker and add that to the incoming request. A possible place to do this could be in the current error return path at around line 1404.

What is your opinion on this?

**Comment by dceejay** [comment]
Sorry - not quite sure what you mean...

Does this not work already ?
```
[{"id":"a61431f6.f962c","type":"worldmap","z":"64eed394.c7935c","name":"","lat":"","lon":"","zoom":"","layer":"","cluster":"","maxage":"","usermenu":"show","layers":"show","panit":"false","panlock":"false","zoomlock":"false","hiderightclick":"false","coords":"false","showgrid":"false","allowFileDrop":"false","path":"/worldmap","x":620,"y":300,"wires":[]},{"id":"1bc941b9.cc13ae","type":"inject","z":"64eed394.c7935c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":230,"y":300,"wires":[["b75efa15.504a68"]]},{"id":"b75efa15.504a68","type":"function","z":"64eed394.c7935c","name":"Blue","func":"msg.payload = {\n    name: \"Dave\",\n    lat:51,\n    lon:-1.3,\n    iconColor:\"blue\"\n}\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":390,"y":300,"wires":[["a61431f6.f962c"]]},{"id":"2dec2aac.30c916","type":"inject","z":"64eed394.c7935c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":220,"y":380,"wires":[["7a51c957.057768"]]},{"id":"7a51c957.057768","type":"function","z":"64eed394.c7935c","name":"green","func":"msg.payload = {\n    name: \"Dave\",\n    iconColor:\"green\"\n}\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":380,"y":380,"wires":[["a61431f6.f962c"]]}]
```

**Comment by rogerjames99** [comment]
Yes that does work. But what I am asking is making it work without having to specify lat and lon. I.e.

**Comment by dceejay** [comment]
err the green button doesn't have lat and lon...

**Comment by rogerjames99** [comment]
Ooops . Huge apologies.

Can I just change this to a request to change the README.

Usage
...
The minimum msg.payload must contain name, lat and lon properties, for example

**Comment by dceejay** [comment]
Well the minimum requirement to create a marker is just that - which is the 99% use case.

**Comment by rogerjames99** [comment]
Don't rub it in! I am embarassed enough that I had to totally forgotten that I had used that facility in my own code a few weeks back after you fixed the layer stuff :-)
