### ISSUE TITLE
Adding a speed to objects appears to cause a BAD DATA error in Browser console and failure to display objects

### ISSUE THREAD

**Issue by Aterfax** [dceejay/RedMap#169]
Adding a speed entry to objects appears to be breaking display and causing browser errors see below:

![image](https://user-images.githubusercontent.com/8648058/122657266-fd7c2c00-d159-11eb-80f6-63d9ce5d341a.png)

See the tracks continue to render but the objects themselves do not, see video:

https://streamable.com/b2a13k

Error seems related to worldmap.js:97: 

`    ws.onmessage = function(e) {
        try { var data = JSON.parse(e.data); handleData(data); }
        catch (e) { if (data) { console.log("BAD DATA",data); } }
        // console.log("DATA",typeof data,data);
    };
}`

But I am not sure - taking a given data update object sent to the browser marked as BAD DATA and sticking it into a JSON parser responds that the JSON is valid. Possibly related to the new speed parsing logic? I tried putting values in as string and as number - nothing functions correctly and any speed values for objects results in bad data.

**Comment by dceejay** [comment]
Can you share some data that you are sending so that I can replicate and test ?

**Comment by Aterfax** [comment]
I think there may have been a conflict with either node-red-contrib-home-assistant / node-red-contrib-lyteworx-cluster as purging these from Node Red appears to have cleared the issue

In any case I can no longer replicate the issue so I will close this for now - if the problem does pop back up I will re-open.

Cheers for all the work on the worldmap nodes!

**Comment by DRazumovskiy** [comment]
Hi, I have the same issue as with BAD DATA thrown in console when speed is added to payload.

All cases that I tried:

1. Payload does not contain speed - no errors
2. Payload contains speed represented by decimal number - BAD DATA in console
3. Payload contains speed and the value is 0 - BAD DATA in console
4. After the map is loaded the object is shown with heading marker:
![image](https://github.com/dceejay/RedMap/assets/13840421/2ca8ec7b-a66d-4353-830b-b12521fe32aa)
after the first data update the heading marker disappears:
![image](https://github.com/dceejay/RedMap/assets/13840421/369711f1-20c8-4064-aa31-3cdef306bdaa)

This is a JSON with speed that causes BAD DATA:
`{"name":"Maria Pinta","lat":44.001767,"lon":9.685178,"hdg":164,"speed":3.2,"label":"Maria Pinta","icon":"ship","iconColor":"#35ADF8","color":"#44803F","layer":"barche","ricevuto":"0 sec fa","skipper":"Senza skipper"}`

This is a JSON without speed that does not cause errors:
`{"name":"Magialla","lat":44.079665,"lon":9.831423,"hdg":0,"label":"Magialla","icon":"ship","iconColor":"#D8D8D8","color":"#A3A3A2","layer":"barche","ricevuto":"7 min fa","skipper":"Senza skipper"}`
