### ISSUE TITLE
Multiple Heatmap Layers

### ISSUE THREAD

**Issue by Picole9** [dceejay/RedMap#170]
RedMap looks really interesting. But i have a problem: i'm trying to build multiple heatmap layers (for different airplane-altitudes) but im not sure how to do that. The code looks like it only use one heatmap so i try to work around that. I tried to clear the heatmap so i could build a new one on a buttonpress but i'm not sure how to do that. Is there a command for clearing the heatmap or a similar feature or is it possible to implement that in a way?

**Comment by dceejay** [comment]
Hi - must admit I've no idea... it was initially intended just to work across all visible layers so it's probably fairly hardcoded like that. though you can pass in msg.payload.addtoheatmap to give finer control on what gets added - but it doesn't do it in layers at all. When the heatmap is visible the should be a button to clear it that appears.

**Comment by Picole9** [comment]
Ah i used the map in Nodered in an iframe so i didn't realized there is that button available in a 'normal' frame. Something like msg.payload.command.clearheatmap would be cool, so i could add buttons myself that delete the current heatmap and build a new one with different data. That way i could choose between different heatmaps.

**Comment by dceejay** [comment]
OK - v2.15.4 - you can send a {command: { clear: "heatmap" } } and it will clear the heatmap correctly.

**Comment by Picole9** [comment]
Thank you very much :)
