### ISSUE TITLE
Possible to plot simply X/Y Values as lines onto a empty map?

### ISSUE THREAD

**Issue by Mannshoch** [dceejay/RedMap#172]
I have the Idea to track my roomba on a simple map.

 Would you say It is possible to use UI_Worldmap to show the location he already was and his current location?

I would have to:
1. Clear the map on vacuuming start
2. draw a simple building boundary (preset it my self)
3. and send permanently the X/Y coordinates +/- 1000 to worldmap.

**Comment by dceejay** [comment]
This map node is based around leaflet.js which relies on lat, lon coordinates and inn general requires a map. In theory there is nothing to stop you creating your own map layer that allows a maxZoom of maybe 25 to let you get into room level zoom. but it would be up to you to do that and convert your co-ordinates to GPS positions..

I suspect the https://flows.nodered.org/node/node-red-contrib-ui-svg node would be more use as quite a few people use it for zoom layout type scenarios - animating things like lights and heating and so on.
