### ISSUE TITLE
Worldmap node don’t use or generate msg.socketid

### ISSUE THREAD

**Issue by lcse66** [dceejay/RedMap#183]
Hi, 
I'm using the excellent Worldmap node.

However, I am having difficulty when multiple sessions are connected. Specifically, I can't get other elements on the page to interact properly as Worldmap doesn't generate and doesn't use the dashboard session reference (msg.socketid). Is it possible to have the message generated by the ui_worldmap node (even during the connection event)?

But maybe I'm looking for the wrong solution, advice is welcome.

Thanks in advance.
Lorenzo

**Comment by dceejay** [comment]
If you inspect the full msg object you will see it reports `msg._sessionid` instead.
