### ISSUE TITLE
need  Attitude and Type to generate TAK types

### ISSUE THREAD

**Issue by brothercorvo** [dceejay/RedMap#184]
This is Corvo from FreeTAKServer's project.
We got some request to  transform RedMap this into a full TAK client
so if you ware willing to implement some functions I will take over the implementation of the API
the main functionality is to be able to create the different types of drop points (friendly, Hostile, neutral and unknow)
when a marker is clicked, depending from the status of 2 buttons attitude  and Type are set
```
{ "action": "click", "name":"Putin", "layer":"gps", "attitude": "hostile", "Type": "Sniper", "icon":"male", "iconColor":"blue", "lat":38.889, "lon":-77.0104 }  
```

Based on that I can send to the FTS rest API a message like this:
```
{
"longitude": -77.0104,
"latitude": 38.889,
"attitude": "hostile",
"geoObject": "Gnd Combat Infantry Sniper",
"how": "nonCoT",
"name": "Putin",
"timeout": 600  
}
```

**Comment by dceejay** [comment]
Hi,  great to see you.
When you right click on the map to create an icon
![image](https://user-images.githubusercontent.com/5375409/143301128-7df5988b-aa17-4e6e-8578-0d98a125ae18.png)

you can type in the name , then the icon - which can be a SIDC code (or short part thereof) eg  Dave,SFGPU to create
![image](https://user-images.githubusercontent.com/5375409/143301292-c07b5a5c-1a62-4770-866e-bdea1187a741.png)

or Corvo,SSAPMF for a fixed wing enemy aircraft
![image](https://user-images.githubusercontent.com/5375409/143301728-a7db5edd-86a5-49f5-bba6-e226ad50d98a.png)

You can usually change SIDC codes into COT codes  quite easily I think
SFGPU -> a-f-G-U   
SSAPMF -> a-h-A-M-F

Is that OK ?

**Comment by dceejay** [comment]
I have pushed a change so that that if you are online the  "form" now looks like
![image](https://user-images.githubusercontent.com/5375409/143307854-f58e6770-b7df-486f-9198-9058fb95ce01.png)

v2.21.8

**Comment by dceejay** [comment]
The other way to do it is to re-write the right click menu to be whatever you want - eg a simple form

![image](https://user-images.githubusercontent.com/5375409/143420162-20d4ea41-e50f-43c3-89a6-84be0992ee3b.png)

```
msg.payload = { command: {
contextmenu: String.raw`
Text <input type="text" id="sometext" value="hello"><br/>
Number <input type="number" id="somenum" value="5"><br/>
<input type="button" value="Send" onclick=
'feedback("myform",{
    "st":document.getElementById("sometext").value,
    "sn":document.getElementById("somenum").value,
})'
>
`
}}
return msg;
```

Example
```
[{"id":"7351100bacb1f5fe","type":"function","z":"4aa2ed2fd1b11362","name":"","func":"msg.payload = { command: {\ncontextmenu: String.raw`\nText <input type=\"text\" id=\"sometext\" value=\"hello\"><br/>\nNumber <input type=\"number\" id=\"somenum\" value=\"5\"><br/>\n<input type=\"button\" value=\"Send\" onclick=\n'feedback(\"myform\",{\n    \"st\":document.getElementById(\"sometext\").value,\n    \"sn\":document.getElementById(\"somenum\").value,\n})'\n>\n`\n}}\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":350,"y":360,"wires":[["a6a82f2e8efc44fc"]]},{"id":"7b595f0c8f6ac710","type":"worldmap in","z":"4aa2ed2fd1b11362","name":"","path":"/worldmap","events":"connect","x":195,"y":360,"wires":[["7351100bacb1f5fe"]]}]
```

sends 
![image](https://user-images.githubusercontent.com/5375409/143420437-ffa5fd31-3529-459d-8579-98ff83a843da.png)

**Comment by brothercorvo** [comment]
thanks, this is technically feasible, however it's not very comfortable for end users in a TAK scenario of Emergency.
What I wonder is if we can have a new layer, with a toolbox containing the basic types and attitude. As soon the toolbox is activated, a new element is created with auto-name (Sniper1, sniper2, etc).
The name can be edited later if necessary.
It's feasible?

**Comment by dceejay** [comment]
That still "feels" like a custom contextmenu - albeit a somewhat more complex one than the example above... Let me see if I can create one.

**Comment by dceejay** [comment]
Maybe something like
```
[{"id":"7351100bacb1f5fe","type":"function","z":"4aa2ed2fd1b11362","name":"","func":"msg.payload = { command: {\ncontextmenu: String.raw`\n<table border=0><tr>\n<th>Attitude</th><td><select id=\"myatt\">\n  <option value=\"friend\">Friend</option>\n  <option value=\"hostile\">Hostile</option>\n  <option value=\"neutral\">Neutral</option>\n  <option value=\"unknown\">Unknown</option>\n  <option value=\"pending\">Pending</option>\n  <option value=\"suspect\">Suspect</option>\n  <option value=\"assumed\">Assumed Friend</option>\n  </select></td>\n</tr><tr>\n<th>Type</th><td><select id=\"mytyp\" value=\" \" onchange=\"document.getElementById('mynam').value = this.value+'-'+parseInt(Math.random()*9999);\">\n  <option value=\"Rifleman\">Rifleman</option>\n  <option value=\"Grenadier\">Grenadier</option>\n  <option value=\"Mortar\">Mortar</option>\n  <option value=\"Medic\">Medic</option>\n  <option value=\"Teamleader\">Team Leader</option>\n  <option value=\"Hq\">HQ</option>\n  <option value=\"Sniper\">Sniper</option>\n  <option value=\"Recon\">Recon</option>\n  <option value=\"RTO\">RTO</option>\n  <option value=\"K9\">K9</option>\n</select></td>\n</tr><tr>\n<th>Timeout</th><td><input type=\"number\" id=\"mytout\" step=\"10\" value=\"300\">S</td>\n</tr><tr>\n<th>Name</th><td><input type=\"text\" id=\"mynam\"></td>\n</tr><tr>\n<th><input type=\"button\" value=\"Send\" onclick=\n'feedback(\"myform\",{\n    \"attitude\":document.getElementById(\"myatt\").value,\n    \"geobject\":document.getElementById(\"mytyp\").value,\n    \"timeout\":document.getElementById(\"mytout\").value,\n    \"name\":document.getElementById(\"mynam\").value,\n})'\n></th>\n</tr></table>\n`\n}}\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":315,"y":90,"wires":[["a6a82f2e8efc44fc"]]}]
```

**Comment by brothercorvo** [comment]
Works now, will be included in the next release of FreeTAKServer!
![image](https://user-images.githubusercontent.com/60719165/143496992-a26c1bc9-44ce-4d8a-bfff-d4033fb6ac56.png)

**Comment by dceejay** [comment]
More TAK like
```
```
[{"id":"7351100bacb1f5fe","type":"function","z":"bf6c9dc1a5062a3a","name":"add marker","func":"msg.payload = { command: {\ncontextmenu: String.raw`\n<table border=0><tr>\n<th>Attitude</th><td><select id=\"myatt\" style=\"width:153px;\" onchange=\"document.getElementById('mynam').value = this.value.substr(0,1).toUpperCase()+'.'+(new Date()).getDate()+'.'+(new Date()).getHours().toString().padStart(2,'0') + (new Date()).getMinutes().toString().padStart(2,'0') + (new Date()).getSeconds().toString().padStart(2,'0');\">\n  <option selected=\"true\" style=\"display:none;\">Please select</option>\n  <option value=\"friend\">Friend</option>\n  <option value=\"hostile\">Hostile</option>\n  <option value=\"neutral\">Neutral</option>\n  <option value=\"unknown\">Unknown</option>\n  <option value=\"pending\">Pending</option>\n  <option value=\"suspect\">Suspect</option>\n  <option value=\"assumed\">Assumed Friend</option>\n  </select></td>\n</tr><tr>\n<th>Type</th><td><select id=\"mytyp\" style=\"width:153px;\">\n  <option selected=\"true\" style=\"display:none;\">Please select</option>\n  <option value=\"Rifleman\">Rifleman</option>\n  <option value=\"Grenadier\">Grenadier</option>\n  <option value=\"Mortar\">Mortar</option>\n  <option value=\"Medic\">Medic</option>\n  <option value=\"Teamleader\">Team Leader</option>\n  <option value=\"Hq\">HQ</option>\n  <option value=\"Sniper\">Sniper</option>\n  <option value=\"Recon\">Recon</option>\n  <option value=\"RTO\">RTO</option>\n  <option value=\"K9\">K9</option>\n</select></td>\n</tr><tr>\n<th>Timeout</th><td><input type=\"number\" id=\"mytout\" step=\"10\" value=\"300\"> s</td>\n</tr><tr>\n<th>Name</th><td><input type=\"text\" id=\"mynam\"></td>\n</tr><tr>\n<th><input type=\"button\" value=\"Send\" onclick=\n'feedback(\"myform\",{\n    \"attitude\":document.getElementById(\"myatt\").value,\n    \"geobject\":document.getElementById(\"mytyp\").value,\n    \"timeout\":document.getElementById(\"mytout\").value,\n    \"name\":document.getElementById(\"mynam\").value,\n},\"FTS\",true)'\n></th>\n</tr></table>\n`\n}}\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":430,"y":330,"wires":[["6a201cf14cdeec50","12bddd2f58f614df"]]}]
```
