### ISSUE TITLE
Map seems to reset zoom level every 25 seconds

### ISSUE THREAD

**Issue by adawson-netafy** [dceejay/RedMap#185]
When I use my map for more than 25 seconds, the map will jump and zoom back out to the "Start" coordinates. This makes me lose my place when looking across large geographical areas.

The only "Map In" event I have set is "Connect" and I am on the latest plugin version 2.22.2. Is there anything I can do to avoid the map resetting itself? This is on Google Chrome. I can attach a video if needed as well.

**Comment by dceejay** [comment]
are you able to share your flow here ? Is the map set to auto pan to points or locked to position ? 
Have you checked all messages going to  the map to see if they have any extra commands in ?

**Comment by adawson-netafy** [comment]
Here is my flow for the map. It uses a simple JSON DB node to get the payload data. I can send you a dev version of the actual map I'm using on the web so you can see the behavior later today or tomorrow. 

Here my map node:
<img width="504" alt="2021-12-04_08-46-13" src="https://user-images.githubusercontent.com/63602127/144711804-fe8641d9-090d-4d3d-a05e-4ca24259d1c2.png">

Heres the Map In node -

<img width="522" alt="2021-12-04_08-47-05" src="https://user-images.githubusercontent.com/63602127/144711827-813caa15-0315-4ec3-a8e7-fca9f4758d7f.png">


    {
        "id": "26ec8c9037ba430d",
        "type": "DataOut",
        "z": "b4afb7c4b5e96840",
        "collection": "e8195ef9d497d22c",
        "name": "",
        "topic": "/backlog",
        "error": true,
        "x": 2600,
        "y": 2060,
        "wires": [
            [
                "a76ffa9d0c3a756f"
            ]
        ]
    },
    {
        "id": "46b52538b96149c4",
        "type": "change",
        "z": "b4afb7c4b5e96840",
        "name": "",
        "rules": [
            {
                "t": "set",
                "p": "datapath",
                "pt": "msg",
                "to": "/",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 2410,
        "y": 2060,
        "wires": [
            [
                "26ec8c9037ba430d"
            ]
        ]
    },
    {
        "id": "a76ffa9d0c3a756f",
        "type": "split",
        "z": "b4afb7c4b5e96840",
        "name": "",
        "splt": "\\n",
        "spltType": "str",
        "arraySplt": 1,
        "arraySpltType": "len",
        "stream": false,
        "addname": "",
        "x": 2750,
        "y": 2060,
        "wires": [
            [
                "8c0c06b85d4cfd1d"
            ]
        ]
    },
    {
        "id": "d71291081e035d11",
        "type": "worldmap in",
        "z": "b4afb7c4b5e96840",
        "name": "",
        "path": "/backlog",
        "events": "connect",
        "x": 2130,
        "y": 2060,
        "wires": [
            [
                "46b52538b96149c4"
            ]
        ]
    },
    {
        "id": "8c0c06b85d4cfd1d",
        "type": "worldmap",
        "z": "b4afb7c4b5e96840",
        "name": "",
        "lat": "44.3458545",
        "lon": "-71.4627607",
        "zoom": "9",
        "layer": "OSMG",
        "cluster": "",
        "maxage": "",
        "usermenu": "show",
        "layers": "show",
        "panit": "false",
        "panlock": "false",
        "zoomlock": "false",
        "hiderightclick": "false",
        "coords": "none",
        "showgrid": "false",
        "allowFileDrop": "false",
        "path": "/backlog",
        "overlist": "DR,CO,RA,DN,HM",
        "maplist": "OSMG,OSMC,EsriC,EsriS,EsriT,EsriDG,UKOS,SW",
        "mapname": "",
        "mapurl": "",
        "mapopt": "",
        "mapwms": false,
        "x": 2900,
        "y": 2060,
        "wires": []
    },
    {
        "id": "e8195ef9d497d22c",
        "type": "json-db-collection",
        "name": "",
        "collection": "backlog",
        "save": true
    }
]`

**Comment by dceejay** [comment]
ok - looks ok so far... 
Can you add a debug node just after the database set to send data to the console.log and then cut/paste and example of the data you get back (Between   ```   ```  so I can import it (not a picture). Thanks

**Comment by adawson-netafy** [comment]
After watching the full msg object debug node and my map page, I noticed what seems to be the issue. It seems the "sessions" are refreshing every 25 seconds, each time the exact same but with a new "session id". Ideally, each session could be extended to keep the same session ID for a custom time like 10 minutes/1 hour/etc.

<img width="652" alt="2021-12-06_09-34-49" src="https://user-images.githubusercontent.com/63602127/144864925-a73e434a-8215-41b5-9c1e-62f841f7bf15.png">

Here is the copied msg object. You can also see the example of the zoom out here on this dev clone I set up (I removed all customer PII data): https://dev-nodered.netafyengine.com/backlog/

I can also give you access to the Node-RED login as well if it'll help

`backlog : msg : Object
object
payload: array[82]
[0 … 9]
[10 … 19]
[20 … 29]
[30 … 39]
[40 … 49]
[50 … 59]
[60 … 69]
[70 … 79]
[80 … 81]
topic: "backlog"
_sessionid: "5934ee0d-144c-4efb-83cf-19b2aac71f93"
_sessionip: "24.218.43.28, 34.149.122.89"
_msgid: "da8f54e1c8859856"`

**Comment by dceejay** [comment]
This is most odd - I can only think it is something that your hosting provider is doing to cause it to drop the connection every 25 seconds... certainly there is no such timeout in the code that I know of.

**Comment by adawson-netafy** [comment]
Interesting. In this case, I am running Node-RED on Google Kubernetes Engine. I will move my NR Map server to a consistent host VM on Google Compute and see if that resolves the issue.

**Comment by adawson-netafy** [comment]
I ended up figuring out the solution here - For people hosting Node-RED on GKE Kubernetes, you need to follow the steps here- https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#1.16-gke.3+ to change from the default 30-second refresh.

You must create a "BackendConfig" object and attach it to the Node-RED service, and within the BackendConfig object, set the timeout limit to be higher than 30 seconds. 30 seconds is the default setting for a refresh if no BackendConfig is set up. This only really affects you if you're using Node-RED Map or Dashboard.

**Comment by dceejay** [comment]
Interesting... wonder why they do that ? but hey - glad you fixed it
