### ISSUE TITLE
Overlay Geojson clickable false doesn't work

### ISSUE THREAD

**Issue by smallf00t** [dceejay/RedMap#186]
Hi,
i v got version 2.22.2 of wordlmap when i send this command the clickable command seems not working what s wrong me or ?
Thanks  
![2021-12-04_08h56_22](https://user-images.githubusercontent.com/28515330/144702355-a3bec9f4-1a1e-4c2c-bf21-e95dc9364d00.png)

`[
    {
        "id": "c6645c9f89447cf4",
        "type": "function",
        "z": "b75cbff2f2508227",
        "name": "Add Overlay geoJson",
        "func": "var geojson = {\n  \"type\": \"FeatureCollection\",\n  \"features\": [\n    {\n      \"type\": \"Feature\",\n      \"properties\": {},\n      \"geometry\": {\n        \"type\": \"Polygon\",\n        \"coordinates\": [\n          [\n            [\n              1.84844970703125,\n              48.61112192003074\n            ],\n            [\n              2.70263671875,\n              48.61112192003074\n            ],\n            [\n              2.70263671875,\n              48.982019588328214\n            ],\n            [\n              1.84844970703125,\n              48.982019588328214\n            ],\n            [\n              1.84844970703125,\n              48.61112192003074\n            ]\n          ]\n        ]\n      }\n    }\n  ]\n}\nmsg.payload = {command:{map:{\n    \"overlay\": \"test\",\n    \"geojson\": geojson,\n    \"opt\": {\"color\":\"black\",\n    \"weight\": 2,\n    \"fillColor\":\"#0000FF\",\n    \"fillOpacity\": 0.0},\n    \"fit\": false ,\n    \"clickable\": false\n}}};\n\n\n\nreturn msg;\n\n",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 1560,
        "y": 460,
        "wires": [
            [
                "c0fd7c30bf08f752"
            ]
        ]
    },
    {
        "id": "61464ad6a17c0d4e",
        "type": "inject",
        "z": "b75cbff2f2508227",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 1270,
        "y": 460,
        "wires": [
            [
                "c6645c9f89447cf4"
            ]
        ]
    },
    {
        "id": "c0fd7c30bf08f752",
        "type": "worldmap",
        "z": "b75cbff2f2508227",
        "name": "",
        "lat": "48.8410",
        "lon": "2.2794",
        "zoom": "10",
        "layer": "OSMC",
        "cluster": "",
        "maxage": "",
        "usermenu": "show",
        "layers": "show",
        "panit": "false",
        "panlock": "false",
        "zoomlock": "false",
        "hiderightclick": "false",
        "coords": "deg",
        "showgrid": "true",
        "allowFileDrop": "false",
        "path": "/worldmap",
        "overlist": "RA,AC",
        "maplist": "OSMC",
        "mapname": "",
        "mapurl": "",
        "mapopt": "",
        "mapwms": false,
        "x": 1880,
        "y": 460,
        "wires": []
    }
]`
[worldmap.txt](https://github.com/dceejay/RedMap/files/7653578/worldmap.txt)

**Comment by dceejay** [comment]
Hi, yes slight confusion there... by clickable it means do or do not send a click action (clickgeo event) back to a worldmap-in node - but yes - It would be tidier if it didn't show a popup if it was empty - so I'll fix that.

**Comment by dceejay** [comment]
Empty popup removed in v2.23.0
