### ISSUE TITLE
Hide or customize "Node-RED Map All The Things" Header

### ISSUE THREAD

**Issue by adawson-netafy** [dceejay/RedMap#187]
This is most likely more for a GitHub "discussion" vs an Issue, but is there a way to add an option to remove the "map all the things" and node-red logo? Option to hide and option to add your own logo and text would be awesome.

I have not contributed to any open source in the past but I use Node-RED a lot so if there's a way for me to help code/contribute on this let me know.

**Comment by dceejay** [comment]
Hi, If you just want to change the name - set the node Name to whatever you want....
![image](https://user-images.githubusercontent.com/5375409/144713334-9f4dca3e-6b56-4f56-bb48-3351eb031161.png)
![image](https://user-images.githubusercontent.com/5375409/144713346-29e19361-e4ca-4fd3-aa46-255706a63399.png)

If you want t remove the bar completely the easiest way is to embed the map into your own webpage as an iframe and it will not be shown.

**Comment by smallf00t** [comment]
or in 2.22.2
msg.payload = {command:{"toptitle":"text you want"}}
return msg;

**Comment by dceejay** [comment]
@smallf00t  - Happy to consider a Pull request like that if you like...

**Comment by smallf00t** [comment]
@dceejay how can i "pull request" i m not familiar with github :(

**Comment by dceejay** [comment]
OK - slightly invloved...  but this is a good overview
https://opensource.com/article/19/7/create-pull-request-github

As it's a "small" change I'm happy to do it - but likewise if you want to use it as a learning exercise please go ahead, just let me know.

**Comment by smallf00t** [comment]
@dceejay thanks for this one please do it, promise il will learn

**Comment by dceejay** [comment]
Thanks for PR - closing this issue now

**Comment by dceejay** [comment]
Published as v2.23.0
