### ISSUE TITLE
Layer Menu on Map - Allow for Sorting Alphabetically

### ISSUE THREAD

**Issue by adawson-netafy** [dceejay/RedMap#189]
I have a map with many layers on it, and it would be amazing if the layer selection menu had an option to sort the menu alphabetically by default. It seems to randomly sort the layers which make it hard to visually organize when working with multiple layers

Example of non-sorted layer menu:
<img width="236" alt="2021-12-07_14-48-31" src="https://user-images.githubusercontent.com/63602127/145097464-88e953c2-8a7b-4f20-92f3-5787f5c68a2b.png">

**Comment by dceejay** [comment]
I think it is just an array so they are in the order they are added.

**Comment by adawson-netafy** [comment]
I did solve the issue with a Sort node at the end of my flow that deposits the data in the JSON DB. Thank you

<img width="510" alt="2021-12-08_11-04-43" src="https://user-images.githubusercontent.com/63602127/145241657-bbd762ad-474e-4ed5-b880-7a3c00e23921.png">

I do think the idea of "sub-layers" and layer groupings like folders would be a cool additional feature. So you can check a layer group and turn on/off all sub-layers.
