### ISSUE TITLE
msg.payload.layerDisabled

### ISSUE THREAD

**Issue by adawson-netafy** [dceejay/RedMap#190]
It would be great to have a layer option like msg.payload.layerDisabled, that would keep the layer disabled when the map loads. 

That way you can have the normal msg.payload.layer enabled by default, and msg.payload.layerDisabled would be a layer that is there but not enabled.

**Comment by dceejay** [comment]
Not sure what you mean. Which layer are you talking about ? you need to load a base layer. And there is msg.command.hidelayer to hide layers

**Comment by adawson-netafy** [comment]
Yes, this was my bad. I did not read the README and see the command section.
