### ISSUE TITLE
The ui_worldmap node displays more overlays than defined in the configuration

### ISSUE THREAD

**Issue by oliv3** [dceejay/RedMap#191]
Hi, in a ui_worldmap node (v2.23.0), I set the configuration to display the "heatmap" overlay only. But, the layers button still shows "drawing", "countries", "day/night" and "rainfall".

**Comment by dceejay** [comment]
I'm not seeing this issue. Have you refreshed / reloaded the browser since changing the option ?

(I am seeing an issue of not saving the custom layer if that is selected as the default map.- but that isn't this.)

**Comment by oliv3** [comment]
I reloaded the page and cleared the browser's cache

**Comment by dceejay** [comment]
and ? they are still there ? or now removed ?
which version of the node do you have ? and which version of Node-RED and node.js.

**Comment by oliv3** [comment]
Sorry - yes, there's still there.

- NodeRED 2.1.3 (from node-red docker)
- node-red-contrib-web-worldmap 2.23.1
- Firefox 91.4.0esr

**Comment by oliv3** [comment]
It also happens with the plain `worldmap` node: selecting only the `heatmap` overlay
![image](https://user-images.githubusercontent.com/84910/146583287-81c5a86d-c59b-4d8d-b3f6-3d1b2e55a46d.png)
results in
![image](https://user-images.githubusercontent.com/84910/146583341-23ece2b2-0f6d-41ab-a3a0-266ddf174d97.png)

**Comment by dceejay** [comment]
Weird - on FF 95 I get
![image](https://user-images.githubusercontent.com/5375409/146583909-0835b831-a558-45ac-aa53-32dce0351b45.png)

I deploy... then refresh map browser page.

**Comment by oliv3** [comment]
That's what i also did.. weird

**Comment by oliv3** [comment]
I tried hiding the layer button then enabling it again, same result

**Comment by dceejay** [comment]
and there is nothing in the browser console log ? (I wouldn't expect anything as it doesn't log anything relevant).

What hardware are you running Node-RED on ?

**Comment by oliv3** [comment]
I don't see anything special in the logs if i change the configuration then re-deploy. Node-RED is running in docker on my laptop, so nothing fancy.

**Comment by dceejay** [comment]
Ok I will continue to keep an eye out for it.

**Comment by oliv3** [comment]
It's not that a serious bug, can live with it. But I expected to get the same behavior as you :)

**Comment by dceejay** [comment]
Think I have found it - please try v2.23.3

**Comment by oliv3** [comment]
Is it commited/published ?

**Comment by dceejay** [comment]
Yes. Should be in flows library

**Comment by oliv3** [comment]
Hi, I just upgraded - works like a charm now ! Thanks.

**Comment by oliv3** [comment]
Little type in the changelog: "Fix initial `laod` of maps"
