### ISSUE TITLE
ui-worldmap not available

### ISSUE THREAD

**Issue by ckanoab** [dceejay/RedMap#193]
When I install `node-red-contrib-web-worldmap` the `ui-worldmap` module is disabled and missing from the sidebar. Looking in the browser console for errors, I see a 404 failed call from vendor.js to `<domain>/-ui-worldmap`. I'm running nodered at a subdirectory `/nodered` using the `httpRoot` directive in settings.js, so that call should be to `<domain>/nodered/-ui-worldmap`. If I browse to `<domain>/nodered/-ui-worldmap` I get a 200 response with `true` as the data. I tried using Fiddler to break on that request and changed it to `/nodered/-ui-worldmap` and it installed successfully and is available in the side menu.

**Comment by ckanoab** [comment]
Testing further, despite tricking it into installing, it doesn't function on the dashboard. 404 not found ☹️

**Comment by dceejay** [comment]
closed by fixes in v2.24.0

**Comment by ckanoab** [comment]
Thank you!
