### ISSUE TITLE
ui_worldmap: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kapet** [dceejay/RedMap#194]
Thanks for implementing "resend markers for late joiners", much appreciated!

But with this release I'm seeing a weird error that I'm struggling to find the root cause for.

Simple flow: A geolocation from mqtt/owntracks is fed into a ui_worldmap node.
Now whenever a location is updated and sent to the ui_worldmap node, it triggers an exception.

Catching the exception, this is the error:
{"message":"RangeError: Maximum call stack size exceeded", "source":{"id":"98f2b8aca6c0b21a", "type":"ui_worldmap", "count":1},
"stack":"RangeError: Maximum call stack size exceeded\n    at hasBinary (/home/node-red/.node-red/node_modules/socket.io-parser/dist/is-binary.js:28:19)\n    at hasBinary (/home/node-red/.node-red/node_modules/socket.io-parser/dist/is-binary.js:49:63)\n    at hasBinary (/home/node-red/.node-red/node_modules/socket.io-parser/dist/is-binary.js:49:63)\n    at hasBinary (/home/node-red/.node-red/node_modules/socket.io-parser/dist/is-binary.js:49:63)\n    at hasBinary (/home/node-red/.node-red/node_modules/socket.io-parser/dist/is-binary.js:49:63)\n    at hasBinary (/home/node-red/.node-red/node_modules/socket.io-parser/dist/is-binary.js:49:63)\n    at hasBinary (/home/node-red/.node-red/node_modules/socket.io-parser/dist/is-binary.js:49:63)\n    at hasBinary (/home/node-red/.node-red/node_modules/socket.io-parser/dist/is-binary.js:49:63)\n    at hasBinary (/home/node-red/.node-red/node_modules/socket.io-parser/dist/is-binary.js:49:63)\n    at hasBinary (/home/node-red/.node-red/node_modules/socket.io-parser/..."}

Interestingly, AFAICT the worldmap module does not even have a dependency on socket.io, but the dashboard has.

Is it possible that the dashboard gets confused by the data in allPoints? As a test I deleted payload.name in the data I send to ui_worldmap so that it does not get stored, and this made the exception go away.

**Comment by dceejay** [comment]
Darn pass by ref feedback error... 
fixed in v2.27.1
