### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by scargill** [dceejay/RedMap#2]
JNot working for me - I have the latest of everything - Jessie, node, node-red on a Raspberry Pi - lots of nodes - just installed this - the map comes up a treat but no matter what I put into the payload as an inject - makes no difference whatsoever - I always end up with the map pointing somewhere in the south of England.

I'm putting in a string in an inject node into the worldmap node.... injecting - nothing - map stays the same even after a refresh of the page. What if anything am I doing wrong??

Pete.

**Comment by dceejay** [comment]
working fine... resolved via mailing list.
No issue.
