### ISSUE TITLE
Historic Os layers

### ISSUE THREAD

**Issue by Phil-b-l** [dceejay/RedMap#201]
In node red the historic OS layers from the NLS now come up with a message “NLS maps upgraded:  maptiler.com/NLS I’m not sure how to go about sorting it this is a link to what appears https://nls.tileserver.com/

**Comment by dceejay** [comment]
Thanks for reporting. Will see if there is any way to recover.

**Comment by dceejay** [comment]
Sadly no way to fix this easily for everyone - they have moved them behind an API key so they can track usage. 
 You can use the custom map provider option with a url like

```
https://api.maptiler.com/tiles/uk-osgb25k1937/{z}/{x}/{y}.jpg?key={your-api-key-here}

and an options object like
{
    attribution: 'Historical Maps Layer, from <a href="https://maps.nls.uk/projects/api/">NLS Maps</a>',
    bounds: [[49.6, -12], [61.7, 3]],
    crossOrigin: true,
    minZoom:1, maxZoom:18,
    subdomains: '0123'
}
```

**Comment by Phil-b-l** [comment]
Thank you,
I’ll have a play and get an API though I will be fumbling about in the dark a bit as I really don’t know my way around this stuff. It is a way to learn though I suppose.

Thanks again for the response and for your effort at creating the whole thing.

Kind regards

Phil

**Comment by dceejay** [comment]
Hi - I set my node up like this
<img width="842" alt="image" src="https://user-images.githubusercontent.com/5375409/186193940-76d4717b-7df3-478d-a74a-79fa7703769a.png">
Once you login into their website https://cloud.maptiler.com/tiles/uk-osgb63k1885/leaflet
then you can cut and paste the info from the leaflet examples.

**Comment by Phil-b-l** [comment]
Brilliant, thank you so much

Phil
