### ISSUE TITLE
Feature request: map follow mobile user

### ISSUE THREAD

**Issue by christian-skjetne** [dceejay/RedMap#202]
Hi, thanks for the awesome node. 
One feature I would love is the ability to toggle the "Follow me" function in "continuous mode"
I.E. when i move, the map moves with me. I think it would be a great feature on mobile. And should be rather easy to implements as well.
Also, if the map is moved manually a certain distance, it could toggle off again.

**Comment by dceejay** [comment]
You can already set the map into auto-pan mode...

**Comment by christian-skjetne** [comment]
Unless I'm misunderstanding something, the autopan feature will pan the view to any new (or updated) marker. What I'm talking about is autopan to the users actual location (similar to pressing the "locate me" button on the left of the map, only continuously updating as the user moves around with their mobile phone) 
Or in other words, something like this: `if(followMode) setInterval(map.locate({setView:true, maxZoom:16}, 1000);`

If there was a way to get continuous location updates from the users gps as a map event (as in "action": "point", only updating every second or so), I guess it could solved using the lat/lon commands. But I don't see a way to get that info without putting the map in an iframe and polling for position updates in the parent site. It would also be way more hassle than just doing it on the client side.

**Comment by dceejay** [comment]
Ah right... ok fully understand now. And actually I see a built in watch option - https://leafletjs.com/reference.html#locate-options ...  my only thoughts are 
    a) how stable is the location ? will the map bounce around a lot ?  
    b) As it says - if it gets an error it will zoom to whole world...  not pretty...

**Comment by christian-skjetne** [comment]
I've done some testing and it seems to work pretty well. With some caveats.

a) location is stable and works as expected. even after i move inside with no gps coverage.
b) Did not see any issues with this. though I'm not sure how to trigger an error. Tried to deny location access, works fine. tried to move to a location with no gps coverage, also works fine. I even tried to trigger an error in the chrome console using the "sensor"-tools, and while it gave the wrong location, nothing catastrophic happened.
c) the maxZoom is probably the most annoying thing. if not set it defaults to max zoom. The simplest solution I found was to use setView:false in the map.locate options, and just use map.panTo(e.latlng) in the onLocationFound callback.
d) in a perfect world it would be nice to be able to choose a marker (imagine an icon like a car or an arrow or something, since we get the heading it would look pretty cool) but even just drawing the same circle/polygon that is currently used is a fine start. The current "loctate me" onLocationFound code should probably be updated anyway since clicking the button more than once does not move the circle, but draws a new one every time. Not sure that is the intended behaviour.

PS: It is super easy to test the code without using an actual phone by enabling the "sensors"-tab in the chrome devtools.


my changes (apologize for my terrible test code):
```javascript
var followMode = false;
var locationSymbol;
var headingSymbol;

function onLocationFound(e) {
    if(followMode) map.panTo(e.latlng);
    var radius = e.accuracy;
    if(!locationSymbol) {
        locationSymbol = L.circle(map.getCenter(), radius, {color:"cyan", weight:4, opacity:0.8, fill:false, clickable:false});
        locationSymbol.addTo(map);
    }
    else {
        locationSymbol.setLatLng(e.latlng);
    }
    if (e.hasOwnProperty("heading")) {
        var lengthAsDegrees = e.speed * 60 / 110540;
        var ya = e.latlng.lat + Math.sin((90-e.heading)/180*Math.PI)*lengthAsDegrees*Math.cos(e.latlng.lng/180*Math.PI);
        var xa = e.latlng.lng + Math.cos((90-e.heading)/180*Math.PI)*lengthAsDegrees;
        var lla = new L.LatLng(ya,xa);
        if(!headingSymbol) {
            headingSymbol = L.polygon([ e.latlng, lla ], {color:"cyan", weight:3, opacity:0.5, clickable:false});
            headingSymbol.addTo(map);
        }
        else {
            headingSymbol.setLatLngs([ e.latlng, lla ]);
        }
    }
    ws.send(JSON.stringify({action:"point", lat:e.latlng.lat.toFixed(5), lon:e.latlng.lng.toFixed(5), point:"self", hdg:e.heading, speed:(e.speed*3.6 || undefined)}));
}
```

and where the "locacte me" button is added to the map, I just added another "track me" button.
```javascript
    // Add the track my position button
    trackMeButton = L.easyButton({
            states: [{
                    stateName: 'track-on',                           // name the state
                    icon:      'fa-solid fa-location-arrow',     // and define its properties
                    title:     'Disable tracking',                     // like its title
                    onClick: function(btn, map) {               // and its callbacK
                        btn.state('track-off');                       // change state on click!
                        followMode = false;
                        map.locate({setView:false, watch:followMode, enableHighAccuracy:true,maxZoom:16});
                    }
                }, {
                    stateName: 'track-off',
                    icon:      'fa-thin fa-location-arrow',      //<-- could not get fa icon styles to work with easyButton :(
                    title:     'Enable tracking',
                    onClick: function(btn, map) {
                        btn.state('track-on');
                        followMode = true;
                        map.locate({setView:false, watch:followMode, enableHighAccuracy:true,maxZoom:16});
                    }
            }]
        });
    trackMeButton.state('track-off');
    trackMeButton.addTo(map);
```

**Comment by dceejay** [comment]
so thinking out loud... rather than a follow mode boolean - if it was an object with properties like  icon, iconColor, accuracy (boolean) that can be set my a command message ? 
(and replace the existing button completely (but defaulted so it looked like existing... (no icon - just the ring)

**Comment by christian-skjetne** [comment]
That sounds like a pretty good solution to me. Should give tons of flexibility for "power users" while still being easy to use for "regular" users.

**Comment by christian-skjetne** [comment]
Sounds like a pretty good solution to me. It would give great flexibility for "power users" while still being easy to use for "regular users".

**Comment by dceejay** [comment]
OK - version 2.29.0 published - added a trackme command that accepts a boolean or an object - and made the button into a toggle.

example flow

```
[{"id":"754cd97ba3ee94b8","type":"inject","z":"1f7f9c4efc1c5c0a","name":"Track Me","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"command\":{\"trackme\":true}}","payloadType":"json","x":240,"y":240,"wires":[["9e95310b7d554465"]]},{"id":"ad8ebce727716855","type":"inject","z":"1f7f9c4efc1c5c0a","name":"Stop tracking","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"command\":{\"trackme\":false}}","payloadType":"json","x":250,"y":195,"wires":[["9e95310b7d554465"]]},{"id":"9374ac8de4488673","type":"inject","z":"1f7f9c4efc1c5c0a","name":"Track me with icon color etc","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"command\":{\"trackme\":{\"name\":\"Fred\",\"layer\":\"tracking\",\"icon\":\"car\",\"iconColor\":\"blue\"}}}","payloadType":"json","x":300,"y":285,"wires":[["9e95310b7d554465"]]},{"id":"9e95310b7d554465","type":"worldmap","z":"1f7f9c4efc1c5c0a","name":"","lat":"","lon":"","zoom":"","layer":"","cluster":"","maxage":"","usermenu":"show","layers":"show","panit":"false","panlock":"false","zoomlock":"false","hiderightclick":"false","coords":"false","showgrid":"false","allowFileDrop":"false","path":"/worldmap","overlist":"DR,CO,RA,DN,HM","maplist":"OSMG,OSMC,EsriC,EsriS,EsriT,EsriDG,UKOS","mapname":"","mapurl":"","mapopt":"","mapwms":false,"x":540,"y":240,"wires":[]}]
```
