### ISSUE TITLE
Example not working without additional configuration (url rewrite)

### ISSUE THREAD

**Issue by jose1711** [dceejay/RedMap#204]
I installed worldmap and imported 'Map in Dashboard' example into my workflow, making no other changes, just hit deploy. The map endpoint is served (in my case it's https://server.tld/nodered/worldmap but there was nothing on the dashboard since the request went to https://server.tld/worldmap which ended up as 404. To overcome this I added a rewrite rule to my `nginx` configuration:
```
 location / {
   rewrite ^/worldmap/$ https://$host/nodered/worldmap/ permanent;
 }
```
Now I wonder if there's something flawed with my setup or there is an option to fix the issue just using NodeRED configuration.

**Comment by dceejay** [comment]
If you are using nginx to rewrite the paths then I'm not sure there is anything worldmap can do - as it will just assume what it gets from Node-RED is correct, so will use the default path.
