### ISSUE TITLE
[question] using MVT maps with 2D RedMap?

### ISSUE THREAD

**Issue by mhaberler** [dceejay/RedMap#207]
I would like to use vector maps (MVT) with a 2D map setup

I see the following options:
- use the mapboxgl code in "2D mode" (is that possible?)
- tack on https://github.com/palantir/Leaflet.MapboxVectorTile to Leaflet

I can give the second option a try towards a PR but am unconvinced of the quality of Leaflet MVT add-ons so far

what would would you recommend?

thanks in advance, 
Michael

**Comment by dceejay** [comment]
I can't really recommend either as I have never come across this before... so you are several steps ahead of me I'm afraid. I certainly don't mind a Pull Request if you don't mind

**Comment by mhaberler** [comment]
fair enough, will give it a try - thanks!

**Comment by dceejay** [comment]
Closing as we now support vector pmtiles files.
