### ISSUE TITLE
Compatibility with node-red 1.0.6

### ISSUE THREAD

**Issue by mrdvt92** [dceejay/RedMap#208]
node-red 1.0.6
node v16.17.0

I get this error when trying to open the "edit worldmap node" properties window in the flow.

Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at HTMLInputElement.<anonymous> (<anonymous>:217:35)
    at HTMLInputElement.dispatch (vendor.js:2:42571)
    at v.handle (vendor.js:2:40572)
    at Object.trigger (vendor.js:2:70627)
    at HTMLInputElement.<anonymous> (vendor.js:2:71222)
    at Function.each (vendor.js:2:2777)
    at e.fn.init.each (vendor.js:2:1419)
    at e.fn.init.trigger (vendor.js:2:71198)
    at r (red.min.js:16:369202)
    at E (red.min.js:16:369601)

Current work around is to open a second node and then they both pop up and then cancel the second one.

![image](https://user-images.githubusercontent.com/5374501/197888085-50d40a21-91b7-4f44-a924-be1b84a8139d.png)

**Comment by dceejay** [comment]
As we are now on Node-RED 3.x I'm not realistically going to look at this.

**Comment by mrdvt92** [comment]
> As we are now on Node-RED 3.x I'm not realistically going to look at this.

I'm not sure that it only impacts 1.0.6.   Based on googling the issue is from

https://github.com/dceejay/RedMap/blob/6f28ffc91ee20095260719bc6ec810c48567508d/worldmap.html#L541

And this is a trivial fix.

```
-                        if (value.indexOf("MB3d") > -1) {
+                        if (value && value.indexOf("MB3d") > -1) {
```

**Comment by mrdvt92** [comment]
Fails testing on 2.30.3 but now at line. 

```
                            mshort = mlist.filter(e => value.indexOf(e.value)!==-1);
```

I wish I understood why "value" is undefined in my browser.

**Comment by dceejay** [comment]
feel free to raise a Pull Request if you have 5 mins to fix it.
