### ISSUE TITLE
KML polygon fill color is not considered

### ISSUE THREAD

**Issue by VA2XJM** [dceejay/RedMap#211]
I use some KML files that I wish to display on a map. Problem, is that each KML file includes multiple polygons with linked style.

Loaded into multiple software, the color coding is respected. When injecting the KML into worldmap all polygons are properly displayed but they are all the same color (blue).

I can provide complete files if needed. 

So I was wondering if the KML style is taken into consideration or if I need to provide fillcolor and opacity somehow for each one.

**Comment by dceejay** [comment]
Good question - I can't recall off the top of my head...  but yes please any sample files would help greatly.

**Comment by VA2XJM** [comment]
[demo-kml.zip](https://github.com/dceejay/RedMap/files/9974268/demo-kml.zip)
Here we go. Both KML zipped since .kml is not accepted.

Thanks for you reply @dceejay. Really appreciated.

**Comment by dceejay** [comment]
I have updated/changed the KML handling library - seems to be better now - give it a whirl - v2.31.0
