### ISSUE TITLE
feedback function

### ISSUE THREAD

**Issue by zafrirron** [dceejay/RedMap#212]
Hi @dceejay 

Any reason that context menu "feedback" works different for map popup and marker popup?

 ```
var feedback = function(n,v,a,c) {
    if (v === "$form") { v = form; }
    if (markers[n]) {
        //var fp = markers[n]._latlng;
        // ws.send(JSON.stringify({action:a||"feedback", name:n, value:v, layer:markers[n].lay, lat:fp.lat, lon:fp.lng}));
        var fb = allData[n];
        fb.action = a || "feedback";
        ws.send(JSON.stringify(fb));
    }
    else {
        if (n === undefined) { n = "map"; }
        ws.send(JSON.stringify({action:a||"feedback", name:n, value:v, lat:rclk.lat, lon:rclk.lng}));
    }
    if (c === true) { map.closePopup(); }
} 
```
why sending back all marker data to the server? (this data was send to the map from the server no real need to reply it back)
why preventing from using the same feedback option as the map popup? (a marker HTML popup will not return the value property using this code) 

(just want to make sure for the reason, before submitting a PR.)

Regards

**Comment by dceejay** [comment]
Apologies I can't recall the reason... would need to check the commit date and check issues around then. There must have been some reason to send all back. Am away for a couple of days so can't dig in until then.

**Comment by mrdvt92** [comment]
Could this be due to the fact that worldmap is inherently multi-user whereas most dashboard nodes are single user/shared across all users?

**Comment by zafrirron** [comment]
I'm less worried about sending the back ALL marker data as part of the feedback function (looks like a debug stage), more concerned about the ability to have the option to send "normal" feedback object the includes my own marker actions (currently not implemented for marker but works for the map only), I guess all map objects (including drawing entities) should have the same feedback function option.

**Comment by dceejay** [comment]
Both legs of the if statement add the action property that is passed into the feedback call.... so what is missing ? (I'm obviously not quite "getting it"...)

**Comment by dceejay** [comment]
Ah - I see the value isn't there so yes can certainly add that.

**Comment by zafrirron** [comment]
The "first leg" of the if sending the action is commented out...
