### ISSUE TITLE
Map drawing

### ISSUE THREAD

**Issue by zafrirron** [dceejay/RedMap#213]
![image](https://user-images.githubusercontent.com/3098954/202876143-7da213f4-b81c-4107-8842-2e4efd545908.png)

Could not see the "type" attribute propagates as part of the event...(also could not find trace in the code for it)
anyone got it working?

thanks

**Comment by dceejay** [comment]
Sorry - not sure what/where you mean ? propagate when ? do you have a small example flow to show the issue ?

**Comment by zafrirron** [comment]
According to the documentation, 
The property "type" (shape type) should be part of the event coming back from the map to the flow when a map drawing entity created. I could not get the property "type" as part of the event (I do get all other properties).  
please take a look  the event message object content I got:
![image](https://user-images.githubusercontent.com/3098954/203219350-e871cafa-ec68-4811-8f6d-9b2c83905811.png)
