### ISSUE TITLE
Great Circle Lines - Still problematic

### ISSUE THREAD

**Issue by JackHenry99** [dceejay/RedMap#217]
Hi dceejay (again)

I've downloaded the new version of World Map and restarted the Pi and Node-Red. The issue has not been fixed. See images

<img width="1142" alt="Screen Shot 2022-12-01 at 15 57 16" src="https://user-images.githubusercontent.com/13172326/204973164-2e63efbe-2987-49af-ad1c-e51267398d38.png">

<img width="1144" alt="Screen Shot 2022-12-01 at 15 57 23" src="https://user-images.githubusercontent.com/13172326/204973250-15d08682-6e36-4729-aec7-034413574de6.png">

**Comment by dceejay** [comment]
OK - so we have a choice... :-)... What it is doing now is strictly more correct in that it is plotting the line and marker on what leaflet defines as -180 to +180 degrees longitude... so when it crosses the antimeridian it "jumps" to the -180 and continues drawing from there... 

But I can see that is not what you want - so the other solution is to revert to the way it was and for you to change the lat lng of the marker to be +237.71 etc instead of -122.28 - as that then moves it out of the +/-180 but does stick it on the end of the line...

<img width="256" alt="image" src="https://user-images.githubusercontent.com/5375409/205056086-c8932aea-b144-4aef-94d6-02bd74df8582.png">

**Comment by JackHenry99** [comment]
I have no control on the lat/long of the marker as it gets dynamically brought in from an outside site when a call is logged..

I would have thought that, having a map centered on a specific location (in this case near Adelaide SA), that a location east of that, should plot for an easterly direction on the map, irrespective of the date line.  Not split the event into two separate plot lines.

**Comment by kd9lsv** [comment]
@dceejay  is there an easy way to duplicate a given map, but offset it 360°. if so that would just solve our solution and allow for the map to look pretty across the dateline while also being "more correct".

**Comment by dceejay** [comment]
@JackHenry99 - of course you have control... you can add a node between the api call and the map to check the marker longitude and if necessary add 360 to it.
@kd9lsv - yes - as just said add a function node to manipulate the longitude values before you send to the map based on whatever criteria you deem necessary.

**Comment by JackHenry99** [comment]
Dave
I'm a Node-Red relative newcomer. What might that actually look like in a function??
John

**Comment by dceejay** [comment]
msybe something like
```
if (msg.payload.lon < 0) { msg.payload.lon += 360; }
return msg;
```

**Comment by JackHenry99** [comment]
That's what I thought before I asked the question. But your version doesn't work either. I get the same msg.payload.lon out that goes in. (plus a lot less data) In case you had a typo, I tried it without the = after the + and with the semi colon outside the bracket. In all cases, the lon remains the same. The 360 doesn't get added to it.

**Comment by JackHenry99** [comment]
This is what goes in. And below that is what comes out.

{"payload":{"name":"KM9G","lat":"45.57095","lon":"-92.48113","ttl":"80000","op":"VK5Y","band":"20M","mode":"SSB","isrunqso":"0","exchange":" ","section":"","distance_km":15648,"distance_miles":9723,"iconColor":"#FF0000","layer":"20M","ismultiplier":0,"greatcircle":[[-35.05,138.08],[45.570945,-92.48113]]},"fromip":"10.1.1.5:65087","ip":"10.1.1.5","port":65087,"_msgid":"a1bef36410b474e1","qsotype":"qso","_event":"node:677d263669792c2d","original":{"app":["N1MM"],"contestname":["KALBAR"],"contestnr":["1"],"timestamp":["2022-12-03 22:27:30"],"mycall":["VK5Y"],"band":["14"],"rxfreq":["1415900"],"txfreq":["1415900"],"operator":["VK5Y"],"mode":["USB"],"call":["KM9G"],"countryprefix":["K"],"wpxprefix":["KM9"],"stationprefix":["VK5Y"],"continent":["NA"],"snt":["59"],"sntnr":["14"],"rcv":["59"],"rcvnr":["1"],"gridsquare":[""],"exchange1":[""],"section":[""],"comment":[""],"qth":[""],"name":[""],"power":[""],"misctext":[""],"zone":["4"],"prec":[""],"ck":["0"],"ismultiplier1":["0"],"ismultiplier2":["0"],"ismultiplier3":["0"],"points":["0"],"radionr":["1"],"run1run2":["1"],"RoverLocation":[""],"RadioInterfaced":["1"],"NetworkedCompNr":["0"],"IsOriginal":["True"],"NetBiosName":["WINDOWS-MACHINE"],"IsRunQSO":["0"],"StationName":["WINDOWS-MACHINE"],"ID":["b3de6fd77e05432ab1323e3ed2045031"],"IsClaimedQso":["1"],"oldtimestamp":["2022-12-03 22:27:30"],"oldcall":["KM9G"]},"qrzkey":"c09bfeb459548c04f81a4541951fc05a","statusCode":200,"headers":{"date":"Sat, 03 Dec 2022 22:27:28 GMT","server":"Apache/2.4.29 (Ubuntu)","expires":"Fri, 02 Dec 2022 22:27:28 GMT","vary":"Accept-Encoding","access-control-allow-origin":"*","connection":"close","transfer-encoding":"chunked","content-type":"text/xml; charset=utf-8","x-node-red-request-node":"39aab004"},"responseUrl":"https://xmldata.qrz.com/xml/current/?s=c09bfeb459548c04f81a4541951fc05a;callsign=KM9G","redirectList":[],"retry":0,"QRZDatabase":{"$":{"version":"1.36","xmlns":"http://xmldata.qrz.com"},"Callsign":[{"call":["KM9G"],"aliases":["KD9FSQ"],"dxcc":["291"],"fname":["Steve E"],"name":["McGrane"],"addr1":["PO BOX 101"],"addr2":["Luck"],"state":["WI"],"zip":["54853"],"country":["United States"],"lat":["45.570945"],"lon":["-92.481130"],"grid":["EN35sn"],"county":["Polk"],"ccode":["271"],"fips":["55095"],"land":["United States"],"efdate":["2018-12-21"],"expdate":["2028-12-21"],"class":["E"],"codes":["HVIE"],"email":["temporarilyoffline@gmail.com"],"u_views":["21331"],"bio":["1209"],"biodate":["2019-11-21 23:56:13"],"image":["https://cdn-xml.qrz.com/g/km9g/Profile.png"],"imageinfo":["333:235:119862"],"moddate":["2022-04-16 21:51:27"],"MSA":["0000"],"AreaCode":["715"],"TimeZone":["Central"],"GMTOffset":["-6"],"DST":["Y"],"lotw":["1"],"geoloc":["user"],"name_fmt":["Steve E McGrane"]}],"Session":[{"Key":["c09bfeb459548c04f81a4541951fc05a"],"Count":["8590"],"SubExp":["Fri Apr 21 07:11:43 2023"],"GMTime":["Sat Dec  3 22:27:28 2022"],"Remark":["cpu: 0.021s"]}]}}

****************************************************

{"name":"KM9G","lat":"45.57095","lon":"-92.48113","ttl":"80000","op":"VK5Y","band":"20M","mode":"SSB","isrunqso":"0","exchange":" ","section":"","distance_km":15648,"distance_miles":9723,"iconColor":"#FF0000","layer":"20M","ismultiplier":0,"greatcircle":[[-35.05,138.08],[45.570945,-92.48113]]}

**Comment by JackHenry99** [comment]
Ok, a bit of progress. i needed to add a Change node to convert the lon from a string to a number for the addition to work. That puts the pin on the 'correct' map. But the Great Circle line still splits (at the equator it seems) and the top half gets drawn on the 'other' map.  See images.

<img width="1094" alt="Screen Shot 2022-12-04 at 14 27 04" src="https://user-images.githubusercontent.com/13172326/205473975-b9ce3a98-b0e4-47be-af91-1a89c9500cf9.png">


<img width="1151" alt="Screen Shot 2022-12-04 at 14 27 28" src="https://user-images.githubusercontent.com/13172326/205473977-caf38572-2edc-4db9-a1a2-2d5979c82961.png">

**Comment by JackHenry99** [comment]
Also, if you look at the first image I posted when I opened the original query #216, you can see that one of the two lines does draw correctly across the dateline, but one doesn't. That was 2.31.1 (I think) Was the correctly drawn line an anomaly? Or did you change something in that version that inadvertently fixed the line draw issue (but not the pin drop)
