### ISSUE TITLE
deletion of marker from heat map?

### ISSUE THREAD

**Issue by devleaks** [dceejay/RedMap#218]
Hello,

Thank you for this very useful node-red plugin.

I could not find how a marker gets deleted from the heat map.

The heat map has no delete function (just add) but the markers is "just" an array of (lon, lat).
So removing a marker is removing it from the array of markers.
Maybe worldmap could keep the array and delete from it.
Leaflet.Heat always does a full redraw when a marker is added. So removing a marker could do the same.

Best regards,

Pierre

**Comment by dceejay** [comment]
The underlying library does not have this capability so it would need to be added. Ideally it would be a PR to the Leaflet.heat library - but that seems fairly inactive... so I'd be happy to look at a local pull request if you fancy having a go ?
As you say it looks like is already has the array so maybe extending the prototype to add the remove function is the way forward...

**Comment by devleaks** [comment]
Leaflet.heat has not changed for the last 7 years. Actually, it does not need to change. It has function
```
setLatLngs(latlngs)
```
to set an array of [(lat, lon)] ourselves. (Since in all cases it does a redraw() afterwards.)
So rather than adding points to leaflet.heat directly, may be you could add (and remove) points to an array you maintain yourself in world map and use setLatLngs( your_array ) on the heatmap each time it changes.
Just a suggestion.
I need it because I use heat map  to show traffic density over the last 20 minutes, so I need to "remove" points older than 20 minutes from the heat map.
Pierre

**Comment by dceejay** [comment]
as it already has the array, holding it again outside is just a waste.
added to version 2.32.0

**Comment by dceejay** [comment]
So... I have added delLatLng to remove a marker from the array...  but thinking about it - I'm not sure that is really what you want - as that only removes the marker at one specific lat,lng ... I'm guessing from what you said that actually you need to be able to replace the whole array based on time... none of which the current array logs - it just holds latlngs. As a marker moves over the 20 mins it may add lots of points to the array. This is not something I want to track inside the worldmap - so instead I could expose a command to  replace the whole array - and let you create and manage the array yourself, so you can prune it based on whatever criteria you wish ?

**Comment by devleaks** [comment]
Yes, providing a hook/relay to heatmap setLatLngs(latlngs) in worldmap would be perfect. I would indeed maintain my own array of coordinates and pass it to worldmap->heat map (I already do that, but I'm missing the integration to worldmap/heatmap.)
Many thanks.
Pierre

**Comment by dceejay** [comment]
OK - have pushed to git for you to test... - 
a payload like 
```
msg.payload = {
    "command": {
            "heatmap":[{"lat":51,"lng":1}]
    }
}
```
should do the necessary etc...  eg just send a blank array to clear it out is an easy test...
