### ISSUE TITLE
Using more than one map in a node-red instance

### ISSUE THREAD

**Issue by devleaks** [dceejay/RedMap#220]
Hello,

Building a dashboard and using ui_worldmap, I noticed that you cannot have more than one map in the dashboard. It this correct or did I miss something?

I would have like to have 2 maps in the dashboard, one "wide area map" (zoom 8) and a "focus map" (zoom 14) but the dashboard map does not behave as expected: data sent to one map appears on both, zoom is not preserved for the first map loaded, etc.

It this correct? Is it due to the fact that there is only one "web socket" channel beteewn node-red and the map? (and not one channel per map.)

P.

PS: To reproduce, just build a dashboard with 2 maps on 2 different groups (I used 2 full page groups). Load the dashbord. Sometimes, first map has zoom 8, sometimes has zoom 14...?! When switching maps, zoom is not preserve, etc.

**Comment by dceejay** [comment]
how have you set the endpoints ? as long as you configure different endpoints (eg /worldmap  and /worldmap2  ) then you should be able to address them independently.

**Comment by devleaks** [comment]
Ah! Thank you. That's the parameter I was missing. Works perfectly. Thank you.
