### ISSUE TITLE
deleted: true stopped working

### ISSUE THREAD

**Issue by svdasein** [dceejay/RedMap#222]
I don't think this is likely to be a "bug" - I'm just fishing for some guidance.

I have a nodered map that I built a few months ago that seems to no longer be processing deletion events properly.  What actually are you keying on when I do a delete?  Is that the precise lat/lon or is there more to it?

Browser is FF 102.0 (64-bit)

I did notice that in the js console in ff both the create and delete events I send end up with a "BAD DATA" message - not sure if that's related.  The create works fine regardless of the BAD DATA message.  Visually however the delete does nothing 'til I completely reload and refresh the page.

**Comment by dceejay** [comment]
the payload should just need the name and the deleted property eg  `{"name":"Dave", "deleted":true }`
Mayeb if you can share an example of thedate you are sending then I can comment further

**Comment by svdasein** [comment]
Hm - ok.  In my test case I see that the name string is identical in both messages, and that "deleted":true is set on the delete request:
create:
![image](https://user-images.githubusercontent.com/511777/213488304-d6726a92-516f-4b1e-819a-3be7d9893f56.png)
delete:
![image](https://user-images.githubusercontent.com/511777/213487998-6794f3ba-3328-4dd0-b260-e2e5b22a2b79.png)

The marks are simply not going away when I send the delete.  Any ideas?

**Comment by dceejay** [comment]
not easy to cut/paste and test with screenshots - so no not immediately.
You could try adding a `console.log(e.data)` right after the try line... and then another `console.log(data)` after the var data line - and start to see where it is failing.

**Comment by svdasein** [comment]
Sorry about the screen shots - I am obligated to not share "internal data" so I have to blur stuff.

I did a breakpoint on the JSON.parse(e.data) line and ran that line.  Here's what I'm seeing after that line executes:

![image](https://user-images.githubusercontent.com/511777/213523088-f7b30e94-20bb-4989-a3bf-d73856819129.png)

Could it be that the test is failing because "type" is undefined?

**Comment by svdasein** [comment]
I think maybe I've found something 

![image](https://user-images.githubusercontent.com/511777/213539250-6acb1b74-1793-4e60-946a-7e6a87578e38.png)

Does that help?

**Comment by dceejay** [comment]
pushed a version 2.33.0

**Comment by svdasein** [comment]
Dave should I be seeing 2.33.0 in the "manage palette" thing in node-red? (I'm not atm)

Thanks,

Dave

**Comment by dceejay** [comment]
sorry - is there now

**Comment by dceejay** [comment]
by all means feel free to sponsor the project :-)
