### ISSUE TITLE
Which ports are used by redmap? (issue with ssh tunnel)

### ISSUE THREAD

**Issue by M0ebiu5** [dceejay/RedMap#23]
The map does not show any plotted markers on the map, if i use it thru an ssh tunnel. I only forwarded the default node red port 1880. Does the map need any other ports?

**Comment by dceejay** [comment]
it uses the socket.io library so tries to use websockets to start with , dropping back to ajax or long polling if they fail.. so should only need the same port to be open.

**Comment by M0ebiu5** [comment]
thanks!
