### ISSUE TITLE
Custom map layer not selected automatically

### ISSUE THREAD

**Issue by Digitum** [dceejay/RedMap#230]
Nodered v3.0.2
node-red-contrib-web-worldmap: 2.37.1
Module: location/worldmap

When selecting "Custom Map Provider" on Base map field, and remove all other providers, and deploy changes, the map does not automatically selects the custom map. 

When manually selecting the custom map, it works, but are not initialized as it should. Also, all settings (pan/zoom etc) is not set as it should.

![image](https://user-images.githubusercontent.com/9963291/234282261-eb5b7ea2-bfb6-4a7a-9457-af49924a2d7f.png)
![image](https://user-images.githubusercontent.com/9963291/234282736-fe8f20d2-35fa-4c05-9971-fd4d930471dc.png)

In browser console log, message "BAD DATA" is shown:
![image](https://user-images.githubusercontent.com/9963291/234283943-9cca4bf6-e11e-41a1-ac2e-b365e59d8c3a.png)

Expected behaviour is to show the custom layer immediatly on page reload.

**Comment by dceejay** [comment]
Fixed in v2.37.2

**Comment by Digitum** [comment]
Excellent. I can confirm that it works at first glance.
Thank you for quick response.
