### ISSUE TITLE
BAD DATA when speed is added to data

### ISSUE THREAD

**Issue by DRazumovskiy** [dceejay/RedMap#237]
Hi, I have a similar issue as one reported in Issue #169 with BAD DATA thrown in console when speed is added to payload.

All cases that I tried:

1. Payload does not contain speed - no errors
2. Payload contains speed represented by decimal number - BAD DATA in console
3. Payload contains speed and the value is 0 - BAD DATA in console
4. After the map is loaded the object is shown with heading marker:
![image](https://github.com/dceejay/RedMap/assets/13840421/2ca8ec7b-a66d-4353-830b-b12521fe32aa)
after the first data update the heading marker disappears:
![image](https://github.com/dceejay/RedMap/assets/13840421/369711f1-20c8-4064-aa31-3cdef306bdaa)

This is a JSON with speed that causes BAD DATA:
`{"name":"Maria Pinta","lat":44.001767,"lon":9.685178,"hdg":164,"speed":3.2,"label":"Maria Pinta","icon":"ship","iconColor":"#35ADF8","color":"#44803F","layer":"barche","ricevuto":"0 sec fa","skipper":"Senza skipper"}`

This is a JSON without speed that does not cause errors:
`{"name":"Magialla","lat":44.079665,"lon":9.831423,"hdg":0,"label":"Magialla","icon":"ship","iconColor":"#D8D8D8","color":"#A3A3A2","layer":"barche","ricevuto":"7 min fa","skipper":"Senza skipper"}`

_Originally posted by @DRazumovskiy in https://github.com/dceejay/RedMap/issues/169#issuecomment-1583156864_

**Comment by dceejay** [comment]
Which version of the node are you using. If I test the payload above that you say fails - it works for me...

<img width="714" alt="image" src="https://github.com/dceejay/RedMap/assets/5375409/3cf4e00f-4392-40e7-aaea-4acdc2006eeb">

**Comment by dceejay** [comment]
Closing as no follow up
