### ISSUE TITLE
get 401 when the map loads tile png files for roads, rain, pressure and weather layer

### ISSUE THREAD

**Issue by jmikerq** [dceejay/RedMap#24]
Notice these errors in the chrome developer console. Running the latest version of node-red-contrib-web-worldmap, node-red@0.17.5. 

The errors in the chrome console look like these:

b.tile.openweathermap.org/map/rain/10/164/350.png:1 GET http://b.tile.openweathermap.org/map/rain/10/164/350.png 401 (Unauthorized)
349.png:1 GET http://b.tile.openweathermap.org/map/rain/10/162/349.png 401 (Unauthorized)
b.tile.openweathermap.org/map/rain/10/163/351.png:1 GET http://b.tile.openweathermap.org/map/rain/10/163/351.png 401 (Unauthorized)
349.png:1 GET http://b.tile.openweathermap.org/map/rain/10/165/349.png 401 (Unauthorized)
352.png:1 GET http://b.tile.openweathermap.org/map/rain/10/165/352.png 401 (Unauthorized)
351.png:1 GET http://b.tile.openweathermap.org/map/rain/10/166/351.png 401 (Unauthorized)
350.png:1 GET http://a.tile.openweathermap.org/map/rain/10/166/350.png 401 (Unauthorized)
350.png:1 GET http://a.tile.openweathermap.org/map/rain/10/163/350.png 401 (Unauthorized)
351.png:1 GET http://a.tile.openweathermap.org/map/rain/10/165/351.png 401 (Unauthorized)
352.png:1 GET http://a.tile.openweathermap.org/map/rain/10/164/352.png 401 (Unauthorized)
349.png:1 GET http://a.tile.openweathermap.org/map/rain/10/164/349.png 401 (Unauthorized)
351.png:1 GET http://a.tile.openweathermap.org/map/rain/10/162/351.png 401 (Unauthorized)
349.png:1 GET http://c.tile.openweathermap.org/map/rain/10/166/349.png 401 (Unauthorized)
350.png:1 GET http://c.tile.openweathermap.org/map/rain/10/162/350.png 401 (Unauthorized)
351.png:1 GET http://c.tile.openweathermap.org/map/rain/10/164/351.png 401 (Unauthorized)
350.png:1 GET http://c.tile.openweathermap.org/map/rain/10/165/350.png 401 (Unauthorized)
349.png:1 GET http://c.tile.openweathermap.org/map/rain/10/163/349.png 401 (Unauthorized)
352.png:1 GET http://c.tile.openweathermap.org/map/rain/10/163/352.png 401 (Unauthorized)
352.png:1 GET http://b.tile.openweathermap.org/map/rain/10/162/352.png 401 (Unauthorized)
352.png:1 GET http://c.tile.openweathermap.org/map/rain/10/166/352.png 401 (Unauthorized)

and thus I don's see these layers showing on the map.

**Comment by dceejay** [comment]
Yes - sorry - seems like the providers for these no longer serve them for free.. I'll remove them.

**Comment by dceejay** [comment]
removed from menu as source no longer available
