### ISSUE TITLE
Adding multiple markers triggers multiple action "bounds" event 

### ISSUE THREAD

**Issue by evcharger** [dceejay/RedMap#244]
Hello,
When I inject multiple markers (array of over 1000), Node-Red and Worldmap hang and I receive bounds event for every marker from every connected IP/Session that the markers were sent to. What could be causing this and how can I change it so that these bounds events are not sent when injecting the markers?

**Comment by meeki007** [comment]
Disable auto-pan as it be trying to pan the map for each marker.
Then use a split node to add makers 1 at a time.

I then run my own calculation(function) to auto center(auto-pan) all my 100's of markers

example of what I came up with to auto center and zoom on my markers
```
// reformat lat: key's value in object to an Array
var lat_to_array = msg.payload.map(obj => Number(obj.latitude));

// reformat lon: key's value in object to an Array
var lon_to_array = msg.payload.map(obj => Number(obj.longitude));

// get the average of all the values in lat array
let sum_lat = lat_to_array.reduce((previous, current) => current += previous);
let avg_lat = sum_lat / lat_to_array.length;

// get the average of all the values in lon array
let sum_lon = lon_to_array.reduce((previous, current) => current += previous);
let avg_lon = sum_lon / lon_to_array.length;

//find the greatest distance of sepreration between two cameras on the map
// used to set zoom distance on map
//get highest and lowest values in both arrays
var lat_max = Math.max(...lat_to_array);
var lat_min = Math.min(...lat_to_array);
var lon_max = Math.max(...lon_to_array);
var lon_min = Math.min(...lon_to_array);
var lat_lon_seperation_max_array = [(lat_max) - (lat_min),(lon_max) - (lon_min)];
var lat_lon_seperation_max = Math.max(...lat_lon_seperation_max_array);

//set the map zoom level
var map_zoom_level = 2;
if (lat_lon_seperation_max < (1/512)) { map_zoom_level = 18; }
else if (lat_lon_seperation_max < (2/512)) { map_zoom_level = 17; }
else if (lat_lon_seperation_max < (4/512)) { map_zoom_level = 16; }
else if (lat_lon_seperation_max < (8/512)) { map_zoom_level = 15; }
else if (lat_lon_seperation_max < (16/512)) { map_zoom_level = 14; }
else if (lat_lon_seperation_max < (32/512)) { map_zoom_level = 13; }
else if (lat_lon_seperation_max < (64/512)) { map_zoom_level = 12; }
else if (lat_lon_seperation_max < (128/512)) { map_zoom_level = 11; }
else if (lat_lon_seperation_max < (256/512)) { map_zoom_level = 10; }
else if (lat_lon_seperation_max < (512/512)) { map_zoom_level = 9; }
else if (lat_lon_seperation_max < (1024/512)) { map_zoom_level = 8; }
else if (lat_lon_seperation_max < (2048/512)) { map_zoom_level = 7; }
else if (lat_lon_seperation_max < (4096/512)) { map_zoom_level = 6; }
else if (lat_lon_seperation_max < (8192/512)) { map_zoom_level = 5; }
else if (lat_lon_seperation_max < (16384/512)) { map_zoom_level = 4; }


msg.payload = { command:{layer:"",lat:avg_lat,lon:avg_lon,zoom:map_zoom_level} };



//msg.map_zoom_level = map_zoom_level;
msg.avg_lat = avg_lat;
msg.avg_lon = avg_lon;
//msg.lat_lon_seperation_max = lat_lon_seperation_max;


return msg;
```

**Comment by evcharger** [comment]
Thank you for this solution! I will try it out. In the meanwhile, some more information as to how this problem occurs:
1. If I inject a JSON array with the markers, with only: name, lat, lon, icon, layer, popped, ttl - it tries to pan for each marker and sends bounds event.
2. If I inject a JSON array with the markers, containing all properties possible with null values except for: name, lat, lon, icon, layer, popped, ttl (they contain same values as in 1. ) - there is no panning and no bounds event. 
In both cases markers show up on map as expected.

**Comment by meeki007** [comment]
The best bet for @dceejay or maybe me, as I do play with the innards of the wolrdmap quite a bit, to track down this issue is to create a flow that we can import that when we hit the inject for each of the above examples 1 and 2 we have the same issue. Then we may be able to track it down.

**Comment by evcharger** [comment]
With the panit set to false it works without issues. Thank you!

**Comment by PizzaProgram** [comment]
@meeki007 

> msg.payload.map(obj => Number(obj.latitude));

May I ask: 
 - Where do you get that `obj` filled up with all gps coords?
 - Is there a way to read all the object from a layer previously added?
