### ISSUE TITLE
UI Issue using Drawing Layer

### ISSUE THREAD

**Issue by innoagg** [dceejay/RedMap#248]
Window 10 Pro 19045.3448
Chrome Browser Version 116.0.5845.188 (Official Build) (64-bit)
Edge Browser Version 117.0.2045.36 (Official build) (64-bit)
Worldmap: 2.42.3

Cannot select Polygon or Line tool to draw with. The "hand" mode of the cursor takes priority over the crosshair cursor and so a point can not be placed on the map. 

Circle and Square work as expected.

**Comment by dceejay** [comment]
Sorry I'm not quite understanding... For me drawing is working for all types. Is it the initial drawing ? or editing after having done the drawing ?
I'm using Chrome Version 117.0.5938.92 (on Mac)

**Comment by innoagg** [comment]
It's the initial drawing. I will take a video and post. Reproduced on
multiple PCs. Windows 10 and 11 chrome and edge.

**Comment by innoagg** [comment]
This could be a silly user error, but there are 3 of us scratching our heads. Here is the video. 

https://youtu.be/ifP88M74VrI

**Comment by dceejay** [comment]
I'm currently looking to replace Draw with Geoman as that is much mode supported.
Will be version in 3.0
