### ISSUE TITLE
fa icon pointer

### ISSUE THREAD

**Issue by beneuto** [dceejay/RedMap#25]
The fa icons are a welcome addition but are all shown with a small square which I assume is meant to point to the lat/long location.   2 issues with this pointer:

1. It detracts from the look (or more bluntly it is ugly, particularly where there are many icons in close proximity.)

2. If it is indeed meant to be a pointer then it is not accurate.   It does not quite point to the same location as the non-fa icon.

**Comment by dceejay** [comment]
HI - can you attache a small screen grab to show what you mean ? 
What platform / os / browser ?

**Comment by beneuto** [comment]
You can see the small squares here.   I am running node-red as an Azure Web App and viewing the map on Chrome/Windows 10.

![image](https://user-images.githubusercontent.com/25493799/29149363-efffb3a8-7db6-11e7-838e-98725d168eda.png)

**Comment by dceejay** [comment]
gotta love Windows... :-(
