### ISSUE TITLE
support for dynamic map icons

### ISSUE THREAD

**Issue by christian-skjetne** [dceejay/RedMap#251]
Could it be possible to add support for dynamic map icons? 
Like this, for instance:
msg.payload.icon = "data:image/bmp;base64,Qk22GAEAAAAAADYAAAAoAAAAEAEAAFgAAAA......";
similar to the way you would define base64 encoded images in html.
The use case for me is showing dynamically changing traffic signs on the map, if anyone was curious.

Not familiar enough with leaflet to know if this is possible or not. Also not sure if it is super useful for other people.

NOTE:
as a workaround I'm now using the photoUrl property and it is working fine, but that requires the user to click on the marker to see the image.

**Comment by dceejay** [comment]
well you can change the icon at any time but just resending the point with a new msg.payload.icon - we currently support fa-icons(4.7), emojis, or urls so no need to use photoUrl property. I guess we could add support for inline but I'm not sure what benefit it would bring ? (there would be no control over size/alignment)

**Comment by dceejay** [comment]
Actually just published as v4.2.0
