### ISSUE TITLE
4.2 version SyntaxError: Unexpected token '.' (line:129)

### ISSUE THREAD

**Issue by brothercorvo** [dceejay/RedMap#252]
Hi, the 4.2  version of the worldmap is failing. We use it in FTS webMaps

**Comment by dceejay** [comment]
Hi - any more info than that ?
What are you sending ? 
any chance of an example flow that fails ?

**Comment by brothercorvo** [comment]
NodeJS version provided by Ubuntu will only run like, Node12, which NodeRed 2.3 is the latest that can run on that Node12 version.

**Comment by dceejay** [comment]
Don't use the one provided by Ubuntu - it is past end of service life and probably has security vulnerabilities.
Even Debian (Bookworm) now has nodejs 18 in the repo. - But better to get direct from node source - https://github.com/nodesource/distributions or use our Node-RED install script which will also install nodejs... https://nodered.org/docs/getting-started/raspberrypi

I will patch that line so it may work for you - but in general going forwards you should migrate to a supported version.

**Comment by dceejay** [comment]
Released as 4.2.1

**Comment by brothercorvo** [comment]
thank you so much for the quick fix @dceejay. we are looking forward to fix that
