### ISSUE TITLE
[Feature Request] Configure the layers shown when a map is loaded

### ISSUE THREAD

**Issue by JohnnyPicnic** [dceejay/RedMap#257]
Is it possible to configure the layers shown when a map is loaded?
Something like:
`msg.layer = { 
    "name": "layer_name", 
    "show_on_load": true 
    }`

**Comment by dceejay** [comment]
As per the README you should be able to combine loading a layer with a command to show it
{"command":{"showlayer":"foo"}}

Or is that not what you mean ?

**Comment by JohnnyPicnic** [comment]
Yup that's it. I thought I had looked through the readme... :disappointed:
