### ISSUE TITLE
Number of points in  tracks 

### ISSUE THREAD

**Issue by jhonyasqui3** [dceejay/RedMap#258]
Is it possible to read the number of points on the track using a function node and enter it into the map so that this value would be variable according to other data? or does it always remain static?

**Comment by dceejay** [comment]
You can't read the number of points already held - but as per the node info
<img width="299" alt="image" src="https://github.com/dceejay/RedMap/assets/5375409/a74745c9-515a-4ebd-ae45-3e7dd168d548">
