### ISSUE TITLE
Grouping of layers in layer menu?

### ISSUE THREAD

**Issue by TwinTurbine** [dceejay/RedMap#263]
Hi,

Is it possible to group different overlays in the layer menu? For instance it would be nice to visually separate different "map overlays" from "object overlays". Maybe even a checkbox to show/hide all overlays in respective group with one click/command?

**Comment by dceejay** [comment]
Hi,

not quite sure what you mean - but the layer menu is by default what Leaflet gives you - so I can't think of a simple way to separate them.

**Comment by TwinTurbine** [comment]
I think I'm looking for something similar to this: https://leafletjs.com/examples/layers-control/ but I'm uncertain about how to achieve this in Worldmap. If it's possible. This will on one hand combine the layers, but it might be as close as one can get.

**Comment by dceejay** [comment]
OK - I'm still not getting it. That is the control that Worldmap uses... any basemaps you add get added to the radio buttons and any overlays get added to the checkboxes...

**Comment by TwinTurbine** [comment]
Let's say that we have one overlay containing cars, one with buses and one with trucks. AFAIK there's only one way to set them up toady:

- [ ] Cars
- [ ] Buses
- [ ] Trucks

My question is if it is possible to group them something like this, ideally:
- [ ] Vehicles
  - [ ] Cars
  - [ ] Buses
  - [ ] Trucks

Or maybe just separate them visually by "groups":

----------------------------
- [ ] Cars
- [ ] Buses
- [ ] Trucks
----------------------------
- [ ] Small vessels
- [ ] Medium vessels
- [ ] Big ships
----------------------------
- [ ] Helicopters
- [ ] Airplanes
----------------------------

**Comment by dceejay** [comment]
Ah right - no you can't do that. There are leaflet plugins that can do that sort of thing but I can't just add one without replumbing all the existing calls. (eg - https://github.com/ismyrnow/leaflet-groupedlayercontrol?tab=readme-ov-file)

**Comment by TwinTurbine** [comment]
Yeah, that sounds like something similar that I'm looking for. But I understand that it would be a hassle to implement it. Just wanted to ask the question. Thanks for looking into it!
