### ISSUE TITLE
Linestring getting filled like polygon ?

### ISSUE THREAD

**Issue by gitToad** [dceejay/RedMap#265]
Not sure whether *I* am doing something wrong or this is a bug:

when i send packets like this to the map:
**name**: "C101 path"
**line**: array[52]
[0 … 9]
0: array[2]
   0: 35.3815871
   1: -121.2555771
1: array[2]
   0: 35.3817143
   1: -121.2547551
2: array[2]
3: array[2]
4: array[2]
5: array[2]
6: array[2]
7: array[2]
8: array[2]
9: array[2]
**color**: "#432257"
**layer**: "Paths"

The rendered version looks like this - it has the correct path/line color but it also fills the geometry with dark green. Even though I did not specify "area", but "line". If I misunderstood the instructions for line rendering in the documentation, could you please comment and close this issue.
<img width="554" alt="image" src="https://github.com/dceejay/RedMap/assets/503035/297d27c0-0a43-41a7-83ce-fc400b5cd459">

**Comment by dceejay** [comment]
Please can you supply the flow snippet used so I can see how you have the nodes configured and the exact data going in ? Thanks
