### ISSUE TITLE
Missing layer button in dashboard frame

### ISSUE THREAD

**Issue by BrendanM-RSA** [dceejay/RedMap#27]
I created a home page for my Node Red dashboard with 2 frames. I have the map shown in the 1 frame and the UI in the other. The map frame does not show the layers button in the top RHS.  The Locate Me, Measure Distance, Full Screen buttons are also not shown on the top LHS.  If I browse direct to the Worldmap (not using the home page) then these buttons are shown, so it has something to do with using the Worldmap in a frame. Tried Chrome and IE.

This is my template node for the 2 frames.

![image](https://user-images.githubusercontent.com/32435731/31056335-53382972-a6d0-11e7-926b-01a661fd1b87.png)

Here is the home page with the missing buttons

![image](https://user-images.githubusercontent.com/32435731/31056343-76abe72c-a6d0-11e7-9e3a-1ee83726c5de.png)

**Comment by dceejay** [comment]
That is working as designed - the assumption being that if the user is embedding the map that they will control the layers themselves using buttons outside of the map area.

**Comment by BrendanM-RSA** [comment]
Ok that makes sense but could you not make it an option whether the layer/drawing controls are visible or not?

**Comment by dceejay** [comment]
A not unreasonable request - will add to the todo list.
