### ISSUE TITLE
Cannot GET /api/worldmap/socket/info

### ISSUE THREAD

**Issue by christianbrueggemann** [dceejay/RedMap#28]
Hello,

I am trying to use worldmap on a docker container in aws (Version 1.1.3).

When locally running on my machine, all works fine, however in AWS I see the map under ../api/worldmap but it cannot establish the socket connection. In the debug console of the browser it tries to make a HTTP get every second. See Screenshot. Any idea why this could happen?

<img width="1372" alt="screen shot 2017-10-11 at 12 41 20" src="https://user-images.githubusercontent.com/12034002/31436121-2b2aff04-ae82-11e7-8128-aff43ea88b7b.png">

**Comment by dceejay** [comment]
no idea. - It uses the sockjs library that automatically tries to drop back down the ajax and long polling if it can't create a true websocket - so I guess the problem lies in the websocket connection - but I don't use AWS so can't really advise.

**Comment by unixweb** [comment]
I have the same issue 

maybe it have to add the Path httpRoot: '/nodered', from the settings.js 
If i use node-red without modify the httpRoot worldmap works 


       var clients = {};
        //node.log("Serving map from "+__dirname+" as "+RED.settings.httpNodeRoot.slice(0,-1)+"/worldmap");
        RED.httpNode.use("/worldmap", express.static(__dirname + '/worldmap'));

Here are the settings from the Apache Webserver : 
ProxyPass /nodered/comms ws://127.0.0.1:1880/nodered/comms
ProxyPass /nodered/worldmap ws://127.0.0.1:1880/nodered/worldmap <-- not works 
ProxyPass /nodered http://127.0.0.1:1880/nodered
ProxyPass /nodered/ui http://127.0.0.1:1880/nodered/ui
ProxyPassReverse /nodered/comms ws://127.0.0.1:1880/nodered/comms
ProxyPassReverse /nodered/worldmap ws://127.0.0.1:1880/nodered/worldmap <-- not works 
ProxyPassReverse /nodered http://127.0.0.1:1880/nodered
ProxyPassReverse /nodered/ui http://127.0.0.1:1880/nodered/ui

![bildschirmfoto 2017-10-28 um 13 51 54](https://user-images.githubusercontent.com/12023025/32134250-944e2442-bbe9-11e7-985d-31e44780a163.png)

**Comment by beneuto** [comment]
I'm not a developer so hesitant to change source code here but I got this to work by updating two references to "prefix" in worldmap.js as follows:


prefix:'/worldmap/socket'

prefix: path.posix.join(RED.settings.httpNodeRoot,'/worldmap/socket')

**Comment by dceejay** [comment]
looks sensible - will test it out. thanks
