### ISSUE TITLE
command to clear mapped points

### ISSUE THREAD

**Issue by luisgcu** [dceejay/RedMap#29]
hello 
first of all  thanks you for sharing your job.
is there any command  that can be passed to the world map node that can clear all points posted in a map?
thanks

**Comment by dceejay** [comment]
not at present... but not an unreasonable suggestion.
but you can send a msg with {name:"the point name, delete:true} - to delete any names point...
or you can set them to timeout and they will disappear after a set time.

**Comment by luisgcu** [comment]
Hello @dceejay  thanks for your response.
basically I am using your world map node , to track gps points that LoRa mobile units with GPS send  to gateway (ESP8266) with  LoRa radio,  I store the points in mysql , then pull the points  for analysis based on a  date, rssi level, and distance, i use that to  basically analyze the antenna performances and also to test the various Lora radios     spreading factors and and bandwidth . so I got a lot of pints on the map, right now to clear the map i have to refresh chrome. 
very soon I will be posting somewhere What i have done, so maybe more people can be interested on that.

**Comment by dceejay** [comment]
Hi have pushed v1.1.5  that allows sending a command to clear a complete layer in one go

        msg.payload = {};
        msg.payload.command = {clear:"unknown"};
        return msg;
