### ISSUE TITLE
'feedback' missing several fields

### ISSUE THREAD

**Issue by phreed** [dceejay/RedMap#293]
In v5.0.3
When using 'feedback' as described in 
https://flows.nodered.org/node/node-red-contrib-web-worldmap "Events From the Map".

The documentation states that I should expect to get something like:
```json
{"payload": {
   "action": "feedback",
   "name": "some name",
   "value": "some value",
    "lat":51, "lon":0,
     "layer":"unknown" 
     } 
}
```
The value I am returning is a json object.

```json
{"payload": {
     "name":"my_spot_report",
     "action":"feedback",
     "value":{
       "attitude":"friend",
       "geoObject":"Gnd Equip Vehicle",
       "timeout":"600",
       "name":"jan",
       "bearing":0,
       "distance":1,
       "how":"nonCoT"}
     },
   },
  "topic":"tak-map",
  "_sessionid":"4d8ff0dd-c1d7-41f2-8c13-c70c07f63017",
  "_sessionip":"10.2.118.201",
  "_msgid":"2155e06325ebcb78"
}
```

The 'lat', 'lon', and 'layer' are all missing.

Is  this is the same problem reported in https://github.com/dceejay/RedMap/issues/278 creeping back in?

https://github.com/dceejay/RedMap/blob/7d1782cc8b89537740921eb2c81123356c0d3a6d/worldmap/worldmap.js#L924-L941

**Comment by phreed** [comment]
It appears that in order to get the lat,lon the 'name' must be 'map'.

**Comment by zafrirron** [comment]
The feedback has more than one option, documentation states under :Event from the map": { "action": "feedback", "name": "some name", "value": "some value", "lat":51, "lon":0, "layer":"unknown" } // when a user calls the feedback function - see below

feedback as utility functions, states other ways to use this function.

if you are using it as utility function and wish to report back the lat lon position, you can use the rclk.lat, rclk.lng variables from your custom feedback code, to create your own custom feedback content.
