### ISSUE TITLE
Undocumented Flag Handling in SIDC Symbols

### ISSUE THREAD

**Issue by zafrirron** [dceejay/RedMap#296]
@dceejay 

Before submitting a new PR, I wanted to clarify a behavior I recently encountered:

After spending some time trying to understand why flag-xx was being appended to my SIDC symbols, I discovered the following code snippet:
`
javascript
Copy code
if (data.SIDC.length > 12) {
    var cc = data.SIDC.substr(12, 2).toLowerCase();
    opts.country = cc.toUpperCase();
    opts.staffComments = emojify(":flag-" + cc + ":") + " " + (opts?.staffComments || "");
    data.flag = emojify(":flag-" + cc + ":");
}
`
This code assumes that the SIDC string has an additional flag identifier beyond the standard length. However, this behavior is undocumented and not compliant with milsymbol.js, which supports MIL-STD-2525D (and possibly assumes compliance with MIL-STD-2525C). Introducing this undocumented feature creates inconsistencies.

Furthermore, since the `payload.flag` option already exists, why not use it directly to set the flag instead of deriving it from the SIDC string in this ad hoc manner?

Additionally, as per the emoji list used ([emojilist](https://github.com/dceejay/RedMap/blob/master/emojilist.md)), the emojify(":flag-xx:") will only return the same two characters instead of an actual flag emoji. Therefore, the benefit of constructing an emoji string in this way is unclear. If it doesn't yield the intended flag symbol, why introduce this complexity?

Suggested Actions:

Either remove this undocumented SIDC flag handling or document it explicitly, ensuring it aligns with the MIL-STD-2525D standard.
Consider leveraging the existing `payload.flag` for this functionality instead of adding assumptions based on SIDC strings.
Simplify or clarify the emoji construction if it doesn't achieve the desired visual representation.
Would appreciate any feedback or thoughts on how to address this discrepancy.

B.T.W - Is there any way for less formal contributors discussion?

**Comment by dceejay** [comment]
The [2525C standard](https://worldwind.arc.nasa.gov/milstd2525c/Mil-STD-2525C.pdf) defines a 15 char string  of which
"g. Positions 13 and 14, country code, identifies the country with which a symbol is associated. Country code identifiers are listed in ISO 3166-1." - so it could be there - it's not an assumption/ad-hoc.

The fact that most uses only use 12 chars (eg milsymbol.js) - is fine - but hey - if the info is there occasionally we can try to show it.
Milsymbol.js also has optional fields for other things like targetNumber but doesn't display that either... 

msg.payload.flag should create a flag symbol in the popup info panel if valid - which is best we can do for non-SIDC icons

Email works if you prefer -  dceejay (A-T) gmail.com

**Comment by dceejay** [comment]
Closed by fixes.
