### ISSUE TITLE
The "node-header-stack" component is unlicensed 

### ISSUE THREAD

**Issue by akd022** [dceejay/RedMap#298]
Can this component "node-header-stack" be replaced with another that has a license?

note, there is an issue logged against this component requesting a license that has gone unaddressed since 2021

**Comment by akd022** [comment]
noting that the "header-stack" package is used by the "cgi@0.3.1", from the same developer, component which is directly used by RedMap.

so the request is, can the "cgi@0.3.1" component be replaced to avoid the unlicensed dependency component "header-stack" ?

**Comment by dceejay** [comment]
Hmm - looking at it again - not so sure I want to remove just like that - as it is still the best way to use fully featured old style local map server. Will need to think how to make it more pluggable. Of course you are free to remove the package from your setup as it will still function fine without it if you aren't using local maps served by the mapserver package.

**Comment by akd022** [comment]
Thanks @dceejay 

just to be clear removing the CGI package will ONLY affect the cases where one has to connect to a local WMS?

**Comment by dceejay** [comment]
Yes  - cgi is only needed to access/run the mapserv executable that talks to mapserver app on Linux.

**Comment by akd022** [comment]
thanks @dceejay .... you are a star! :)

hope in the future though you can switch to a different package, "cgi-core" seems to be a candidate that does the same job.

**Comment by dceejay** [comment]
cgi-core does seem to work though you have to setup the call to mapserv as mapserv.sh instead - so it will be a breaking change when I introduce it. So will be in version 6 as and when I get round to it.
