### ISSUE TITLE
Following the movements on the map as action?

### ISSUE THREAD

**Issue by chameleonbr** [dceejay/RedMap#3]
It is possible to follow the movements from the user on the map? changing the location, zoom and perhaps even insert a central point where the user is focused on the map and get it as an action?
Thanks for the worldmap node, is very useful.

**Comment by dceejay** [comment]
Under the menu - auto pan map will follow the latest point updates
For control try looking at the readme.... http://flows.nodered.org/node/node-red-contrib-web-worldmap.
The latest version you can set the start point in the edit config.
