### ISSUE TITLE
Upgrade to current version of Leaflet 1.2.0

### ISSUE THREAD

**Issue by rmh78** [dceejay/RedMap#32]
Thanks for all your work of wrapping leaflet for using inside node-red.
Are you planning to upgrade to the current version of leaflet and it's new features?

**Comment by dceejay** [comment]
Sorry - I don't have time to look at it right now. Would be nice of course - but I also rely on a lot of extra plugins so they would all have to be compatible as well, so ned to be checked through.

Totally up for someone to either try it and report back what breaks - or to raise necessary PR(s).
