### ISSUE TITLE
is this possible?

### ISSUE THREAD

**Issue by realjax** [dceejay/RedMap#35]
It seems the map only displays icons whenever it receives a msg object with some lat/lon info. 
When I refresh my node red dasboard, change pages, or open it for the first time no icons are shown.
Is there a way to have the map load them after initialisation or something?

**Comment by dceejay** [comment]
the worldmap input node provides a signal that a new client has connected or refreshed their page (IE the websocket has restarted) - you can use this to trigger a resend of any data you have previously stored somewhere. The worldmap does not store data.

**Comment by realjax** [comment]
cool, thanks!
