### ISSUE TITLE
getting mixed content warnings

### ISSUE THREAD

**Issue by realjax** [dceejay/RedMap#36]
getting warnings like the one below. Is there a way to force the map to also use an ssl connection?

`Mixed Content: The page at 'https://noderedsite/ui/#/0' was loaded over HTTPS, but requested an insecure image 'http://a.tile.openstreetmap.org/10/507/342.png'. This content should also be served over HTTPS.`

**Comment by dceejay** [comment]
I should probably change them all to https anyway - all the sources I have built in all serve https.
(though my browser does try to auto switch to https in preference so I've never noticed :-)
