### ISSUE TITLE
Custom attribution not working

### ISSUE THREAD

**Issue by michisnewsletter** [dceejay/RedMap#38]
I have tested your [Demo Flow](https://flows.nodered.org/node/node-red-contrib-web-worldmap) to add a new base-layer. I get the new layer _OSMhot_ in my map.

In your flow, the option _attribution_ is set in the function node _add new layer_ to this value
`attribution: '&copy; OpenStreetMap'`

In the right footer, only "Leaflet" is showing, but not 'Leaflet | © OpenStreetMap'. 

Can you help me ?

Thanks
 Michael

**Comment by michisnewsletter** [comment]
I have found a workaround., in your Example you wrote:
```javascript
msg.payload = {};
msg.payload.command = {};

var u = 'http://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png';
var o = JSON.stringify({ maxZoom: 19, attribution: '&copy; OpenStreetMap'});

msg.payload.command.map = {name:"OSMhot", url:u, opt: o };
msg.payload.command.layer = "OSMhot";

return msg;
```

but this is not working, no opt-values connected throw the leaflet-control.

This Code ist working:
```javascript
msg.payload = {};
msg.payload.command = {};

var u = 'http://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png';

msg.payload.command.map = {name:"OSMhot", url:u, opt:
    { maxZoom: 19, attribution: '&copy; SSOpenStreetMap'}
    
};
msg.payload.command.layer = "OSMhot";

return msg;
```
Can you explain me this ?

Thanks
 Michael

**Comment by dceejay** [comment]
Sorry - where are you getting the example from exactly ?
the one here works

https://www.npmjs.com/package/node-red-contrib-web-worldmap#to-add-a-new-base-layer

**Comment by dceejay** [comment]
Ah found it.. thanks.
updated to work
