### ISSUE TITLE
Does not work if httpRoot setting is used

### ISSUE THREAD

**Issue by Oliv4945** [dceejay/RedMap#4]
Dear,

I just tried your node but it seems, if I am not wrong, that socket.io does not use `httpRoot`. The map is loaded with success on `https://domain.net/httpRoot` but nothing works, when I look in the debug console I have the following error:
`
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (socket.io, line 0)   
https://domain.net/socket.io/?EIO=3&transport=polling&t=LNftCyy
`

A closer look on your code and the socket.io [doc](https://github.com/socketio/socket.io) seems to show that you never pass the `httpRoot` address to `server#path` option of socket.io, nor on the client side but I do not know where it should be set.

**Comment by dceejay** [comment]
how are you hosting this ? looks more like a connection failure. It working fine for me locally on a Mac and Pi, if I set httpRoot to be /red for example.

**Comment by Oliv4945** [comment]
Oh, true ! I am using a reverse proxy configured as : secured connection to HAProxy->unsecured to local:1880. I just tried without HAProxy with http://domain.net:1880/red and it works.
The issue might be socket.io because your [simple web socket](http://flows.nodered.org/flow/8666510f94ad422e4765) example works well behind HAProxy. I will try to learn how socket.io works to debug that...

**Comment by dceejay** [comment]
closing for now - please re-open if a real issue at my end
