### ISSUE TITLE
flows.nodered.org webpage formatting issue

### ISSUE THREAD

**Issue by clowrey** [dceejay/RedMap#43]
I believe something in your documentation page affects the formatting on the node-red flows page here:
https://flows.nodered.org/node/node-red-contrib-web-worldmap

The Node Info right sidebar gets moved to the bottom of the page for me on Chrome Version 68.0.3440.106 (Official Build) (64-bit)

Other node pages on flows.nodered.org look normal with the sidebar on the right. 

![formatting](https://user-images.githubusercontent.com/6935928/44811923-95f02e80-ab71-11e8-98c2-6008f1cd2c47.JPG)

**Comment by dceejay** [comment]
Closing as this is not an issue with this project.
