### ISSUE TITLE
Map won't load

### ISSUE THREAD

**Issue by hubertguillemain** [dceejay/RedMap#47]
When I go to {hostname}/worldmap, the map starts to load (I have the top bar with the menu button) but the main content remains white.

I have the following error in the console:
(index):1021 Uncaught SyntaxError: Unexpected token
The culprit seems to be line with a missing opening parenthesis
`opts.size = opts.size - 30) / 2 + 30;`

worldmap version: 1.3.7
Note that the flow library and NPM sites indicate a 1.3.8 version, but it's not available from the Node-Red GUI palette

**Comment by dceejay** [comment]
yes you need 1.3.8. maybe stop and restart Node-RED - or install in manually.

**Comment by hubertguillemain** [comment]
Can you please re-open ?
I have installed 1.3.8, restard node-red as the UI recommended,  I still have the same issue


FYI,I'm using the demo flow from the flow library:
https://flows.nodered.org/node/node-red-contrib-web-worldmap

**Comment by dceejay** [comment]
try flushing your browser cache - ctrl-r reload.
