### ISSUE TITLE
Changing size of fa icons

### ISSUE THREAD

**Issue by keptenkurk** [dceejay/RedMap#49]
Trying to add an icon property "size" to be able to change the size of a fa-icon being sent to the map.
Tried changing fa-2x to fa-xs in index.html below as a first try however without much luck:

        else if (data.icon && (data.icon.substr(0,3) === "fa-")) {
            var col = data.iconColor || "#910000";
            myMarker = L.divIcon({
                className:"faicon",
                html: '<center><i class="fa fa-fw fa-xs '+data.icon+'" style="color:'+col+'"></i></center>',
                iconSize: [30, 30]

Would this be at all possible?

**Comment by dceejay** [comment]
hmmm - trickier - as I want/need the default to be 2x. However what you are doing would achieve it - were it not for the fact we use Font Awesome 4.7 - which does not include fa-xs...
only `fa-lg, fa-2x, fa-3x, fa-4x, fa-5x` are supported.

**Comment by keptenkurk** [comment]
I'll give that a go and try to come up with something which defaults to fa-2x but could be overridden by an optional field in the data.

**Comment by keptenkurk** [comment]
No joy, Just replacing fa-2x with any other supported one does not change a thing.
I only change the index.html in .node-red/node_modules/node-red-contrib-web-worldmap/worldmap/index.html at line 1052 directly. Then do a node-red restart and Ctrl F5 to clear any browser cache... wrong procedure?

**Comment by dceejay** [comment]
you need to also edit the `worldmap.appcache` file slightly then restart reload

**Comment by keptenkurk** [comment]
Ok, finally managed to change it. Apparently the fa-lg size is not very much smaller than the fa-2x so it doensn't help me. I'll have to figure another way around.

**Comment by dceejay** [comment]
Have thought of a way to allow some modification. If I look to see if the icon is specified has a space in it then don't add the fa-2x - so you can use things like `fa-3x fa-circle-o`  - or in your case just add a space to the icon name and it should do the smaller "1x" size. Will be in version 1.4.6

**Comment by dceejay** [comment]
Quick example

```
[{"id":"4a022013.2ceeb","type":"inject","z":"d511095d.512808","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":120,"y":810,"wires":[["6a2198e9.803078"]]},{"id":"6a2198e9.803078","type":"function","z":"d511095d.512808","name":"Put marker on mylayer","func":"msg.payload = {name: \"test\",\n                lat: 51.4,\n                lon: 5.4,\n                layer: \"mylayer\",\n                icon: \"fa-bug \",\n                iconColor: \"#FF0000\"\n                }\nreturn msg;","outputs":1,"noerr":0,"x":340,"y":810,"wires":[["58004464.c603cc","157817ad.bea668"]]},{"id":"c029ee01.f1baa","type":"inject","z":"d511095d.512808","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":120,"y":855,"wires":[["5714e827.9229b8"]]},{"id":"5714e827.9229b8","type":"function","z":"d511095d.512808","name":"Put marker on mylayer","func":"msg.payload = {name: \"tests\",\n                lat: 51.45,\n                lon: 5.4,\n                layer: \"mylayer\",\n                icon: \"fa-bug fa-5x fa-spin\",\n                iconColor: \"#FF0000\"\n                }\nreturn msg;","outputs":1,"noerr":0,"x":340,"y":855,"wires":[["58004464.c603cc"]]}]
```

**Comment by keptenkurk** [comment]
Wauw Dave, You really made my day! A very neat and hassle free solution and exactly what i was looking for. But be aware: spinning bugs may be hard to catch.
Thanks a million!

**Comment by dceejay** [comment]
YES - I wasn't expecting those to work... but another whole dimension to maps... bugs that walk...
Only thing to be aware of is that the icon was trying to be centred when at the original size - so the actual lat lon on the icon won't be in the centre of the larger or smaller ones as the offsets will be different.
