### ISSUE TITLE
multiple layer overlay in one command

### ISSUE THREAD

**Issue by ThibautRuy** [dceejay/RedMap#53]
Not sure this is an issue, maybe simply a documentation issue. In the documentation, I can read 
**showlayer** - show the named overlay - {command:{showlayer:"foo"}}

Would it be possible to have an option to add multiple overlay with a single command?
`command:{layer:"Esri",lat:lat,lon:lon,zoom:12,showlayer:"roads,countries"}`

**Comment by dceejay** [comment]
Good idea... but it will probably be an array rather than a text list.
eg   showlayer:["reads","countries"]  
(will confirm once implemented... )
