### ISSUE TITLE
Worldmap in "action" when marker clicked

### ISSUE THREAD

**Issue by mereshow** [dceejay/RedMap#56]
Hi Dave,

Could it be possible to add a new "action" when a marker id clicked in order to read it with the "Worldmap in" node (and send, for instance, the marker name)?

I'm using the map, embedded in the dashboard, to show the location of several sensors. I would like to show several graphs for a sensor when the user clicks on its marker. I thinks this (simple?) addition could allow to create more complex dashboards.

Thanks for this great project! I'm using it in a research project in Galicia (Spain).

**Comment by dceejay** [comment]
Hi - do you mean instead of opening the popup ? or as well as ?

**Comment by dceejay** [comment]
added to version 1.5.12
