### ISSUE TITLE
Worldmap markers click "action" not working if clustered

### ISSUE THREAD

**Issue by mereshow** [dceejay/RedMap#57]
The new click action is not triggered if the marker is in a cluster, we click the cluster and then the marker.

**Comment by dceejay** [comment]
sorry, can you explain a bit more. If the marker is in a cluster the cluster doesn't register a click ? Or once unclustered it doesn't register a click ? or... 

The click action is only on a marker. so I wouldn't expect it to work on a  cluster. - You can always turn off clustering if you want.

**Comment by mereshow** [comment]
Once unclustered, but I discovered that the problem was a different one.
If you click on a cluster the markers it contains are shown, if then you click on a marker you get its coordinates. The problem is that these coordinates are different than the ones you get if you click on the same marker when you zoom enough for it to be unclustered (without clicking on the cluster). 

I was using the coordinates to access a database in order to know which marker was clicked and was getting nothing when clustered (because of the coordinates being different). Is it possible to send the marker id in the action object? Or make the marker coordinates the same regardless of the clustering status.

**Comment by dceejay** [comment]
apologies - the name was supposed to be part of the message but wasn't... now fixed.
The co-ordinates are those of the "spider" when the cluster expands so are not correct - so yes - use the name as that is unique.
