### ISSUE TITLE
Include map into dashboard 

### ISSUE THREAD

**Issue by rcadek** [dceejay/RedMap#58]
Hello, 

Is there a way to include the map in a kind of "box" or something like that, to add it in the dashboard ( node-red-dashboard - http://ip/ui ) and not in another page ( http://ip/worldmap ).

Thank you by advance.

**Comment by hubertguillemain** [comment]
Hi @rcadek 
There was an article on the topic here:

https://stackoverflow.com/questions/49232252/how-to-place-a-worldmap-on-a-node-red-dashboard

**Comment by dceejay** [comment]
There is even an example in the library . Menu - Import - Examples - Worldmap ....
