### ISSUE TITLE
Way to disable the right-click and also panning abilities.

### ISSUE THREAD

**Issue by caralmar** [dceejay/RedMap#60]
Hi, first, thanks for this amazing mapping capability.  In my app, I am displaying a "mini-map" with the location of some buildings.  The app allows the user to click on a specific building (a marker) and then the app displays data about the building.  I want to be able to disable the panning capability as well as the right-click, as there is no functionality in the app to add new markers, but I cannot disable this in the map.  Also, since the map is for information only, I would like to disable the panning feature.  Thanks.

**Comment by dceejay** [comment]
not unreasonable suggestions. I have added the ability to specify these via the commands. The example below will turn on and off panning, zooming, and the right click

```
[{"id":"b4f06c7e.25303","type":"inject","z":"d511095d.512808","name":"","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"hide":false,"x":110,"y":1460,"wires":[["420581ae.b91da"]]},{"id":"420581ae.b91da","type":"function","z":"d511095d.512808","name":"Lock map","func":"msg = { \n    payload: {\n        command: {\n            panlock: msg.payload, \n            zoomlock: msg.payload,\n            hiderightclick: msg.payload\n        }\n    }\n};\nreturn msg;","outputs":1,"noerr":0,"x":280,"y":1460,"wires":[["9bea779a.ac91a8"]]},{"id":"563ffb23.e1c7a4","type":"inject","z":"d511095d.512808","name":"","topic":"","payload":"false","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"hide":false,"x":110,"y":1500,"wires":[["420581ae.b91da"]]}]
```
