### ISSUE TITLE
[UI] Created markers with a color change back to red after drag and drop

### ISSUE THREAD

**Issue by oliv3** [dceejay/RedMap#61]
Hello,

Using this function between a worldmap in and a worldmap out (1.5.14)
```js
if (msg.payload.action == "point") {
    var date = new Date();
    var newMarker = {
        payload: {
            name: "CSU/" + Math.round(date.getTime() / 1000),
            description: msg.payload.name,
            lat: msg.payload.lat,
            lon: msg.payload.lon,
            iconColor: "#000000",
            icon: "fa-warning",
            layer: "CSU",
            added: date,
            draggable: true
        }
    }
    
    msg.payload.deleted = true;
    
    return [[msg, newMarker]];
} else
    return msg;
```

The newly created marker is displayed correctly with a black icon.
Using drag and drop on this marker:
1. Color changes back to red all the time 
2. Sometimes the marker disappears after one or two drag and drops
3. Using drag and drop in another connected client than the one where the marker was created only updates in this client, not the original one
4. Sometimes newly created markers just appear and go away, reloading the web page is necessary to make this work again

Those many errors may show an obvious bug in this function, but I can't see why this wouldn't work.
Am I missing something ?

Thanks !

**Comment by dceejay** [comment]
Something weird going on with the clustering plugin. I'll push a new version that lets you set the clusterAt to 0 to disable all clustering, which seems to fix it for me. 
(Don't forget to delete the _sessionid if you want all screens to update)
