### ISSUE TITLE
Worldmap marker click action to bring icon popup text box 

### ISSUE THREAD

**Issue by snaHammond** [dceejay/RedMap#62]
Hi Dave,

My colleague and I are very happy to inform you that your worldmap node is awesome! 

We are able to access the name, lat and lon when the marker is clicked. We want to know if it is possible to get access to the "icon popup text box" data, (meaning the other properties we added to the payload). 

We want this data show that we can show in a a form. 

We will be on standby for clarification of our question, thanks for all the work you have done so far.

Thanks.
Samuel and Adiel

**Comment by dceejay** [comment]
the properties are there when you sent them to the map - you can correlate the name of the marker with those properties back on the server side.

**Comment by dceejay** [comment]
No further information provided - closing
