### ISSUE TITLE
Imagebounds move over overlay

### ISSUE THREAD

**Issue by chamo1101** [dceejay/RedMap#63]
Hi and thanks for your great job.
I have an issue when i put an image bound on an map.
When i zoom on it, the background map is ok but the image added move.

Can you help me ?

Tanks a lot

**Comment by dceejay** [comment]
Not without a lot more info :-)

How can I re-create the error ?  Is the image geo-referenced ? Can you share your flow and the image ? WHich version of worldmap are you using ? Which browser / OS ?

**Comment by dceejay** [comment]
no further response - closing
