### ISSUE TITLE
Max-Age configuration option is not taken into account

### ISSUE THREAD

**Issue by hubertguillemain** [dceejay/RedMap#64]
**Reproduction step:**
- In the worldmap-out node, configure the max-age to any value (especially, 0)
- When sending markers to the map, do not set the ttl property

**Expected result**
The max-age visible in the user menu is by default the one configured in the worldmap-out node
The markers stay on the map for the configured time (or forever if the configured time is 0)

**Actual result**
The max-age visible in the user menu remains 600
The markers disappear after 600 seconds unless ttl has been set.

**Comment by dceejay** [comment]
fixed - pushed as version 1.5.17

**Comment by stefanoco** [comment]
still not working, is this possible?

**Comment by stefanoco** [comment]
it seems to me that an age of 10s is always taken into account

**Comment by hubertguillemain** [comment]
Make sure you have:
- updated to latest version of worldmap node
- made *multiple* times refresh of browser without cache, Ctrl +F5, Ctrl+R

**Comment by stefanoco** [comment]
Ok now I see after measuing more carefully. I'm switching to a new issue.
