### ISSUE TITLE
Markers expiry time check every 20 seconds

### ISSUE THREAD

**Issue by stefanoco** [dceejay/RedMap#68]
maxage (UI setting) and ttl (message payload property) are options that should determine a timeout for markers: any marker gets deleted after maxage seconds from its creation, or ttl seconds if defined.

But the function responsible for cleaning gets called every 20 seconds (see [this line of code](https://github.com/dceejay/RedMap/blob/f4eb6104387c69f4bd96230f4f7ef43637cfd304/worldmap/index.html#L361)).

Why not more often?

**Comment by dceejay** [comment]
If you have loads of markers then it has to check them all. Which could affect performance, for what is essentially a background task. Does it cause an issue ?
