### ISSUE TITLE
How does the user close the popup on a marker?

### ISSUE THREAD

**Issue by caralmar** [dceejay/RedMap#70]
There is on "X" on the marker popup.  When the user clicks on a marker, the popup displays the data I want, but since there are many markers in the vicinity, the popup does not allow the user to click on the other markers and there is no way to close the popup.

Without popup:
![image](https://user-images.githubusercontent.com/26122325/53048068-eb8eff00-3461-11e9-863d-166cbeec4264.png)

With popup, I can't click on the marker behind the popup:
![image](https://user-images.githubusercontent.com/26122325/53048100-fba6de80-3461-11e9-8db6-2fc5f3dea6cd.png)

**Comment by dceejay** [comment]
which browser / os is this on ? which version of the worldmap node ? there should be a close button...

**Comment by caralmar** [comment]
Hi,

Chrome:
![image](https://user-images.githubusercontent.com/26122325/53115040-2866fe80-3513-11e9-9c98-98e0bb1b2aee.png)

Worldmap:
![image](https://user-images.githubusercontent.com/26122325/53115078-3fa5ec00-3513-11e9-842a-733ecb1e56f4.png)

Also, the popup is a custom one I passed in using the "popup" tag:
![image](https://user-images.githubusercontent.com/26122325/53115161-7aa81f80-3513-11e9-9fa8-8c937182340d.png)

**Comment by caralmar** [comment]
Sorry, forgot to ask... is there a way to control the size of the icon used in the marker?

**Comment by dceejay** [comment]
separate question - but yes if you use the fa-icons on their own - you can specify the icon like
    "fa-bug fa-2x fa-rotate-90" 
for example to set the size and rotation

**Comment by dceejay** [comment]
fix pushed as version 1.5.24
