### ISSUE TITLE
Some map tiles are loaded over http

### ISSUE THREAD

**Issue by oliv3** [dceejay/RedMap#71]
Hi, I was tuning CSP server side, and noticed that some tiles are loaded over http:

`Content Security Policy: The page’s settings blocked the loading of a resource at http://tile.stamen.com/watercolor/10/504/341.jpg (“img-src”).`

This is for "Terrain" and "Watercolor" layers. Since I'm enforcing https everywhere, would it be possible to load those tiles using https ?

It seems like there's a certificate issue with https://tile.stamen.com, but found this on their github repository: https://github.com/stamen/maps.stamen.com/pull/126/commits/a84c1d8e8f64f333c91a081de8c6e37d50d9ebf6

**Comment by dceejay** [comment]
Yes should be possible.

**Comment by dceejay** [comment]
pushed fix as version 1.5.26
