### ISSUE TITLE
Custom markers persistence

### ISSUE THREAD

**Issue by oliv3** [dceejay/RedMap#72]
Would it be feasable to add some kind of internal storage to remember custom markers (markers and attributes) ?
Right now, when a worldmap is reloaded, all created markers disappear; this can be problematic because a user might reload the page by error.
Or can this persistence be achieved another way ? Thanks !

**Comment by oliv3** [comment]
Also, a page reload may be triggered by someone deploying the node with an updated configuration.

**Comment by dceejay** [comment]
the `worldmap in` node gets a connect message whenever a client connects - you can use that to trigger a resend of whatever data you wish. This allows you to persist the data in any way you wish on the server side.

**Comment by oliv3** [comment]
Ok, thanks ! Now I see this was documented [here](https://www.npmjs.com/package/node-red-contrib-web-worldmap#events-from-the-map), sorry for the noise.
