### ISSUE TITLE
Make markers undeletable

### ISSUE THREAD

**Issue by oliv3** [dceejay/RedMap#73]
Hi, following the hints given in https://github.com/dceejay/RedMap/issues/72, I store markers using a `file` node, and use `worldmap in`'s `"connected"` event to reinject them on the map.
This works perfectly, but users can still delete them with a right-click.
Would it be possible to add a `deletable` property, which would default to _true_ for backwards compatibility, like there is a `draggable` property ? Thanks again !

**Comment by dceejay** [comment]
Can you not use the hiderightclick control ?

https://flows.nodered.org/node/node-red-contrib-web-worldmap#controlling-the-map

**Comment by oliv3** [comment]
From what I read in this documentation:
> hiderightclick - disables the right click that allows adding points to the map

What I need here is to disable the right click that allows _removing_ points - That is, user can add points, but can not remove some of them. Did I miss something ?

**Comment by dceejay** [comment]
it disables both adding and removing. I'll clarify the docs.

**Comment by oliv3** [comment]
Sorry if I was unclear, I would need to allow users to add points, still prevent them for deleting others. Use case is that I feed custom markers, pretty much like a POI layer, and don't want users to remove them.

**Comment by oliv3** [comment]
@dceejay hello, any thoughts on this ?

**Comment by dceejay** [comment]
Yes - draggable is a native property of the marker, and I don't just want to add a property to the marker.
I am thinking about making the context menu configurable (like the popup for example) - which would then let you specify whatever you wanted in there (ie nothing).

**Comment by oliv3** [comment]
Whatever suites you, now I found out "draggable" is Leaflet-specific, configurable popup menus would be great, or even better.

**Comment by dceejay** [comment]
published version 1.5.32 that allows you to set `.contextmenu` to html for the right click on marker menu. Setting it to `""` - blank string - will disable the right click on that marker.
Also includes an updated sockjs.min.js

**Comment by oliv3** [comment]
Definitely have to test this. Will keep you informed. Thanks again for this great work !

**Comment by oliv3** [comment]
Definitely have to test this. Will keep you informed. Thanks again for this great work !

**Comment by oliv3** [comment]
Just made some more tests, and can confirm https://github.com/node-red/node-red/issues/1717 is fixed, at least for me.
So, I tried setting `contextmenu: "<p><font color=\"blue\"><b>Hello,</b><br><i>world !</i></font></p>"` and it worked fine.
But, setting `contextmenu: ""` (empty string) did not, the delete button was here.
`" "` (a single space) worked, though: a pop-up without the delete button, and the cross to close it.
I thought setting it to empty string would completely disallow the right click ?
Not a big matter, at least the delete button doesn't appear so I'm fine with that. Many thanks once again.

**Comment by dceejay** [comment]
hmm will check - is certainly supposed to remove it totally :-)...
If it doesn't it will  soon...

**Comment by oliv3** [comment]
Just tried 1.5.34 and it works like a charm !

**Comment by oliv3** [comment]
Hi, sorry for the bad news but while this works perfectly on a workstation, markers are still removable when viewing the worldmap on a mobile phone. To reproduce, I made the popup with the delete button show up with a long press on a marker :( Android/Firefox/Chrome.

**Comment by oliv3** [comment]
OK, seems this was a cache issue. Looks fine, I hope.
