### ISSUE TITLE
Markers icons not found

### ISSUE THREAD

**Issue by ThibautRuy** [dceejay/RedMap#77]
Some of the markers icons like uav, plane, arrow are appearing as not found image, any idea what is wrong here ?

msg.payload = { "name":reg, icon:"uav",  "callsign":Call, "id":id, "operator":op, "bearing":trak, "model":Mdl, "alt":Alt, speed:spd , "lat":lat, "lon":lon};
msg.payload.command={layer:"Esri",lat:lat,lon:lon,zoom:5};

![image](https://user-images.githubusercontent.com/14328511/53679663-bab79100-3ccf-11e9-93b3-6acb47760cc6.png)

**Comment by dceejay** [comment]
Hi, which OS ? Browser ? and map node version are you using ?
Is there anything reported in the browser console log (developer tools javascript console) ?

I used to see this when the inline svg didn't have correct xml headers - but that was fixed ages ago... or so I thought.

**Comment by flyturbo** [comment]
I reporting same issue, most of the icons, can't be found. This was working on my previous Raspberry Pi build about 6 months ago. The plane, uav, car, ecc. 
Here is the source for the car icon;
<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cHM6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cHM6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IiB3aWR0aD0iNDdweCIgaGVpZ2h0PSI0N3B4IiB2aWV3Qm94PSIwIDAgNDcgNDciPjxwYXRoIGQ9Ik0yOS4zOTUsMEgxNy42MzZjLTMuMTE3LDAtNS42NDMsMy40NjctNS42NDMsNi41ODR2MzQuODA0YzAsMy4xMTYsMi41MjYsNS42NDQsNS42NDMsNS42NDRoMTEuNzU5ICAgYzMuMTE2LDAsNS42NDQtMi41MjcsNS42NDQtNS42NDRWNi41ODRDMzUuMDM3LDMuNDY3LDMyLjUxMSwwLDI5LjM5NSwweiBNMzQuMDUsMTQuMTg4djExLjY2NWwtMi43MjksMC4zNTF2LTQuODA2TDM0LjA1LDE0LjE4OHogICAgTTMyLjYxOCwxMC43NzNjLTEuMDE2LDMuOS0yLjIxOSw4LjUxLTIuMjE5LDguNTFIMTYuNjMxbC0yLjIyMi04LjUxQzE0LjQxLDEwLjc3MywyMy4yOTMsNy43NTUsMzIuNjE4LDEwLjc3M3ogTTE1Ljc0MSwyMS43MTMgICB2NC40OTJsLTIuNzMtMC4zNDlWMTQuNTAyTDE1Ljc0MSwyMS43MTN6IE0xMy4wMTEsMzcuOTM4VjI3LjU3OWwyLjczLDAuMzQzdjguMTk2TDEzLjAxMSwzNy45Mzh6IE0xNC41NjgsNDAuODgybDIuMjE4LTMuMzM2IGgxMy43NzFsMi4yMTksMy4zMzZIMTQuNTY4eiBNMzEuMzIxLDM1LjgwNXYtNy44NzJsMi43MjktMC4zNTV2MTAuMDQ4TDMxLjMyMSwzNS44MDV6IiBmaWxsPSJyZWQiLz48L3N2Zz4=" style="width:32px; height:32px; -webkit-transform:rotate(242deg); -moz-transform:rotate(242deg);">

This is what  see;
![capture](https://user-images.githubusercontent.com/20879074/53694841-32de8f00-3d82-11e9-85df-557df34e0f3b.JPG)

**Comment by ThibautRuy** [comment]
I upgraded to the latest version but the problem was still here on Chrome and Safari for Mac iOS.
Then I checked on Chrome on Windows 10 and there was no problem. Then I restarted my Mac, cleared my Chrome Cache, and the problem disappeared.

I tried again with Safari, the problem was here. I cleared the history/cache. The problem is now solved.
It seems it is OS dependent and because of cache.

**Comment by ThibautRuy** [comment]
@flyturbo can you please try to apply the same solution, clearing your browser cache?

**Comment by SteampunkProfessor** [comment]
I've lost the icons too. The emoji icons and fa- icons are there but not the car, plane, iss etc. Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Tibo <notifications@github.com> Date: 03/03/2019  14:37  (GMT+00:00) To: dceejay/RedMap <RedMap@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [dceejay/RedMap] Markers icons not found (#77) @flyturbo can you please try to apply the same solution, clearing your browser cache?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dceejay/RedMap","title":"dceejay/RedMap","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/dceejay/RedMap"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ThibautRuy in #77: @flyturbo can you please try to apply the same solution, clearing your browser cache?"}],"action":{"name":"View Issue","url":"https://github.com/dceejay/RedMap/issues/77#issuecomment-469029235"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dceejay/RedMap/issues/77#issuecomment-469029235",
"url": "https://github.com/dceejay/RedMap/issues/77#issuecomment-469029235",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by flyturbo** [comment]
> I've lost the icons too. The emoji icons and fa- icons are there but not the car, plane, iss etc. Sent from my Samsung Galaxy smartphone. -------- Original message --------From: Tibo <notifications@github.com> Date: 03/03/2019 14:37 (GMT+00:00) To: dceejay/RedMap <RedMap@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [dceejay/RedMap] Markers icons not found (#77) @flyturbo can you please try to apply the same solution, clearing your browser cache? —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread. {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dceejay/RedMap","title":"dceejay/RedMap","subtitle":"GitHub repository","main_image_url":"[https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open](https://github.githubassets.com/images/email/message_cards/header.png%22,%22avatar_image_url%22:%22https://github.githubassets.com/images/email/message_cards/avatar.png%22,%22action%22:%7B%22name%22:%22Open) in GitHub","url":"[https://github.com/dceejay/RedMap"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ThibautRuy](https://github.com/dceejay/RedMap%22%7D%7D,%22updates%22:%7B%22snippets%22:%5B%7B%22icon%22:%22PERSON%22,%22message%22:%22@ThibautRuy) in #77: @flyturbo can you please try to apply the same solution, clearing your browser cache?"}],"action":{"name":"View Issue","url":"[#77 (comment)](https://github.com/dceejay/RedMap/issues/77#issuecomment-469029235)"}}} [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[#77 (comment)](https://github.com/dceejay/RedMap/issues/77#issuecomment-469029235)", "url": "[#77 (comment)](https://github.com/dceejay/RedMap/issues/77#issuecomment-469029235)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

 Upgraded to v1.5.29 and seems to have fixed the issue but now am seeing refresh issues. Icons are not refreshing properly. I will clear cache and try on different browsers and report back. Thx.

**Comment by ewrayjohnson** [comment]
I was also having this problem and upgrading v1.5.29 has fixed the special icons for me.
However, I still cannot get the font-awseome icons to appear.

**Comment by dceejay** [comment]
How are you trying to load them ? Which browser, which version of worldmap ? Have you flushed the cache as suggested above ?

**Comment by dceejay** [comment]
Any more updates ? Still a problem ?

**Comment by ewrayjohnson** [comment]
No, I neglected ‘again’ to select display complete message for my debug
node.

**Comment by dceejay** [comment]
No (as in no more updates yet) or No (no longer a problem) ? :-)

**Comment by ewrayjohnson** [comment]
I still cannot get the FontAwesome icons to appear.

**Comment by dceejay** [comment]
which browser / OS are you using to view the map ?

**Comment by ewrayjohnson** [comment]
Chrome browser on Windows

**Comment by dceejay** [comment]
just managed to fire up my vm with a clean version fo chrome ... all icons there.
Can you share a small part of your flow just to check (as the original issue above was about my svg plane icons not fa-icons... which you seem to be having issue with.)
Are there any messages in the browser console ? (developer tools - javascript console)

**Comment by ewrayjohnson** [comment]
So, I can get many icons to work now, but not this one as an example:
https://fontawesome.com/icons/broadcast-tower?style=solid
Possibly its is a font-awesome version issue?

**Comment by ewrayjohnson** [comment]
[
	{
		"id": "7af9b5de.7dec3c",
		"type": "inject",
		"z": "34400427.0b988c",
		"name": "",
		"topic": "",
		"payload": "{\"name\":\"SBC TOWER HOLDINGS LLC\",\"lat\":34.71616666700004,\"lon\":-92.28036111099993,\"icon\":\"wifi\"}",
		"payloadType": "json",
		"repeat": "",
		"crontab": "",
		"once": false,
		"onceDelay": 0.1,
		"x": 210,
		"y": 240,
		"wires": [
			[
				"6fb25d1f.168dd4"
			]
		]
	},
	{
		"id": "6fb25d1f.168dd4",
		"type": "worldmap",
		"z": "34400427.0b988c",
		"name": "",
		"lat": "34.71616666700004",
		"lon": "-92.28036111099993",
		"zoom": "18",
		"layer": "",
		"cluster": "",
		"maxage": "",
		"usermenu": "show",
		"layers": "show",
		"panit": "false",
		"panlock": "false",
		"zoomlock": "false",
		"hiderightclick": "false",
		"path": "/worldmap",
		"x": 460,
		"y": 240,
		"wires": []
	},
	{
		"id": "fbb444ef.c7e928",
		"type": "inject",
		"z": "34400427.0b988c",
		"name": "",
		"topic": "",
		"payload": "{\"name\":\"SBC TOWER HOLDINGS LLC\",\"lat\":34.717,\"lon\":-92.282,\"icon\":\"volume-up\"}",
		"payloadType": "json",
		"repeat": "",
		"crontab": "",
		"once": false,
		"onceDelay": 0.1,
		"x": 210,
		"y": 320,
		"wires": [
			[
				"6fb25d1f.168dd4"
			]
		]
	},
	{
		"id": "b9f14cdb.7f20b",
		"type": "inject",
		"z": "34400427.0b988c",
		"name": "",
		"topic": "",
		"payload": "{\"name\":\"SBC TOWER HOLDINGS LLC\",\"lat\":34.71616666700004,\"lon\":-92.28036111099993,\"icon\":\"broadcast-tower\"}",
		"payloadType": "json",
		"repeat": "",
		"crontab": "",
		"once": false,
		"onceDelay": 0.1,
		"x": 210,
		"y": 160,
		"wires": [
			[
				"6fb25d1f.168dd4"
			]
		]
	}
]

**Comment by dceejay** [comment]
there is no plan - as the base Node-RED already uses 4.7 - and the differences are significant enough to break everything. All the links in the docs should point to the 4.7 versions so should be easy enough to find ones that work.

Next task (now under way) is to try to get leaflet updated to 1.4.

**Comment by dceejay** [comment]
You could also use an image if you wish eg 
Either hosted locally or remote.

```
msg.payload = {
    name:"TV mast",
    icon:"http://icons.iconarchive.com/icons/icons8/windows-8/32/Industry-Radio-Tower-icon.png",
    lat:51.05,
    lon:-1.35
}
```
