### ISSUE TITLE
All map layers are not available in the configuration

### ISSUE THREAD

**Issue by oliv3** [dceejay/RedMap#83]
Hi, I can select "Watercolor" as a map layer, in the worldmap window.
But, I can't select it from the configuration dialog box in the editor ?
![Screenshot_2019-03-19_02-10-37-b](https://user-images.githubusercontent.com/84910/54573648-745f7300-49ed-11e9-9cc3-c33f5cea71ca.png)

**Comment by oliv3** [comment]
Also, these layers don't show up in the worldmap page:
* UK OS Opendata
* Hike Bike
* UK OS 1919-47
* UK OS 1900

**Comment by dceejay** [comment]
HikeBike comes from https://hikebikemap.org/ which does indeed seem to be fairly dead at the moment... no idea if this is permanent or not.

UK layers only cover the UK area but should work OK.

Hide from where ? the user view ?

**Comment by oliv3** [comment]
UK layers work, yes, but just for UK. At first I was surprised because my default map center and zoom were in another part of the world, so there was only an empty layer. Zooming off of course showed the UK in the end. Well, one can live with them in the drop-down menu of the user view, and that would mean adding another option in the node configuration, not really needed. So it's just a detail.
I'd like to be able to select "Watercolour" in the configuration node, though :)

**Comment by dceejay** [comment]
ok - will tidy -up and add ability to delete layers via a command so you can clean up on connect if you like

**Comment by oliv3** [comment]
Oh, perfect ! Thanks.

**Comment by dceejay** [comment]
example - function to clear up a lot of layers

 ```
msg.payload = {command:{
    map:{
        delete:[
            "UK OS 1919-47",
            "UK OS 1900",
            "UK OS Opendata",
            "Hike Bike",
            "Terrain",
            "Nat Geo",
            "Watercolor",
            "ship nav",
            "public transport",
            "heatmap",
            "railways",
            "roads"
        ]
    }
}};
return msg;
```

**Comment by oliv3** [comment]
Great, many thanks again !
