### ISSUE TITLE
contextmenu $name not replaced

### ISSUE THREAD

**Issue by oliv3** [dceejay/RedMap#84]
Hi, testing the `$name` replacement feature in `.contextmenu`, I inject a single marker on the map:

```js
var contextmenu = "$name";

msg.payload = {
    name: "Test",
    lat: 48.83658839192869,
    lon: 2.4314117431640625,
    icon: "fa-warning",
    iconColor: "yellow",
    contextmenu: contextmenu,
    draggable: true
};

return msg;
```
Right-clicking on the marker:
![Screenshot_2019-03-24_15-46-33](https://user-images.githubusercontent.com/84910/54881073-3f6b7a00-4e4c-11e9-9c1c-631b35fb6ea5.png)
Worldmap version 1.5.35.

**Comment by oliv3** [comment]
If I set contextmenu to:
`<button onclick=\"alert('coucou');\">Click me</button>`, the alert box pops up as expected.

But, if I set contextmenu to:
`<button onclick=\"ws.send(JSON.stringify({action:\"confirm\", name:\"Test\"}));\">Click me</button>` 

(I'm hardcoding `"Test"` here, since `$name` expansion doesn't seem to work, the content in the `<div>` is expanded to:
`<button onclick="ws.send(JSON.stringify({action:" confirm",="" name:"test"}));"="">Click me</button>`, which is really weird ?

**Comment by oliv3** [comment]
Also, setting contextmenu to:
`<button onclick=\"ws.send(JSON.stringify({action:\"confirm\", marker:\"Test\"}));\">Click me</button>`
(Here replacing `name` by `marker`), the expanded result is:
`<button onclick="ws.send(JSON.stringify({action:" confirm",="" marker:"test"}));"="">Click me</button>`, which is also strange (notice the space before `confirm` , the `=""`after and the lower-case `"test"`).
Maybe I'm doing something wrong ?

**Comment by dceejay** [comment]
Yeah - dumb bug in there... once fixed this should work

```
var contextmenu = '<button onclick=\'ws.send(JSON.stringify({action:"confirm", name:"$name"}))\'>Click me</button>'
msg.payload = {
    name: "Test",
    lat: 51.1,
    lon: -1.42,
    icon: "fa-warning",
    iconColor: "yellow",
    contextmenu: contextmenu,
    draggable: true
};
return msg;
```

**Comment by oliv3** [comment]
Is quoting the bug ? (single quotes instead of double quotes ?)
Anyway, just tried that and here's what I receive from `worldmap in`:
```js
{"payload":{"action":"confirm","name":"$name"},"topic":"worldmap","_sessionid":"a8033715-a4b4-4b3d-ab18-1fe0d1a23d01","_msgid":"1bd3bad1.6e7505"}
```

**Comment by dceejay** [comment]
just pushed 1.5.36 with the fix
![image](https://user-images.githubusercontent.com/5375409/54886936-61352300-4e85-11e9-804e-37482f0b78a0.png)
![image](https://user-images.githubusercontent.com/5375409/54886938-6befb800-4e85-11e9-8627-ac6ed96324af.png)

**Comment by oliv3** [comment]
Oh ok, so the bug was on your side ? :)

**Comment by dceejay** [comment]
both - I was failing the substitution. You were failing the quotes.

**Comment by oliv3** [comment]
May I suggest some clarification regarding quoting in the documentation then ? I'm not *that* familiar with JS, and others may fall in that trap.

**Comment by dceejay** [comment]
where would that fit ? It's all javascript :-)

How about this

#### To add a custom popup or contextmenu

You can customise the a marker's popup, or context menu (right click), by setting the 
appropriate property to an html string. Often you will need some embedded javascript
in order to make do something when you click a button for example. You need to be careful 
escaping quotes, and that they remain matched.

For example a popup with a slider

    popup: '<input name="slide1" type="range" min="1" max="100" value="50" onchange=\'feedback(this.name,this.value)\' style="width:250px;">'

Or a contextmenu with a button

    contextmenu: '<button name="Clicker" onclick=\'feedback(this.name)\'>Click me</button>'

**Comment by oliv3** [comment]
Looks good :) Thanks for the fix !
