### ISSUE TITLE
Markers disappearing after some (5 or 6) moves

### ISSUE THREAD

**Issue by oliv3** [dceejay/RedMap#85]
Hi, so I have my worldmap-based application where I can move markers around, and changes are propagated OK to all clients by deleting `msg._sessionid`.
But, after a few moves, basically 5 or 6, markers start disappearing from the map (in the client where moves originated), still being propagated to all clients.
From the other clients, I can move the marker 2 or 3 times more, then it also disappears.
Refreshing the page everywhere correctly displays the last known/updated locations for the markers.

**Comment by dceejay** [comment]
And they aren't just timing out ?
How can I simulate/reproduce this ?

**Comment by oliv3** [comment]
If by "timing out" you mean reaching TTL, then I'd say now. This was done moving by hand a marker on the map, approx. 1 second interval.
To reproduce, can try to make a minimal case, it would be something like
`worldmap in` -> `function` that filters `"move"` -> `change` that deletes `msg._sessionid` -> `worldmap`
Then run this with at least two connected clients (in my case was a laptop and a mobile), create a marker from the map.

**Comment by oliv3** [comment]
Thinking of it, I use a `KV store` node in between to store/retrieve markers by their name.

**Comment by oliv3** [comment]
I'm afraid I can't post those flows publicly..

**Comment by oliv3** [comment]
Hmm, testing on my phone, just noticed that:
* move a marker, it disappears
* pan the map a little, it reappears
So maybe it's a Leaflet issue ?

**Comment by dceejay** [comment]
is an odd one - my simple test flow (below) - with three open browsers (chrome, Firefox and safari) lets me add, move and delete markers no problem. Must be a subtle timing thing somewhere.

```
[{"id":"c85f4997.5de2e8","type":"worldmap","z":"ff27ff95.cc8d5","name":"","lat":"51.05","lon":"-1.35","zoom":"","layer":"","cluster":"","maxage":"","usermenu":"show","layers":"show","panit":"false","panlock":"false","zoomlock":"false","hiderightclick":"false","coords":"none","path":"/worldmap","x":700,"y":120,"wires":[]},{"id":"7bb44888.47dbf8","type":"worldmap in","z":"ff27ff95.cc8d5","name":"","path":"/worldmap","x":120,"y":120,"wires":[["5a28a7a0.937928","32106c05.d40664"]]},{"id":"5a28a7a0.937928","type":"switch","z":"ff27ff95.cc8d5","name":"","property":"payload.action","propertyType":"msg","rules":[{"t":"eq","v":"connected","vt":"str"},{"t":"eq","v":"disconnect","vt":"str"},{"t":"else"}],"checkall":"true","repair":false,"outputs":3,"x":290,"y":120,"wires":[["d70038a7.5f0f48"],[],["5f7d8e38.8461f","8849d461.d3bb58"]]},{"id":"32106c05.d40664","type":"debug","z":"ff27ff95.cc8d5","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":270,"y":180,"wires":[]},{"id":"5f7d8e38.8461f","type":"debug","z":"ff27ff95.cc8d5","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":450,"y":180,"wires":[]},{"id":"8849d461.d3bb58","type":"change","z":"ff27ff95.cc8d5","name":"","rules":[{"t":"delete","p":"_sessionid","pt":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":480,"y":120,"wires":[["c85f4997.5de2e8"]]}]
```

**Comment by oliv3** [comment]
I'll try your flow back home, did you try the one I sent you via mail ?
Did you try on mobile ? This is how I can trigger that behaviour most easily.

**Comment by oliv3** [comment]
I have strange results by changing the layer:

```
[{"id":"4814f847.e558f8","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"bdede289.30de5","type":"worldmap","z":"4814f847.e558f8","name":"","lat":"51.05","lon":"-1.35","zoom":"","layer":"","cluster":"","maxage":"","usermenu":"show","layers":"show","panit":"false","panlock":"false","zoomlock":"false","hiderightclick":"false","coords":"none","path":"/worldmap2","x":990,"y":180,"wires":[]},{"id":"bc2a918b.23a72","type":"worldmap in","z":"4814f847.e558f8","name":"","path":"/worldmap2","x":180,"y":180,"wires":[["444b73fe.9c2764","409c1e6f.a020b8"]]},{"id":"444b73fe.9c2764","type":"switch","z":"4814f847.e558f8","name":"","property":"payload.action","propertyType":"msg","rules":[{"t":"eq","v":"connected","vt":"str"},{"t":"eq","v":"disconnect","vt":"str"},{"t":"else"}],"checkall":"true","repair":false,"outputs":3,"x":430,"y":160,"wires":[[],[],["fca368af.92f668","837a8603.f62c6"]]},{"id":"409c1e6f.a020b8","type":"debug","z":"4814f847.e558f8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":330,"y":240,"wires":[]},{"id":"fca368af.92f668","type":"debug","z":"4814f847.e558f8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":590,"y":240,"wires":[]},{"id":"837a8603.f62c6","type":"change","z":"4814f847.e558f8","name":"","rules":[{"t":"delete","p":"_sessionid","pt":"msg"},{"t":"set","p":"payload.layer","pt":"msg","to":"myLayer","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":740,"y":180,"wires":[["bdede289.30de5"]]}]
```

**Comment by dceejay** [comment]
Aha - that was the clue that was needed (I think )

**Comment by oliv3** [comment]
Great, so you can reproduce ? Fingers crossed :)

**Comment by dceejay** [comment]
yes - fixed (finger crossed) in that update pushed to master above. Please try it.

**Comment by oliv3** [comment]
Is it published ?

**Comment by oliv3** [comment]
(running in docker, so not that easy to test if unpublished)

**Comment by dceejay** [comment]
you can install direct from master with `npm i dceejay/redmap` or the equivalent in package.json.
Will be on npm a bit later.

**Comment by oliv3** [comment]
Just tried, doesn't seem to work. A freshly added marker disappears on the first move.

**Comment by dceejay** [comment]
did you flush the browser cache etc. I was using your flow above to test.

**Comment by oliv3** [comment]
Yes. Shit+reloaded the page, also used "Disable cache" in the developer tools > Network tab.

**Comment by oliv3** [comment]
Also double-checked that the index.html was the latest one.

**Comment by dceejay** [comment]
pushed as version 1.5.37 - 
can you share your latest test flow ?

**Comment by oliv3** [comment]
Should be the same:
```json
[{"id":"4814f847.e558f8","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"bdede289.30de5","type":"worldmap","z":"4814f847.e558f8","name":"","lat":"51.05","lon":"-1.35","zoom":"","layer":"","cluster":"","maxage":"","usermenu":"show","layers":"show","panit":"false","panlock":"false","zoomlock":"false","hiderightclick":"false","coords":"none","path":"/worldmap2","x":990,"y":180,"wires":[]},{"id":"bc2a918b.23a72","type":"worldmap in","z":"4814f847.e558f8","name":"","path":"/worldmap2","x":180,"y":180,"wires":[["444b73fe.9c2764","409c1e6f.a020b8"]]},{"id":"444b73fe.9c2764","type":"switch","z":"4814f847.e558f8","name":"","property":"payload.action","propertyType":"msg","rules":[{"t":"eq","v":"connected","vt":"str"},{"t":"eq","v":"disconnect","vt":"str"},{"t":"else"}],"checkall":"true","repair":false,"outputs":3,"x":430,"y":160,"wires":[[],[],["fca368af.92f668","837a8603.f62c6"]]},{"id":"409c1e6f.a020b8","type":"debug","z":"4814f847.e558f8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":310,"y":240,"wires":[]},{"id":"fca368af.92f668","type":"debug","z":"4814f847.e558f8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":590,"y":240,"wires":[]},{"id":"837a8603.f62c6","type":"change","z":"4814f847.e558f8","name":"","rules":[{"t":"delete","p":"_sessionid","pt":"msg"},{"t":"set","p":"payload.layer","pt":"msg","to":"myLayer","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":740,"y":180,"wires":[["bdede289.30de5"]]}]
```

**Comment by dceejay** [comment]
hmm

**Comment by oliv3** [comment]
With that I now get another marker for free :) Sometimes by moving one, the other disappears (so there's only one). Sometimes, marker duplicates (but there are only 2 max).

**Comment by oliv3** [comment]
The latest flow:
```json
[{"id":"bdede289.30de5","type":"worldmap","z":"4814f847.e558f8","name":"","lat":"51.05","lon":"-1.35","zoom":"","layer":"","cluster":"0","maxage":"","usermenu":"show","layers":"show","panit":"false","panlock":"false","zoomlock":"false","hiderightclick":"false","coords":"none","path":"/worldmap2","x":990,"y":180,"wires":[]}]
```
includes
```json
"cluster":"0"
```
as suggested.

**Comment by oliv3** [comment]
Will do a screencast, is it ok to send the link via private mail ?

**Comment by oliv3** [comment]
https://dl.biniou.net/tmp/vokoscreen-2019-04-01_22-02-37.mp4

**Comment by dceejay** [comment]
yes email is fine

**Comment by oliv3** [comment]
Please find a link in my previous comment

**Comment by dceejay** [comment]
Got it - likewise for me  - it works... http://g.recordit.co/y6eremIBWy.gif

**Comment by oliv3** [comment]
And now it works here. Go figure... Checked with 2 browsers and mobile phone. Will do more testing tomorrow. Thanks !

**Comment by oliv3** [comment]
Should I leave clustering to 0 for the moment ?

**Comment by dceejay** [comment]
yes - I would say unless you need it - don't use it.
I'm thinking of making it the default. 
Opinion ?

**Comment by oliv3** [comment]
I don't really have an opinion, since I don't use the clustering feature for now - so 0 as a default would be ok for my use case. Don't know for other people, though.
Anyway, clustering is a global feature, right ? Had I to use it, it would be per layer - but for now hiding layers with too many markers is ok.

**Comment by oliv3** [comment]
https://github.com/dceejay/RedMap/commit/e2e3e439cb4c2c0ad9bd5075c649d05117fd95bf probably fixed this issue ?
Now I set clustering back to undefined instead of forcing to 0 and it seems to work.
