### ISSUE TITLE
[Feature request] Marker expiration date and feedback event

### ISSUE THREAD

**Issue by oliv3** [dceejay/RedMap#86]
Hi, setting the `ttl` property for a marker works fine.

As per the documentation,
```
ttl : time to live, how long an individual marker stays on map in seconds (overrides general maxage setting, minimum 20 seconds)
```

But, the marker is removed from the map and there is no event telling it's been removed.

It would be nice to be able to:
* Set an `expiration` date (e.g., marker has to be removed when t > 2019-03-28T12:39:45.941Z)
* Get a message from `worldmap in` stating e.g. `{expired, markername}` so that one could remove the marker if it is stored in some external storage

This way we could have absolute TTL instead of relative TTL ?

**Comment by dceejay** [comment]
why not handle that at the backend and just send a delete message whenever you want ?

**Comment by oliv3** [comment]
Hmm, right. And also using a inject node as a cron job to check if markers need removal. Thanks for the idea !
