### ISSUE TITLE
Making onLocationFound configurable

### ISSUE THREAD

**Issue by oliv3** [dceejay/RedMap#89]
Hi,

I'm using the worldmap in an iframe. From the parent document, I tried overriding the current onLocationFound callback like this:

```javascript
            function myLocationFound(e) {
                var radius = e.accuracy;
                alert("radius: " + radius);
            }

            // Center map
            function center() {
                var win = document.getElementById('ifrm').contentWindow;
                win.map.on('locationfound', myLocationFound);
                win.map.locate({setView: true, maxZoom: 17});
            }
```

I get the popup, but the old code gets executed: https://github.com/dceejay/RedMap/blob/878ba17b4370e07a4660c7a68a816d8b590a3772/worldmap/index.html#L664

So it seems that using `map.on('locationfound', function);` stacks the callbacks ?
And I've not found (or missed) a way to unregister a callback.

**Comment by dceejay** [comment]
I guess I could only enable it when not in an iframe. IE only add the callback if the button exists.

**Comment by oliv3** [comment]
Sounds like a plan.

**Comment by oliv3** [comment]
Great ! When will it be available on https://libraries.io/npm/node-red-contrib-web-worldmap/ ?

**Comment by dceejay** [comment]
when I get round to publishing it.
Busy looking at trying to upgrade leaflet to 1.x branch.

**Comment by dceejay** [comment]
PS. I published version 2.0.0-beta if you want to try it. (which uses the leaflet 1.4 branch) - must be manually installed.

**Comment by oliv3** [comment]
@dceejay I recreated my docker container, and `node_modules/node-red-contrib-web-worldmap/package.json` now has `node-red-contrib-web-worldmap@2.0.1-beta`, so I suppose the upgrade went fine. Still, in `/data/.config.json`, I get
```json
  "node-red-contrib-web-worldmap": {
   "name": "node-red-contrib-web-worldmap",
   "version": "1.5.39",
   "local": true,
   "nodes": {
    "worldmap": {
     "name": "worldmap",
     "types": [
      "worldmap",
      "worldmap in",
      "worldmap-tracks"
     ],
     "enabled": true,
     "local": true,
     "module": "node-red-contrib-web-worldmap",
     "file": "/data/node_modules/node-red-contrib-web-worldmap/worldmap.js"
    }
   }
  },
```
What I don't get is that all other modules are `"local": false`, and I usually don't install anything by hand in the container, I simply recreate it. Any idea what could have gone wrong ? Thanks in advance !

**Comment by oliv3** [comment]
Oh, 1.5.40 has not been officially released yet either ? https://flows.nodered.org/node/node-red-contrib-web-worldmap has 1.5.39, could this be the reason ?

**Comment by dceejay** [comment]
both should be on npm
