### ISSUE TITLE
Trouble Adding Node to Dashboard

### ISSUE THREAD

**Issue by dmeyer302** [dceejay/RedMap#9]
I'm having issues getting this node added to my dashboard. I cannot find the usual commands (as seen on other UI nodes) to assign the worldmap to a tab or a group. As such, it never appears on the dashboard anywhere.

I have successfully imported and used the "Move Mike" example, but I can't seem to create a clean-sheet worldmap.

Any help appreciated.

**Comment by dceejay** [comment]
Hi - what do you mean by a clean-sheet worldmap ?
It is not a Dashboard widget - it is "only" a standard Node-RED node - so just creates a Web endpoint. The Move Mike example shows how to embed it in an iframe such that it will appear on the Dashboard... it's the ui_template node that sits on the tab and group.

**Comment by dmeyer302** [comment]
Thank you so much for responding. Worldmap being a standard node is a distinction I hadn’t made, and I’m new enough to all of this that sometimes I don’t even know what to google for.

Now I’ve got the template showing up on my dashboard, but the template cannot GET the node (see screenshot). I suspect this is a permission or bad path problem. Do you have a suggestion?

Thanks again,
Daniel

**Comment by dceejay** [comment]
in the template it will be pointing to the map - you can try that url just in a separate browser window to test it. The path will depend where you are serving your Node-RED endpoints from... so slightly tricky to advise.
