### ISSUE TITLE
[2.0.1-beta] 404 on /worldmap/leaflet/Leaflet.coordinates.js

### ISSUE THREAD

**Issue by oliv3** [dceejay/RedMap#90]
Hi, as the title says, Leaflet.coordinates.js can't be found anywhere ?

**Comment by oliv3** [comment]
I also get these errors, but it may be from my specific deployment:
* TypeError: L.control.coordinates is not a function
* TypeError: delMarker is not a function (I can't indeed remove a marker anymore)

**Comment by dceejay** [comment]
good spot - thanks

**Comment by dceejay** [comment]
closed by fix in 2.0.4-beta
