### ISSUE TITLE
My kingdom for a helicopter that works like plane?

### ISSUE THREAD

**Issue by spydmobile** [dceejay/RedMap#91]
In the wildfire business a good majority of the critical aircraft are rotary wing (Helicopters) This Map Node works great for wildfire Flight Following applications except I have to use planes to show helos, or I have to use my own icons which dont follow the heading like the plane icon, SO I guess Im asking for a helicopter icon (from the top) or else allow the direction to function on a custom icon.

**Comment by spydmobile** [comment]
Thank you for all the work you have done on this very cool node!

**Comment by dceejay** [comment]
nice idea - will see what I can find. simple svg best if you have any you can point at.

**Comment by spydmobile** [comment]
thats great! I use this, and color it based on if its in the air or on the ground, but should work for you
https://www.dropbox.com/s/9tfrk61idko17tg/aff-rw-ground.svg?dl=0

**Comment by dceejay** [comment]
Found this simple one ? - OK ?
![image](https://user-images.githubusercontent.com/5375409/56772912-ea58b600-67b3-11e9-8058-f76d93a8ca54.png)

**Comment by dceejay** [comment]
pushed to npm as part of 2.0.4-beta

**Comment by spydmobile** [comment]
Looks great :D I will give that a go!

**Comment by spydmobile** [comment]
Works! Thank you!!!
