### ISSUE TITLE
[2.0.3-beta] Right context menu on a marker doesn't work anymore

### ISSUE THREAD

**Issue by oliv3** [dceejay/RedMap#92]
Looks like `contextmenu` string replacement on a marker is broken, I get the standard "Delete" button (it used to work in 1.5.39).
Right contextmenu replacement in the map (not on a marker) is ok, though.

**Comment by dceejay** [comment]
brain fade here... sorry... do you have an example / screenshot so I can recreate ?

**Comment by dceejay** [comment]
closed by 2.0.4-beta
