### ISSUE TITLE
(2.0.4-beta) Uncaught TypeError: Cannot read property 'trim' of undefined leaflet.js:5

### ISSUE THREAD

**Issue by spydmobile** [dceejay/RedMap#93]
this is blocking events or icons from populating on the map.
![Screenshot 2019-04-26 10 07 12](https://user-images.githubusercontent.com/1065978/56821342-40a51380-680b-11e9-9d48-8e9c3e9d3461.png)

**Comment by spydmobile** [comment]
This happened quite a few times, then I blew away the cache and reloaded, and it seems to go away. If I cant reproduce, I will come back and close it, sorry...

**Comment by spydmobile** [comment]
Ok confirmed, this happens when clustering is enabled and the zoom level is lower than the cluster threshold.

**Comment by dceejay** [comment]
found there was an old library mismatch - now updated... can you check if this fixes this for you ?
(based on the limited description clustering does seem to work for me at various levels)

**Comment by spydmobile** [comment]
Confirmed fixed, Zoom at 6 with cluster till 7 is now showing correctly! Thanks for the super quick fix!!
