### ISSUE TITLE
support: How to remove "Node-RED - map all the things" Bar

### ISSUE THREAD

**Issue by spydmobile** [dceejay/RedMap#95]
Hi There, 
I realize this might be done with externally added CSS however, is there a simple way to eliminate this bar? Publicizing you are using node red is sometimes an invitation to hack, I want use this map in a semi-public way but not reveal that its node red. Maybe even a feature request to add an on/off feature in the main worldmap out node?

**Comment by dceejay** [comment]
the bar is there when you don't include it in an iframe... if you embed it in an iframe it won't be there, so you can wrap it how you like.

**Comment by spydmobile** [comment]
Ok Ill see if I can make that work, thank you!

**Comment by spydmobile** [comment]
Hmm, ok, so yes, this does remove the bar, but also removes the full screen button, the locate button and  and the measure tool :(

**Comment by dceejay** [comment]
so for fully custom use you can rename the index.html and edit it to include whatever top bar/buttons you like.

**Comment by spydmobile** [comment]
Ahh, great Idea, thanks Dave!

**Comment by dceejay** [comment]
In latest 2.x version I have re-organised the files somewhat to make the index.html much more minimal to make that easier. (IE most of my code will be out of there so can be updated more easily.)
