### ISSUE TITLE
Bug: command->map->delete does not work.

### ISSUE THREAD

**Issue by spydmobile** [dceejay/RedMap#96]
here is a test flow to demonstrate. I have tried every which way to make this work, the only thing that works is the clear command but only on overlays, I cannot remove any base layers using the commands and structures in the readme. 
Im using beta 205 not 206 however.
`[
    {
        "id": "39c8dd78.ff6ef2",
        "type": "worldmap",
        "z": "39ba2730.b4f8c8",
        "name": "",
        "lat": "",
        "lon": "",
        "zoom": "",
        "layer": "",
        "cluster": "",
        "maxage": "",
        "usermenu": "show",
        "layers": "show",
        "panit": "false",
        "panlock": "false",
        "zoomlock": "false",
        "hiderightclick": "false",
        "coords": "none",
        "showgrid": "false",
        "path": "/testmap",
        "x": 540,
        "y": 140,
        "wires": []
    },
    {
        "id": "756b558e.76f41c",
        "type": "inject",
        "z": "39ba2730.b4f8c8",
        "name": "Press to test",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 210,
        "y": 140,
        "wires": [
            [
                "fdd72c1a.c767a"
            ]
        ]
    },
    {
        "id": "fdd72c1a.c767a",
        "type": "function",
        "z": "39ba2730.b4f8c8",
        "name": "Remove layers",
        "func": "msg.payload = {command:{map:{\n    \"delete\":[\"Watercolor\",\"Ship Nav\",\"Heatmap\"]\n}}};\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 380,
        "y": 140,
        "wires": [
            [
                "39c8dd78.ff6ef2"
            ]
        ]
    }
]`

**Comment by dceejay** [comment]
the names are case sensitive (the example is wrong - now fixed).

```
[{"id":"70574879.329888","type":"worldmap","z":"ff27ff95.cc8d5","name":"","lat":"","lon":"","zoom":"","layer":"","cluster":"","maxage":"","usermenu":"show","layers":"show","panit":"false","panlock":"false","zoomlock":"false","hiderightclick":"false","coords":"none","showgrid":"false","path":"/testmap","x":600,"y":1380,"wires":[]},{"id":"d8d48f9f.18487","type":"inject","z":"ff27ff95.cc8d5","name":"Press to test","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":210,"y":1380,"wires":[["18a55f61.34f481"]]},{"id":"18a55f61.34f481","type":"function","z":"ff27ff95.cc8d5","name":"Remove layers","func":"msg.payload = {command:{map:{\n \"delete\":[\"Watercolor\",\"ship nav\",\"heatmap\"]\n}}};\nreturn msg;","outputs":1,"noerr":0,"x":380,"y":1380,"wires":[["70574879.329888"]]}]
```

**Comment by spydmobile** [comment]
Sorry Dave, the new node you posted does not work either, it results in the browser console saying:
`(index):1666 Uncaught TypeError: layercontrol.removeFrom is not a function
    at doCommand ((index):1666)
    at ws.onmessage ((index):197)
    at w.r.dispatchEvent (sockjs.min.js:2)
    at sockjs.min.js:2
    at Array.forEach (<anonymous>)
    at w._transportMessage (sockjs.min.js:2)
    at u.i.emit (sockjs.min.js:2)
    at WebSocket.ws.onmessage (sockjs.min.js:2)`

**Comment by spydmobile** [comment]
does this require a newer version of the map module?

**Comment by dceejay** [comment]
well it certainly works withe latest :-)

**Comment by spydmobile** [comment]
Indeed it does :)  sorry for the extra traffic Dave, I know you are a busy guy ;-)
