### ISSUE TITLE
map crash after some times

### ISSUE THREAD

**Issue by accateo** [dceejay/RedMap#97]
Hi,
I'm using your fantastic component on my Node-Red application.
It's perfect except for a fact. After some minutes the map crashes by itself , without no reason.
You can see here some screenshot:

https://imgur.com/Vkk7jbd

https://imgur.com/2Ti5AgQ

Any idea?
Thanks

**Comment by dceejay** [comment]
no idea - is there anything in the log ? how about the network tab ?

**Comment by accateo** [comment]
Unfortunately nothing in the log....
Maybe the map needs to receive some data every X minutes? Like a refresh? Or there is some space limit?

**Comment by dceejay** [comment]
markers will automatically get removed after  the TTL time - but apart from that no - I'm not aware of any timeouts. When you say some minutes - how long ?  
There may indeed be memory limitations but in general most up date message are only a few bytes - unless you have thousands of points all updating I wouldn't expect a problem with memory. (but again the browser tools can show you a memory graph if you wish).

**Comment by accateo** [comment]
Thank for you response. 
I have only 8 markers and I have no problem with memory limitations. 
Mmm...i don't know. I monitor the situation.

**Comment by accateo** [comment]
Hi again,
I have put together some screenshot during the crash:
https://imgur.com/OqfKJse (the console output in the exact time of the crash)

https://imgur.com/2VZZZH2
https://imgur.com/mGz7zyN

what I see always is that there are some request in pending. Have you any idea about this?
Thanks

**Comment by dceejay** [comment]
no - nothing useful there. sorry.
