### ISSUE TITLE
Missing dependency - L is undefinded

### ISSUE THREAD

**Issue by faltfe** [dceejay/RedMap#98]
I've installed the latest version (2.0.12) using `npm i --save node-red-contrib-web-worldmap`. The plugin is working within the node-red GUI but the actual map is not visible at _{root}/worldmap_.

There is a error in the console saying that `"L is not defined in worldmap.js:108"`.

For the moment I use an older version 1.x which is working fine.

---
- node-red 0.20.5
- Debian Stretch
- nodejs 10.15.3

**Comment by oliv3** [comment]
I also have this issue

**Comment by dceejay** [comment]
Which browser are you using ?

**Comment by oliv3** [comment]
Hi @dceejay, strangely this happens on Firefox but not Chrome.

**Comment by oliv3** [comment]
Firefox 60.7.0esr (64-bit) on Debian.

**Comment by dceejay** [comment]
Can you try latest 2.0.14 ? (I reverted a change to use ES6 import... that I thought would help embedding in other pages.)

**Comment by oliv3** [comment]
Not right now, but will let you know.

**Comment by faltfe** [comment]
I was using Firefox (latest version) too. Unfortunately, I can test your new version not before start of July.

**Comment by oliv3** [comment]
Hi @dceejay, many version bumps :) I can confirm the map is back using Firefox and version 2.0.16.
