### ISSUE TITLE
Deprecated include of L.Mixin.Events

### ISSUE THREAD

**Issue by fencer** [dceejay/RedMap#99]
In chrome the below warning is displayed on leaflet.js
Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead.
![image](https://user-images.githubusercontent.com/620966/59163554-f64dcc80-8b02-11e9-8351-19a973a5c0a4.png)

**Comment by dceejay** [comment]
which version of worldmap is this being reported against ?

**Comment by fencer** [comment]
2.0.12

**Comment by dceejay** [comment]
It's only a warning (at this stage) so nothing to worry about.
It is used by a couple of the plugins (Draw and LatLngGraticule - so they need to fix themselves.
Feel free to tell them about it.

**Comment by dceejay** [comment]
Fixed upstream - will be included in v2.20 or more recent
